### ISSUE TITLE
assert this_truth[index][0] == i[0]

### ISSUE THREAD

**Issue by dinglong1020** [Microsoft/MMdnn#102]
environment ubuntu1604 mmdnn0.13
run command:
          python -m mmdnn.conversion.examples.tensorflow.imagenet_test -s tensorflow -i /home/dinglong1020/workspace/seagull.jpg -p resnet -n tf_resnet152 -w resnet152.npy

2018-03-12 20:53:25.668489: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[(884, 8.249091), (739, 6.701796), (983, 5.8156166), (717, 5.6141443), (589, 4.64553)]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/examples/tensorflow/imagenet_test.py", line 75, in <module>
    tester.inference(tester.args.image)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/examples/tensorflow/imagenet_test.py", line 56, in inference
    self.test_truth()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/examples/imagenet_test.py", line 229, in test_truth
    assert this_truth[index][0] == i[0]
AssertionError

**Comment by kitstar** [comment]
Hi @dinglong1020 , it is a test sample only for tf-slim model conversion and will be deprecated by formal pytest. So you can ignore the assertion.

**Comment by dinglong1020** [comment]
Hi @kitstar so you mean that we can not convert models from IR to Tensorflow model

def _convert(args):
          elif args.framework == 'tensorflow':
                raise NotImplementedError("Destination [Tensorflow] is not implemented yet.")

**Comment by kitstar** [comment]
Hi @dinglong1020 
just use
```bash
python -m mmdnn.conversion.examples.tensorflow.imagenet_test -n tf_resnet152 -w resnet152.npy --dump tf_resnet_model
```
to achieve it. 

And we will provide a more convince method to run our project.

Thanks.
