### ISSUE TITLE
How to Caffe > IR > TensorFlow > frozen graph ?

### ISSUE THREAD

**Issue by marvinrichter** [Microsoft/MMdnn#117]
Platform (like ubuntu 16.04/win10):
Mac OS X

Python version:
2.7

Source framework with version (like Tensorflow 1.4.1 with GPU):
Caffe

Destination framework with version (like CNTK 2.3 with GPU):
TensorFlow

Pre-trained model path (webpath or webdisk path):
Places365-CNN
[Architecture](https://github.com/CSAILVision/places365/blob/master/deploy_vgg16_places365.prototxt), [Weights](http://places2.csail.mit.edu/models_places365/vgg16_places365.caffemodel)

Running scripts:
I'm trying to convert the model to a frozen graph in TensorFlow but I'm missing a file. The steps I do are the following:

1. convert Caffe to IR
    ```bash
    python -m mmdnn.conversion._script.convertToIR \
      -f caffe \
      -n deploy_vgg16_places365.prototxt \
      -w vgg16_places365.caffemodel \
      -d ir_places365
    ```
2. convert IR to TF code
    ```bash
    python -m mmdnn.conversion._script.IRToCode \
      -f tensorflow \
      -n ir_places365.pb \
      -w ir_places365.npy \
      -d tf_places365.py
    ```
3. convert IR to TF model
    ```bash
    python -m mmdnn.conversion.examples.tensorflow.imagenet_test \
      -n tf_places365.py \
      -w ir_places365.npy \
      --dump ./places365.ckpt
    ```
4. freeze graph
    ```bash
    python -m tensorflow.python.tools.freeze_graph \
      --input_graph=places365.pb \ # What should I use as an input graph?
      --input_binary=true \
      --input_checkpoint=./places365.ckpt \
      --output_graph=frozen_places365.pb \
      --output_node_names=prob
    ```

**Comment by kitstar** [comment]
Hi @marvinrichter , could you try to use --input_meta_graph ./places365.ckpt.meta to replace the --input_graph? Thanks.

**Comment by marvinrichter** [comment]
Unfortunately this doesn't work either. I got the following error message:
```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 360, in <module>
    app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 254, in main
    FLAGS.saved_model_tags, FLAGS.checkpoint_version)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 235, in freeze_graph
    input_meta_graph, input_binary)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/tools/freeze_graph.py", line 189, in _parse_input_meta_graph_proto
    text_format.Merge(f.read(), input_meta_graph_def)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 679, in _MergeField
    name = tokenizer.ConsumeIdentifierOrNumber()
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/text_format.py", line 1152, in ConsumeIdentifierOrNumber
    raise self.ParseError('Expected identifier or number, got %s.' % result)
google.protobuf.text_format.ParseError: 2:1 : Expected identifier or number, got ?.
```

**Comment by marvinrichter** [comment]
I just saw that in https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/examples/tensorflow/imagenet_test.py#L59 you are using Saver, which the [documentation](https://www.tensorflow.org/programmers_guide/saved_model#saving_variables) says is for saving variables.

For saving the whole model one should use the [SavedModel API](https://www.tensorflow.org/programmers_guide/saved_model#building_a_savedmodel) instead.

I would create a PR but that would change the behavior and make it a breaking change.

**Comment by kitstar** [comment]
Hi @marvinrichter, in my opinion, the meta file of older version TensorFlow is for saving network architecture. The SavedModel API seems new for me. Please submit a PR and I will figure out how to use the new API.

**Comment by marvinrichter** [comment]
Unfortunately my PR is not complete. For the SavedModel to work their needs to be a SignatureDef included.

**Comment by marvinrichter** [comment]
I've updated my PR and added the signature def for input and output tensors

**Comment by namizzz** [comment]
Thank you @marvinrichter . It's in MMdnn now

**Comment by ronyuzhang** [comment]
how to transfer saved model to frozen model?
