### ISSUE TITLE
Caffe to Tensorflow model ,error!

### ISSUE THREAD

**Issue by xieyufei1993** [Microsoft/MMdnn#133]
caffemodel for ctpn
deploy.prototxt
[deploy.txt](https://github.com/Microsoft/MMdnn/files/1865306/deploy.txt)

error information:
I0331 08:47:32.099702  7859 net.cpp:228] relu1_1 does not need backward computation.
I0331 08:47:32.099707  7859 net.cpp:228] conv1_1 does not need backward computation.
I0331 08:47:32.099712  7859 net.cpp:228] input does not need backward computation.
I0331 08:47:32.099717  7859 net.cpp:270] This network produces output rois
I0331 08:47:32.099723  7859 net.cpp:270] This network produces output scores
I0331 08:47:32.099759  7859 net.cpp:283] Network initialization done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 164, in <module>
    _main()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 159, in _main
    ret = _convert(args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 9, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/transformer.py", line 316, in __init__
    graph = GraphBuilder(def_path, self.input_shape, self.is_train_proto, phase).build()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/graph.py", line 447, in build
    graph.compute_output_shapes(self.model)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/graph.py", line 266, in compute_output_shapes
    node.output_shape = TensorShape(*NodeKind.compute_output_shape(node))
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/graph.py", line 126, in compute_output_shape
    return LAYER_DESCRIPTORS[node.kind](node)
KeyError: None

**Comment by TobeyQin** [comment]
Hi, which caffe model you used? could you provide the caffe model files (both .caffemodel and .prototxt files)?

**Comment by xieyufei1993** [comment]
@TobeyQin ok you can download from this site:
https://pan.baidu.com/s/1kEt8bhDOY-rsceISEsKmDg
thank you very much , look forward to your review.

**Comment by xieyufei1993** [comment]
@kitstar @TobeyQin @namizzz Can this model change from caffe to tensorflow?
