### ISSUE TITLE
Message type "caffe.LayerParameter" has no field named "region_param"

### ISSUE THREAD

**Issue by riverar** [Microsoft/MMdnn#137]
Windows 10 RS4 17133.1
Python 3.5.5/x64
Source: caffe 1.0.0 with GPU
Destination: IR
Model/prototxt: https://1drv.ms/u/s!AnjdAnZZcu-GpIdoZxg4md3Jj2lxmQ
Command: `mmtoir -f caffe -d dest -n yolo-obj.prototxt -w yolo-obj.caffemodel`

```
Traceback (most recent call last):
  File "c:\users\rafael\miniconda3\envs\d2c\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rafael\Miniconda3\envs\d2c\Scripts\mmtoir.exe\__main__.py", line 9, in <module>
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 163, in _main
    ret = _convert(args)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 9, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\mmdnn\conversion\caffe\transformer.py", line 309, in __init__
    text_format.Merge(f.read(), model)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "c:\users\rafael\miniconda3\envs\d2c\lib\site-packages\google\protobuf\text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 950:5 : Message type "caffe.LayerParameter" has no field named "region_param".
```

**Comment by kitstar** [comment]
Hi @riverar , 

Seems your model is built by a third-party modified Caffe binary, which can't load by original Caffe framework. If so, please provide your Caffe binary to load the model then run the conversion. If your model is converted from DarkNet, Caffe may not load or run the converted model.

We are developing the Darknet->IR parser and will release later. Will ping you if there is any progress.

Thanks.

**Comment by riverar** [comment]
@kitstar It's the fork of Caffe built for Windows https://github.com/BVLC/caffe/tree/windows. Not sure what you mean by "provide your Caffee binary" -- is there a MMdnn switch for this I missed?

Thanks for looking at this!

**Comment by kitstar** [comment]
I mean the model you provided is not *trained* by official Caffe. So the Caffe in your computer (mine either) can't load the model, of course. Then we need that third-party modified Caffe which is used for **training** this model, to load and run the model.

**Comment by kitstar** [comment]
Hi @riverar  we have implemented a initial darknet parser and tested the darenet->keras/cntk. Keras seems ok, but haven't checked the cntk correctness.

**Comment by riverar** [comment]
Nice, will try it out asap and let you know the results.
