### ISSUE TITLE
Using the extractor to extract Tensorflow models

### ISSUE THREAD

**Issue by mm-aditya** [Microsoft/MMdnn#148]
Platform (like ubuntu 16.04/win10): MacOS Sierra 10.12.6

Python version: 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): Tensorflow 1.5

Destination framework with version (like CNTK 2.3 with GPU): Caffe

Pre-trained model path (webpath or webdisk path): 

**Issue:**

Can't figure out how to use the extractor mentioned under the Tensorflow ReadMe before we can use the converter to convert the model to IR. Any help would be appreciated.

**Comment by kitstar** [comment]
```python
mmdownload -f tensorflow -n resnet_v2_152
mmtoir -f tensorflow -d resnet152 -n imagenet_resnet_v2_152.ckpt.meta -w imagenet_resnet_v2_152.ckpt --dstNodeName MMdnn_Output
```

**Comment by mm-aditya** [comment]
Running this leaves me with this error:

/anaconda/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Parse file [model.ckpt.meta] with binary format successfully.
Tensorflow model file [model.ckpt.meta] loaded successfully.
Tensorflow checkpoint file [model.ckpt] loaded successfully. [200] variables loaded.
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 168, in <module>
    _main()
  File "/anaconda/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 163, in _main
    ret = _convert(args)
  File "/anaconda/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 51, in _convert
    parser = TensorflowParser(args.network, args.weights, args.frozen_pb, args.dstNodeName)
  File "/anaconda/lib/python3.6/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 194, in __init__
    model = extract_sub_graph(model, dest_nodes.split(','))
  File "/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 145, in extract_sub_graph
    assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: MMdnn_Output is not in graph

**Comment by krishnavishalv** [comment]
@kitstar is there a way to add "MMdnn_Output" node by editing the existing graph structure.
