### ISSUE TITLE
KeyError: None when converting from Caffe to Tensorflow: maybe related to PReLU?

### ISSUE THREAD

**Issue by RobinDtx** [Microsoft/MMdnn#191]
Platform (like ubuntu 16.04/win10): Ubuntu 18.04

Python version: 3.6.5

Source framework with version (like Tensorflow 1.4.1 with GPU): Caffe 1.0.0 CPU

Destination framework with version (like CNTK 2.3 with GPU): TensorFlow 1.8.0 CPU

Pre-trained model path (webpath or webdisk path): https://github.com/danaitri/Face-detection-cnn . Any of the two .prototxt file and the .caffemodel

Running scripts: mmconvert -sf caffe -in F8_deploy.prototxt -iw G3XT_B.caffemodel -df tensorflow -om ./

Error:  
Traceback (most recent call last):
  File "/home/robin/Documents/virtualenvfolder/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/robin/Documents/virtualenvfolder/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 95, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/robin/Documents/virtualenvfolder/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 9, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)
  File "/home/robin/Documents/virtualenvfolder/lib/python3.6/site-packages/mmdnn/conversion/caffe/transformer.py", line 316, in __init__
    graph = GraphBuilder(def_path, self.input_shape, self.is_train_proto, phase).build()
  File "/home/robin/Documents/virtualenvfolder/lib/python3.6/site-packages/mmdnn/conversion/caffe/graph.py", line 447, in build
    graph.compute_output_shapes(self.model)
  File "/home/robin/Documents/virtualenvfolder/lib/python3.6/site-packages/mmdnn/conversion/caffe/graph.py", line 266, in compute_output_shapes
    node.output_shape = TensorShape(*NodeKind.compute_output_shape(node))
  File "/home/robin/Documents/virtualenvfolder/lib/python3.6/site-packages/mmdnn/conversion/caffe/graph.py", line 126, in compute_output_shape
    return LAYER_DESCRIPTORS[node.kind](node)
KeyError: None

I saw on related errors that this might be due to the presence of PReLU in the .prototxt. Is PReLU supported from Caffe to TensorFlow or not?

Thank you very much!

**Comment by JiahaoYao** [comment]
The `PReLU` is sooning add into MMdnn. I am creating a pull request, hoping to solve your problem.

-------

### The converted code of tensorflow 

```python
def KitModel(weight_file = None):
    global __weights_dict
    __weights_dict = load_weights(weight_file)

    data            = tf.placeholder(tf.float32, shape = (None, 160, 120, 3), name = 'data')
    conv1           = convolution(data, group=1, strides=[1, 1], padding='VALID', name='conv1')
    prelu1          = prelu(conv1, name='prelu1')
    conv2_pad       = tf.pad(prelu1, paddings = [[0L, 0L], [0L, 1L], [0L, 1L], [0L, 0L]])
    conv2           = convolution(conv2_pad, group=1, strides=[2, 2], padding='VALID', name='conv2')
    prelu2          = prelu(conv2, name='prelu2')
    conv3           = convolution(prelu2, group=1, strides=[1, 1], padding='VALID', name='conv3')
    prelu3          = prelu(conv3, name='prelu3')
    conv4n          = convolution(prelu3, group=1, strides=[1, 1], padding='VALID', name='conv4n')
    prelu4n         = prelu(conv4n, name='prelu4n')
    conv5n          = convolution(prelu4n, group=1, strides=[1, 1], padding='VALID', name='conv5n')
    prelu5n         = prelu(conv5n, name='prelu5n')
    conv6n          = convolution(prelu5n, group=1, strides=[1, 1], padding='VALID', name='conv6n')
    prelu6n         = prelu(conv6n, name='prelu6n')
    conv7           = convolution(prelu6n, group=1, strides=[1, 1], padding='VALID', name='conv7')
    prob            = tf.nn.softmax(conv7, name = 'prob')
    fpool_pad       = tf.pad(prob, paddings = [[0L, 0L], [1L, 1L], [1L, 1L], [0L, 0L]])
    fpool           = tf.nn.avg_pool(fpool_pad, [1, 3, 3, 1], [1, 1, 1, 1], padding='VALID', name='fpool')
    return data, fpool
```

**Comment by RobinDtx** [comment]
Thanks ! Will try it out once it has been merged!

**Comment by kitstar** [comment]
Hi @RobinDtx merged. Please check it. Thanks.

**Comment by bhadresh74** [comment]
@kitstar @JiahaoYao @RobinDtx 
This post is redundant of what is posted at https://github.com/Microsoft/MMdnn/issues/57
Adding this here since the ticket is still open.

I am having the same error which could maybe for different reason.

Here is the prototext file I am trying to convert.

https://github.com/hszhao/PSPNet/blob/master/evaluation/prototxt/pspnet101_cityscapes_713.prototxt

Here is the command I used to convert Caffemodel to IR

mmtoir -f caffe -n path-to-prototxt -w path-to-caffemodel -o caffe_resnet_IR

Here is my stack trace.

Traceback (most recent call last):
File "/data/bdhanani/Experiments_04/Notebooks/cf_to_tf/mmdnn/bin/mmconvert", line 11, in 
sys.exit(_main())
File "/data/bdhanani/Experiments_04/Notebooks/cf_to_tf/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 95, in _main
ret = convertToIR._convert(ir_args)
File "/data/bdhanani/Experiments_04/Notebooks/cf_to_tf/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 9, in _convert
transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)
File "/data/bdhanani/Experiments_04/Notebooks/cf_to_tf/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/caffe/transformer.py", line 318, in init
graph = GraphBuilder(def_path, self.input_shape, self.is_train_proto, phase).build()
File "/data/bdhanani/Experiments_04/Notebooks/cf_to_tf/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/caffe/graph.py", line 450, in build
graph.compute_output_shapes(self.model)
File "/data/bdhanani/Experiments_04/Notebooks/cf_to_tf/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/caffe/graph.py", line 269, in compute_output_shapes
node.output_shape = TensorShape(*NodeKind.compute_output_shape(node))
File "/data/bdhanani/Experiments_04/Notebooks/cf_to_tf/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/caffe/graph.py", line 129, in compute_output_shape
return LAYER_DESCRIPTORSnode.kind
KeyError: None

Regarding the error, my guess is on these two things

The prototxt file has a layer name called "BN" which is nothing but a "BatchNorm" layer. If I parse the file with the layer name "BatchNorm", I get this error:
check failed: param_size <= num_param_blobs (4 vs. 3) Too many params specified for layer conv1_1_3x3_s2/bn

To tackle this error, I changed the layer definition and reduced batch norm parameter from 4 to 3 which afterwards lead me to this error:

Check failed: target_blobs.size() == source_layer.blobs_size() (3 vs. 4) Incompatible number of blobs for layer conv1_1_3x3_s2/bn

Which makes sense, since my weights has 4 blobs for the batch norm layer: scale, offset, mean and variance.

The prototxt file has a layer name called "Interp" which is custom layer implemented in the Caffe.
I am not sure which of these things from above causing this issue.

I have a small suggestions.

Can the error be more informative than just "Keyerror":None ? Like, which layer is problematic or the root cause of the error.
Please let me know if anyone had the same issue or my approach is wrong.

Thanks,
Bee
