### ISSUE TITLE
Convert Resnet100 from MxNet to Caffe

### ISSUE THREAD

**Issue by 321zhangli123** [Microsoft/MMdnn#218]
Platform (like ubuntu 16.04/win10): ubuntu 16.04

Python version: 2.7

Source framework with version (like Tensorflow 1.4.1 with GPU):MxNet 1.2.0

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path): 

Running scripts:

I ran this command to convert my mxnet model to IR model:

python -m mmdnn.conversion._script.convertToIR -f mxnet -n /home/sll/zl/resnet-100-symbol.json -w /home/sll/zl/resnet-100-0197.params -d resnet100 --inputShape 3 112 112

This is the error trace I got.

[10:01:07] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.1.0. Attempting to upgrade...
[10:01:07] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Warning: MXNet Parser has not supported operator one_hot with name one_hot0.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sll/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 186, in <module>
    _main()
  File "/home/sll/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 181, in _main
    ret = _convert(args)
  File "/home/sll/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 99, in _convert
    parser.run(args.dstPath)
  File "/home/sll/.local/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/sll/.local/lib/python2.7/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 265, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "/home/sll/.local/lib/python2.7/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 377, in rename_UNKNOWN
    raise NotImplementedError()
NotImplementedError

**Comment by namizzz** [comment]
Hi @321zhangli123. One_hot is always used in the preprocess. MMdnn can only convert the architecture of a network, so the preprocess is skipped. Can you remove the preprocess part?

**Comment by xuguozhi** [comment]
I have met this problem, have you solved this?

**Comment by namizzz** [comment]
Hi @xuguozhi ,One_hot is always used in the preprocess. MMdnn can only convert the architecture of a network, so the preprocess is skipped. Can you remove the preprocess part?
