### ISSUE TITLE
Resnet152 Unknown layer: Scale

### ISSUE THREAD

**Issue by pandasMX** [Microsoft/MMdnn#230]
Hi, it seems that I cannot convert the resnet 152 keras model to IR. Error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 186, in <module>
    _main()
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 181, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 39, in _convert
    parser = Keras2Parser(model)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/keras/keras2_parser.py", line 101, in __init__
    model = self._load_model(model[0], model[1])
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/keras/keras2_parser.py", line 68, in _load_model
    'DepthwiseConv2D': _keras.applications.mobilenet.DepthwiseConv2D})
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 379, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2525, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2511, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Scale
```

Running script: python3 -m mmdnn.conversion._script.convertToIR -f keras -d resnet152 -n resnet152.json -w resnet152.h5

**Comment by kitstar** [comment]
Hi @pandasMX , Seems your keras model is trained by third-party modified Keras, with custom Scale layer (seems there is no scale layer in your offical keras).

**Comment by pandasMX** [comment]
Hi @kitstar , Can I know which official keras resnet152 model you refer to?

**Comment by kitstar** [comment]
Hi @pandasMX,

if you are using the model from [https://gist.github.com/flyyufelix/7e2eafb149f72f4d38dd661882c554a6](https://gist.github.com/flyyufelix/7e2eafb149f72f4d38dd661882c554a6), it is converted from caffe. You can just use mmdnn to convert caffe resnet152 model to IR.

**Comment by pandasMX** [comment]
@kitstar I'm using https://gist.github.com/mvoelk/ef4fc7fb905be7191cc2beb1421da37c which is modified version from https://gist.github.com/flyyufelix/7e2eafb149f72f4d38dd661882c554a6 to work with Keras 2.0. 
However, we can see that both of them have the Scale layer. The reason for having it was mentioned in https://flyyufelix.github.io/2017/03/23/caffe-to-keras.html 
"
Similarly, Keras and Caffe handle BatchNormalization very differently. For Keras, BatchNormalization is represented by a single layer (called “BatchNormalization”), which does what it is supposed to do by normalizing the inputs from the incoming batch and scaling the resulting normalized output with a gamma and beta constants. The layer stores 4 parameters, namely gamma, beta, the running mean and standard deviation for the input batch. However, interestingly for Caffe, it introduces 2 separate layers to handle the above operation. The first layer (called “BatchNorm Layer”) only performs the normalization step. The scaling step is left to be performed by a second layer (called “Scale Layer”). The “BatchNorm” layer only stores the running mean and SD of the input batch, while the “Scale” layer learns and stores the gamma and beta scaling constants.
"

I loaded the pre-trained weights provided here https://drive.google.com/file/d/0Byy2AcGyEVxfeXExMzNNOHpEODg/view and try to convert with mmdnn, but got that error. 

Now I have an idea that I can remove all the scale layers and trained the model from scratch instead of loading the pre-trained weights. Because the reason why there is scale layer is to convert the weights from caffe to keras. If I don't use the pre-trained weights, I can simply remove it and retrain the model, isn't it correct?

**Comment by kitstar** [comment]
@pandasMX   Yes it is. When you finished training a new model, we can work together to convert it!
