### ISSUE TITLE
failed to convert MXnet model to TF

### ISSUE THREAD

**Issue by IdeoG** [Microsoft/MMdnn#231]
### Platform (like ubuntu 16.04/win10):
Manjaro 17.1

### Python version:
Python 3.6.5

### Source framework with version (like Tensorflow 1.4.1 with GPU):
mxnet-latest with GPU

### Destination framework with version (like CNTK 2.3 with GPU):
tensorflow with GPU

### Pre-trained model path (webpath or webdisk path)
https://github.com/deepinsight/insightface
https://pan.baidu.com/s/1If28BkHde4fiuweJrbicVA

### Running scripts:
``` bash
python -m mmdnn.conversion._script.convertToIR -f mxnet -n model-symbol.json -w model-0000.params -d my_net --inputShape 3 112 112
```

### Output:
``` bash
$ python -m mmdnn.conversion._script.convertToIR -f mxnet -n model-symbol.json -w model-0000.params -d resnet50 --inputShape 3 112 112
[14:37:14] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.0.0. Attempting to upgrade...
[14:37:14] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
/usr/lib/python3.6/site-packages/mxnet/module/base_module.py:54: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	data
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 186, in <module>
    _main()
  File "/usr/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 181, in _main
    ret = _convert(args)
  File "/usr/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 99, in _convert
    parser.run(args.dstPath)
  File "/usr/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/lib/python3.6/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 262, in gen_IR
    func(current_node)
  File "/usr/lib/python3.6/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 398, in rename_FullyConnected
    weight = self.weight_data.get(source_node.name + "_weight").asnumpy().transpose((1, 0))
AttributeError: 'NoneType' object has no attribute 'asnumpy'

```

**Comment by namizzz** [comment]
Hi @IdeoG, I don't know which file you use to train this model,but I found in the [fmobilefacenet.py](https://github.com/deepinsight/insightface/blob/5a7937c76963da2723d0c601e967ce22e4db6c55/src/symbols/fmobilefacenet.py)
```python
_weight = mx.symbol.Variable("fc1_weight", shape=(num_classes, 512), lr_mult=1.0, wd_mult=wd_mult)
conv_6_f = mx.sym.FullyConnected(data=conv_6_dw, weight=_weight, num_hidden=num_classes, name='pre_fc1')
fc1 = mx.sym.BatchNorm(data=conv_6_f, fix_gamma=True, eps=2e-5, momentum=bn_mom, name='fc1')
```
So the weight name of fullyconnected layer is named manually as **'fc1_weight'** so you need to change the parser code to fix it 

```python
weight = self.weight_data.get("fc1_weight").asnumpy().transpose((1, 0))
```

and see if it works? Thanks.

**Comment by IdeoG** [comment]
Sorry for late answer. It worked!

**Comment by why702** [comment]
Hi @namizzz

I have a similar problem:

I used the model: https://www.dropbox.com/s/2xq8mcao6z14e3u/gamodel-r50.zip?dl=0

`python -m mmdnn.conversion._script.convertToIR -f mxnet -n model-symbol.json -w model-0000.params -d model-r50 --inputShape 3,112,112`

```
Traceback (most recent call last):
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 197, in <module>
    _main()
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 81, in _convert
    from mmdnn.conversion.mxnet.mxnet_parser import MXNetParser
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\mxnet\mxnet_parser.py", line 538
    self.set_weight(source_node.name, "bias", self.weight_data.get(source_node.name + "_beta").asnumpy())
       ^
SyntaxError: invalid syntax

D:\svnML\ditSRC\modules\AIOT\div_algo\model\face\insightface\gamodel-r50>python -m mmdnn.conversion._script.convertToIR -f mxnet -n model-symbol.json -w model-0000.params -d model-r50 --inputShape 3,112,112
[10:23:54] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.0. Attempting to upgrade...
[10:23:54] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
C:\Users\hsiaoyuh_wang\AppData\Roaming\Python\Python36\site-packages\mxnet\module\base_module.py:56: UserWarning: [91mYou created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
        data[0m
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Traceback (most recent call last):
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 197, in <module>
    _main()
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\common\DataStructure\parser.py", line 22, in run
    self.gen_IR()
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\mxnet\mxnet_parser.py", line 262, in gen_IR
    func(current_node)
  File "C:\Users\hsiaoyuh_wang\AppData\Local\Programs\Python\Python36\lib\site-packages\mmdnn\conversion\mxnet\mxnet_parser.py", line 538, in rename_BatchNorm
    self.set_weight(source_node.name, "bias", self.weight_data.get(source_node.name + "_beta").asnumpy())
AttributeError: 'NoneType' object has no attribute 'asnumpy'
```

I think this issue caused by the BatchNorm op "name": "gender_resnet0_batchnorm0_fwd" don't have the beta, so "self.weight_data.get(source_node.name + "_beta")" get None.

Do you have any suggestion?

**Comment by sumanth13131** [comment]
> Sorry for late answer. It worked!

hello can you please send me the process to convert to IR . I am also getting the same error while converting
 
thank u
