### ISSUE TITLE
tensorflow->caffe imagenet_vgg19 conversion error

### ISSUE THREAD

**Issue by shubh-agrawal** [Microsoft/MMdnn#243]
Platform: Ubuntu 16.04
Python version: 2.7
Source framework with version: Tensorflow 1.8.0 cpu
Destination framework with version: Caffe 1.0.0
Running scripts:

```
mmconvert -sf tensorflow -in imagenet_vgg19.ckpt.meta -iw imagenet_vgg19.ckpt -df caffe -om imagenet_caffe --inputShape 3 224 224 --dstNodeName vgg_19/fc8/Conv2D
```

Hi, I am trying to convert a tensorflow model to caffe just as a sample to test the conversion. I downloaded the imagenet_vgg19 using mmdownload command line and later used the above mentioned command for the conversion. However, I face this kind of error:

```
Parse file [imagenet_vgg19.ckpt.meta] with binary format successfully.
Tensorflow model file [imagenet_vgg19.ckpt.meta] loaded successfully.
2018-06-11 11:03:38.479816: W tensorflow/core/framework/allocator.cc:101] Allocation of 411041792 exceeds 10% of system memory.
Tensorflow checkpoint file [imagenet_vgg19.ckpt] loaded successfully. [38] variables loaded.
IR network structure is saved as [09520891ac414fc2a7722704916ebba1.json].
IR network structure is saved as [09520891ac414fc2a7722704916ebba1.pb].
IR weights are saved as [09520891ac414fc2a7722704916ebba1.npy].
Parse file [09520891ac414fc2a7722704916ebba1.pb] with binary format successfully.
Warning: Graph Construct a self-loop node vgg_19/dropout6/Identity. Ignored.
Warning: Graph Construct a self-loop node vgg_19/dropout7/Identity. Ignored.
Traceback (most recent call last):
  File "/home/itin065/.local/bin/mmconvert", line 11, in <module>
    load_entry_point('mmdnn==0.2.1', 'console_scripts', 'mmconvert')()
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 143, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 131, in gen_code
    func(current_node)
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 173, in emit_Conv
    if IR_parent_node.type == 'Pad':
AttributeError: 'NoneType' object has no attribute 'type'
```

Please let me know what is going wrong here. I suspect some elements missing out while conversion. Thanks in advance.

**Comment by kitstar** [comment]
Hi @shubh-agrawal,

not quite sure about the problem. I just update the mmdnn pip package (0.2.2) and tested it with

```bash
pip3 install -U mmdnn
mmdownload -f tensorflow -n vgg19

mmconvert -sf tensorflow -in imagenet_vgg19.ckpt.meta -iw imagenet_vgg19.ckpt -df caffe -om imagenet_caffe --dstNodeName MMdnn_Output
or
mmconvert -sf tensorflow -in imagenet_vgg19.ckpt.meta -iw imagenet_vgg19.ckpt -df caffe -om imagenet_caffe --dstNodeName vgg_19/fc8/Conv2D
```
both works.

BTW, vgg_19/fc8/BiasAdd is the true **Output Node**.

Thanks.

**Comment by shubh-agrawal** [comment]
Hey @kitstar ,
Thanks for the quick reply. I really appreciate your effort.
I have the latest mmdnn install. That is, pulled master.
```
pip install -U git+https://github.com/Microsoft/MMdnn.git@master
```
For the previous problem I faced, I assigned layername to dsnNameNode that comes before `vgg_19/dropout6/Identity`. I suspected from the error output that this layer maybe somehow causing problem. Now the conversion works, but only when dstNodeName is a layer before `vgg_19/dropout6/Identity`. 

Well this was a sample conversion which I intended as a warm-up for my own trained models. So when I am running the conversion for my model, I get quite a different error. Note that my trained model consists of Conv, Relu, Pool and FCN. No dropout. So I wasn't expecting an error like before.

Command I run for my model for getting IR first itself gives problem
```
mmtoir -f tensorflow --frozen_pb entropy.pb -d entropy --inputShape 122 160 1 --dstNodeName mmdnn_output
``` 

Error output:
```
Traceback (most recent call last):
  File "/home/itin065/.local/bin/mmtoir", line 11, in <module>
    load_entry_point('mmdnn==0.2.1', 'console_scripts', 'mmtoir')()
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 184, in _main
    ret = _convert(args)
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 48, in _convert
    parser = TensorflowParser2(args.frozen_pb, args.inputShape, args.inNodeName, args.dstNodeName)
  File "/home/itin065/.local/lib/python2.7/site-packages/mmdnn/conversion/tensorflow/tensorflow_frozenparser.py", line 108, in __init__
    placeholder_type_enum = dtypes.float32.as_datatype_enum)
  File "/home/itin065/.local/lib/python2.7/site-packages/tensorflow/python/tools/strip_unused_lib.py", line 83, in strip_unused
    raise KeyError("The following input nodes were not found: %s\n" % not_found)
KeyError: "The following input nodes were not found: set([u'input'])\n"
```
Same error when running the conversion end-to-end. Could you please give any information about this?

**Comment by kitstar** [comment]
@shubh-agrawal If you want to handle **frozen tensorflow model**, you need to specify the input node name of your model (which can be found in your model graph or your **freeze_graph** arguments). @namizzz Is that right?

**Comment by shubh-agrawal** [comment]
Nice. I added the correct inputNodeName and dstNodeName for IR conversion and it worked! The command line tool `mmtoir` requires correct arguments for these 2 node names. I think this point should mentioned in readme for tensorflow to IR conversion.
