### ISSUE TITLE
Input size has type str but expected one of int, long

### ISSUE THREAD

**Issue by Duke02** [Microsoft/MMdnn#247]
Platform (like ubuntu 16.04/win10):
ubuntu 18.04
Python version:
Python 3.6.4 :: Anaconda custom (64-bit)
Source framework with version (like Tensorflow 1.4.1 with GPU):
Caffe 1.0.0 without GPU
Destination framework with version (like CNTK 2.3 with GPU):
PyTorch 0.4.0 without GPU
Pre-trained model path (webpath or webdisk path):
[this link automatically downloads the file](http://mi.eng.cam.ac.uk/~agk34/resources/PoseNet.zip) 
[this one gives you the webpage I found the file on](http://mi.eng.cam.ac.uk/projects/relocalisation/)
You can download the files from the webpage if you scroll to "Code & DataSet"
Running scripts:
`mmtoir -f caffe -n .../train_kingscollege.prototxt --inputShape 224 -w .../weights_kingscollege.caffemodel -o output`

I get the final error as `TypeError: '224' has type str, but expected one of: int, long`
The error leads you to mmdnn/conversion/_script/convertToIR.py at the top.

The complete error message is:
```
Traceback (most recent call last):
  File "~/anaconda3/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "~/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 184, in _main
    ret = _convert(args)
  File "~/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 9, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)
  File "~/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/caffe/transformer.py", line 318, in __init__
    graph = GraphBuilder(def_path, self.input_shape, self.is_train_proto, phase).build()
  File "~/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/caffe/graph.py", line 320, in __init__
    self.load()
  File "~/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/caffe/graph.py", line 327, in load
    self.process_train_proto()
  File "~/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/caffe/graph.py", line 358, in process_train_proto
    self.model.input_dim.extend(self.input_shape)
TypeError: '224' has type str, but expected one of: int, long
```
(Note: there were some modifications to error message but only in terms of /home/.../anaconda3 and replaced with ~/anaconda3/...)

**Comment by Duke02** [comment]
Note: Adding the following
```
input: "data"
input_shape {
    dim: 64
    dim: 3
    dim: 224
    dim: 224
}
```
 to the train_kingscollege.prototxt file resulted in the error:
```
mmdnn.conversion.caffe.errors.ConversionError: the train_val.prototxt should be provided with the input shape
```
which requires me to use the command in the original post and gives the original error.

**Comment by JiahaoYao** [comment]
I created a pull request to fix the input shape problem. 
```bash
mmtoir -f caffe -n /Users/kit/Downloads/PoseNet/train_kingscollege.prototxt -w /Users/kit/Downloads/PoseNet/weights_kingscollege.caffemodel --inputShape 3 224 224 -o output
```
However, it gives the following error.
```bash
  File "/Users/kit/github/MMdnn/mmdnn/conversion/caffe/transformer.py", line 318, in __init__
    graph = GraphBuilder(def_path, self.input_shape, self.is_train_proto, phase).build()
  File "/Users/kit/github/MMdnn/mmdnn/conversion/caffe/graph.py", line 439, in build
    parent_node = graph.get_node(input_name)
  File "/Users/kit/github/MMdnn/mmdnn/conversion/caffe/graph.py", line 228, in get_node
    raise ConversionError('Layer not found: %s' % name)
mmdnn.conversion.caffe.errors.ConversionError: Layer not found: label_xyz
```
Then, I inspect the network. I find it might be some of the layers not well supported in MMdnn. 
![image](https://user-images.githubusercontent.com/20907377/41327817-83b5d816-6ef7-11e8-9738-608101c576d8.png)
