### ISSUE TITLE
Caffe->IR tmp prototxt used after deletion

### ISSUE THREAD

**Issue by Dzugaru** [Microsoft/MMdnn#259]
Platform: Ubuntu 16.04

Python version: 3.5

Source framework with version: Caffe 

Destination framework with version: mmtoir used

Pre-trained model path (webpath or webdisk path):
Prototxt: https://drive.google.com/open?id=18Soq6VgzqOpr7Z5mcKvbXgcmZ-pFy6Vi
Weights: https://drive.google.com/open?id=1cldYMuO5RhMsvgqSrLFPLQK9o58T5N5U

Running scripts: 
```
mmtoir -f caffe -w net_iter_1000.caffemodel -n caffe_squeeze.prototxt -o ./test_ --inputShape 3 128 128
```

```
Traceback (most recent call last):
  File "/home/dzugaru/.local/bin/mmtoir", line 11, in <module>
    load_entry_point('mmdnn==0.2.2', 'console_scripts', 'mmtoir')()
  File "/home/dzugaru/.local/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 187, in _main
    ret = _convert(args)
  File "/home/dzugaru/.local/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 13, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", inputshape, phase = args.caffePhase)
  File "/home/dzugaru/.local/lib/python3.5/site-packages/mmdnn/conversion/caffe/transformer.py", line 323, in __init__
    self.data_injector if self.data_injector else DataInjector(def_path, data_path), # Load and associate learned parameters
  File "/home/dzugaru/.local/lib/python3.5/site-packages/mmdnn/conversion/caffe/transformer.py", line 29, in __init__
    self.load_using_caffe()
  File "/home/dzugaru/.local/lib/python3.5/site-packages/mmdnn/conversion/caffe/transformer.py", line 35, in load_using_caffe
    net = caffe.Net(str(self.def_path), str(self.data_path), caffe.TEST)
RuntimeError: Could not open file /tmp/tmpwfilbxmq.prototxt
```

I know that using train prototxt is a bad idea (deploy prototxt works just fine) - but the code is suspicious, we replace prototxt path like this
```self.prototxt = tmp_prototxt```
then delete the file
```os.remove(tmp_prototxt)```
and use it in transformer.py afterwards.

Removing the deletion altogether works:
https://github.com/Dzugaru/MMdnn/commit/50e5440e70efc9167602d63f4751ff6af3b25d7d

**Comment by namizzz** [comment]
Hi @Dzugaru ,Thanks for your issue. We have fixed the bug you mentioned. Try the newest code!
