### ISSUE TITLE
Convert Pytorch Model to IR error

### ISSUE THREAD

**Issue by SmallMunich** [Microsoft/MMdnn#260]
Platform (like ubuntu 16.04):

Python version:2.7
I train the pytorch model named  _0620_100.pth. when I used the MMdnn command line : pytorch to IR.
mmtoir -f pytorch -d  CPM_FPN3_cmpadd6_dress  --inputShape 3 368 368 -n _0620_100.pth --dstNodeName MMdnn_Output  
the error is : ImportError: No module named models.CPM_FPN3_cpmadd6_dress

the models.CPM_FPN3_cpmadd6_dress is Network file .py! I think the error is the setting path but I do not know how to do it. 

Thank you!

**Comment by OIdiotLin** [comment]
the same problem I met...

I have trained a pytorch (v0.4.0) model and save it by `torch.save(model, path)` which filename is `2018-06-22.pth`

current directory is
```
./
└── 2018-06-22.pth
```

After running `mmtoir -f pytorch -d mobilenet --inputShape 3 224 224 -n ./2018-06-22.pth`, an error occurred.

```
Traceback (most recent call last):
  File "/home/oidiotlin/.local/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/oidiotlin/.local/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 184, in _main
    ret = _convert(args)
  File "/home/oidiotlin/.local/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 79, in _convert
    parser = PytorchParser(args.network, inputshape)
  File "/home/oidiotlin/.local/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 71, in __init__
    model = torch.load(model_file_name)
  File "/home/oidiotlin/.local/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/oidiotlin/.local/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'model'
```

**Comment by namizzz** [comment]
Hi @SmallMunich and  @OIdiotLin , I find this [issue](https://github.com/pytorch/pytorch/issues/2762). It's a problem load pytorch model file using "torch.load" because you define a custom class in your model. He said "I resolved it by adding the class definition code to the this script.". Maybe you can also try ? or just remove the class defination ? Thanks!

**Comment by huanyuan54** [comment]
@OIdiotLin this question is solve?

**Comment by OIdiotLin** [comment]
> @OIdiotLin this question is solve?

guess not. I ignored it.
