### ISSUE TITLE
Python crash when trying to convert tf frozen model ( maybe i missed some flags ? )

### ISSUE THREAD

**Issue by OrDavidi** [Microsoft/MMdnn#278]
On ubuntu 16.04
Python version: 3.5
Source framework with version (Tensorflow 1.6)
Destination framework with version (caffe)

Pre-trained model path (https://github.com/mozilla/DeepSpeech/releases/download/v0.1.1/deepspeech-0.1.1-models.tar.gz
)

Running scripts:

mmconvert -sf tensorflow --frozen_db DeepSpeech/models/output_graph.pb -df caffe -om result_mmdnn --dstNodeName output_node

I got : 

Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/usr/local/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 54, in _convert
    parser = TensorflowParser(args.network, args.weights, args.dstNodeName)
  File "/usr/local/lib/python3.5/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 223, in __init__
    model = extract_sub_graph(model, dest_nodes.split(','))
UnboundLocalError: local variable 'model' referenced before assignment

Thanks

**Comment by namizzz** [comment]
Hi @OrDavidi , It's  **--frozen_pb** ,not **frozen_db** . Tensorflow Parsers don't support RNN now. You can do it by yourself. Here is [Contribution Guideline](https://github.com/Microsoft/MMdnn/wiki/Contribution-Guideline).Thanks!
