### ISSUE TITLE
Mxnet to TF-Serving converted model only returns probability

### ISSUE THREAD

**Issue by gr8Adakron** [Microsoft/MMdnn#279]
I have converted my **MXnet model into tf-serving format, using these following commands of MMdnn**:

```

#..> Command 1:
mmtoir -f mxnet -n sleeve_length_mxnet_model/model152places-symbol.json -w sleeve_length_mxnet_model/model152places-0000.params -d sleeve_length_ir --inputShape 3 224 224
 
#..> Command 2:
mmtocode -f tensorflow --IRModelPath sleeve_length_ir.pb --IRWeightPath sleeve_length_ir.npy --dstModelPath sleeve_length_code.py
 
#..> Command 3:
python -m mmdnn.conversion.examples.tensorflow.imagenet_test -n sleeve_length_code.py -w sleeve_length_ir.npy --dump Mmdnn_serving --dump_tag SERVING



```

And conversion was successful. After I have used this client script to get the prediction out of the converted model.

```

from grpc.beta import implementations
import tensorflow as tf
import numpy as np
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2
from keras.preprocessing import image as keras_image
tf.app.flags.DEFINE_string('host', 'localhost', 'Service host')
tf.app.flags.DEFINE_string('port', '9000', 'Service port')
tf.app.flags.DEFINE_string('picture', '', 'path to picture')
FLAGS = tf.app.flags.FLAGS


def main(_):
    host = FLAGS.host
    port = FLAGS.port
    channel = implementations.insecure_channel(host, int(port))
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
    # Send request
    image =  keras_image.load_img(FLAGS.picture)
    image = keras_image.img_to_array(image).astype('float32')/255
    image = np.expand_dims(image, axis=0)
    request = predict_pb2.PredictRequest()
    request.model_spec.name = 'inception'
    request.model_spec.signature_name = tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY
    request.inputs['input'].CopyFrom(
        tf.contrib.util.make_tensor_proto(image, dtype='float32'))

    result = stub.Predict(request, 30)
    print(result)

if __name__ == '__main__':
    tf.app.run()

```

> **python model_client_medium.py --host=localhost --port=9000 --picture=temp/resized.jpg** 

**Output:**
![output](https://user-images.githubusercontent.com/16715364/42151414-8f649118-7dfa-11e8-82f2-94d7fc2315dc.png)

Successfully! I am getting the prediction out of it. But the problem is I am only getting the probabilities, can anyone please help me on **how to get the prediction classes along with the probability?**

**Comment by gr8Adakron** [comment]
@kant @martinwoodward @liangfu @gzuidhof Is there a problem with the conversion or I have to change my client-request script?

**Comment by namizzz** [comment]
Hi @gr8Adakron ,
There is a labels file in mmdnn/conversion/examples/data/imagenet_1000.txt .If you can get the predict probability of the labels you can get the prediction classes along with the probability. Thanks

**Comment by gr8Adakron** [comment]
@namizzz why don't do your job properly? I am not getting even the index of labels otherwise I would have figured it out. It's only and only returning probabilities that's what I meant to say.

**Comment by namizzz** [comment]
Hi @gr8Adakron ,I am confused why you don't know what the probabilities mean. It's your model actually. Before your conversion, the result of your mxnet model is not probabilities ? Maybe you need to figure out what the model work first. It may be more helpful.

**Comment by gr8Adakron** [comment]
No, with mxnet inference script it returns both predictions and probabilities but after conversion with MMdnn, it only returns me probabilities that's actually weird. that's the help am asking for, if you can tell me if anything wrong with my client script of calling the model.

**Comment by kitstar** [comment]
Hi @gr8Adakron, you can refer the pseudo-code below:

```python
result = stub.Predict(request, 30)
result = [val for val in result.value.float_val]
result = numpy.array(result)
result = result.argsort()[-5:][::-1]
with open(YOUR_LABLE_FILE, 'r') as f:
  labels = [l.rstrip() for l in f]

for i in result:
   print (labels[i - offset], i, predict[i])
```

**Comment by gr8Adakron** [comment]
pseudo-code not working, it returns an error.

```
Traceback (most recent call last):
  File "model_client_medium.py", line 47, in <module>
    tf.app.run()
  File "/home/afzal/.virtualenvs/tensorflow_py36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "model_client_medium.py", line 31, in main
    result = [val for val in result.value.float_val]
AttributeError: 'PredictResponse' object has no attribute 'value
```
This error is what I can see, but the I don't what do you mean by **YOUR_LABLE_FILE** because I don't have any labels file. Because:

**This is the structure of my original-MXnet model:**

```
mxnet_collar_model
├── collar_mxnet-0000.params
└── collar_mxnet-symbol.json

0 directories, 2 files
```
**And this is my structure of converted mxnet to the tensorflow-serving model directory:**
```
├── mxnet2tf-serving_client_script.py
├── saved_model.pb
└── variables
    ├── variables.data-00000-of-00001
    └── variables.index

1 directory, 4 files
```

All of them are binaries, I can't figure out which one is the labels file.

**While MXnet inference just take the two files shown above and returns both prediction and probabilities.**

**Comment by namizzz** [comment]
Hi @gr8Adakron ,try get 'outputs' first, maybe
```python 
result['outputs'].value.float_val
or
result.outputs.value.float_val
```
It's a mxnet [tutorial ](http://mxnet.incubator.apache.org/tutorials/python/predict_image.html). Try to figure out the label name.

**Comment by gr8Adakron** [comment]
Thank you! @namizzz 
This is my script which works fine and returns prediction labels along with probability, on converted model from MXnet to TF-serving using MMdnn.

Requires: python3.6
Returns: Top 5 predictions.

```

from grpc.beta import implementations
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2
from keras.preprocessing import image as keras_image

import re
import numpy as np
import tensorflow as tf
import numpy as np

tf.app.flags.DEFINE_string('host', 'localhost', 'Service host')
tf.app.flags.DEFINE_string('port', '9000', 'Service port')
tf.app.flags.DEFINE_string('picture', '', 'path to picture')
FLAGS = tf.app.flags.FLAGS

def predictResponse_into_nparray(response, output_tensor_name):
    dims = response.outputs[output_tensor_name].tensor_shape.dim
    shape = tuple(d.size for d in dims)
    return np.reshape(response.outputs[output_tensor_name].float_val, shape)


def main(_):
    host = FLAGS.host
    port = FLAGS.port
    channel = implementations.insecure_channel(host, int(port))
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)

    # Send request

    image =  keras_image.load_img(FLAGS.picture)
    image = keras_image.img_to_array(image).astype('float32')/255
    image = np.expand_dims(image, axis=0)
    request = predict_pb2.PredictRequest()
    request.model_spec.name = 'inception'
    request.model_spec.signature_name = tf.saved_model.signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY
    request.inputs['input'].CopyFrom(
        tf.contrib.util.make_tensor_proto(image, dtype='float32'))

    print("\n")
    result = stub.Predict(request, 30)
    with open("collar_label.txt", 'r') as f:
        labels = [l.rstrip() for l in f]

    output = predictResponse_into_nparray(result,'output')
    scores = output[0]
    rank   = np.array(output[0]).argsort()[-5:][::-1]
    
    for r in rank:
        label = labels[r]
        score = scores[r]
        print(f"\t{label} => {score}")
    print("\n")

if __name__ == '__main__':
    tf.app.run()
```
Thanks! I hope its helpful to others.

**Comment by kitstar** [comment]
Hi @gr8Adakron . Glad it helps! And thanks for this guiding!
