### ISSUE TITLE
mxnet to tensorflow problem: IR->TF failed, looks like the pooling caused?

### ISSUE THREAD

**Issue by xmuszq** [Microsoft/MMdnn#285]
Platform (like ubuntu 16.04/win10): ubuntu 16.04
Python version: 2.7
Source framework with version: mxnet (newest one)
Destination framework with version : TF

Mx->IR： success
IR->TF :  Failed

I check the codes step by step and found the pooling caused the problem:
_**mx.sym.pooling()**_
But if I replace above with 
_**mx.sym.pooling(global=True)**_ 
the MX model can be converted to TF successfully. 
In the link below, there are several files:
the original MXNET files: model-0001.paras, model-symbol.json
all the other files are generated file from MX->IR step 
and it failed during IR->TF step. 
Link: [link](https://drive.google.com/drive/folders/1J6W142bTFxQzaShV-EtBWOZoRWyBGfJ1?usp=sharing)
Any one knows who to solve this problem? Following are error message from IR->TF step:

```
Parse file [IR_output.pb] with binary format successfully.
('...IR_node....', <mmdnn.conversion.common.IR.IR_graph.IRGraphNode object at 0x7f669423c610>)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 122, in <module>
    _main()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 117, in _main
    ret = _convert(args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/tensorflow/tensorflow_emitter.py", line 81, in gen_code
    func(current_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/tensorflow/tensorflow_emitter.py", line 193, in emit_Pool
    padding = IR_node.get_attr('pads')[1:dim]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by namizzz** [comment]
Hi @xmuszq 
Thanks for your issue! We have fixed the bug ,try the newest code please!

**Comment by xmuszq** [comment]
I tried the newest verson, looks like new issue occur:

  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
infer_shape error. Arguments:
  data: (1, 3)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File
"/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py",
line 197, in <module>
    _main()
  File
"/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py",
line 192, in _main
    ret = _convert(args)
  File
"/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py",
line 115, in _convert
    parser.run(args.dstPath)
  File
"/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/parser.py",
line 22, in run
    self.gen_IR()
  File
"/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py",
line 262, in gen_IR
    func(current_node)
  File
"/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py",
line 424, in rename_Convolution
    self.set_output_shape(source_node, IR_node)
  File
"/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py",
line 281, in set_output_shape
    arg_shape, output_shape, aux_shape = sym.infer_shape(data =
self.data_shape)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py",
line 990, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py",
line 1120, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 149, in
check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator convolution0: [09:04:42]
src/operator/nn/convolution.cc:143: Check failed: dshp.ndim() == 4U (2 vs.
4) Input data should be 4D in batch-num_filter-y-x

**Comment by xmuszq** [comment]
I tried the newest verson, looks like new issue occur:
(Using previous code, I can convert residue model from mxnet to TF, but right now, this also failed with the same error)


```
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
infer_shape error. Arguments:
  data: (1, 3)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 197, in <module>
    _main()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 262, in gen_IR
    func(current_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 424, in rename_Convolution
    self.set_output_shape(source_node, IR_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 281, in set_output_shape
    arg_shape, output_shape, aux_shape = sym.infer_shape(data = self.data_shape)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py", line 990, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py", line 1120, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
**mxnet.base.MXNetError: Error in operator convolution0: [09:04:42] src/operator/nn/convolution.cc:143: Check failed: dshp.ndim() == 4U (2 vs. 4) Input data should be 4D in batch-num_filter-y-x**
```

**Comment by xmuszq** [comment]
@namizzz   
Can you again help me and take a look?

Thank you!

**Comment by xmuszq** [comment]
@kitstar 
Hi Kitstar,   Can you help me take a look at this issue?

Thank you so much!

**Comment by namizzz** [comment]
Hi @xmuszq , you need to use 
```cmd
--inputShape 3,112,112
not
--inputShape 3 112 112
```

**Comment by xmuszq** [comment]
@namizzz   
Thank you so much! It works for this model.
