### ISSUE TITLE
weights of tf.multiply operation seems not saved when convert tf model to caffe model

### ISSUE THREAD

**Issue by CuiXiaoDao** [Microsoft/MMdnn#303]
When converting my model from tensorflow to caffe, I encountered the following problem. It seems `rename_Mul()` didn't save one of the inputs as weights of mul operation. So when converting mul operation to caffe's scale layer, it didn't found the weights and then throw the error.
I think it could be solved by reuse some saving weights code from `rename_Conv2D()`. 

```
Parse file [tx.pb] with binary format successfully.
Traceback (most recent call last):
  File "./mmdnn/conversion/_script/IRToCode.py", line 122, in <module>
    _main()
  File "./mmdnn/conversion/_script/IRToCode.py", line 117, in _main
    ret = _convert(args)
  File "./mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/home/cuichao/MMdnn/mmdnn/conversion/caffe/caffe_emitter.py", line 143, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/home/cuichao/MMdnn/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/home/cuichao/MMdnn/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/home/cuichao/MMdnn/mmdnn/conversion/caffe/caffe_emitter.py", line 131, in gen_code
    func(current_node)
  File "/home/cuichao/MMdnn/mmdnn/conversion/caffe/caffe_emitter.py", line 532, in emit_Mul
    self.emit_Scale(IR_node)
  File "/home/cuichao/MMdnn/mmdnn/conversion/caffe/caffe_emitter.py", line 373, in emit_Scale
    self.weights_dict[IR_node.variable_name] = self.weights_dict.pop(IR_node.name)
KeyError: 'stage1/block0/merged/mul'
```

**Comment by namizzz** [comment]
Hi @CuiXiaoDao ,Merged, Thanks!
