### ISSUE TITLE
ISSUE when convert mxnet to tensorflow during MX->IR

### ISSUE THREAD

**Issue by xmuszq** [Microsoft/MMdnn#307]
Platform (like ubuntu 16.04/win10):
--16.04
Python version:
--2.7
Source framework with version :
--mxnet newest version with GPU
Destination framework with version:
-- Tensorflow 1.4.1 with GPU
Pre-trained model path (webpath or webdisk path):
--[LINK](https://drive.google.com/drive/folders/1e9a6EN3edCXmR2eO9ZTxSfWTkhc8e9cE?usp=sharing)
Running scripts:

ISSUE: I'm going to transfer MXNET model to Tensorflow. I'm using the newest MMDNN codes (pip install -U git+https://github.com/Microsoft/MMdnn.git@master). The error occurs in MX to IR stage. 

The error is: 
`transform the mxnet model to IR model using mmdnn....................
/home/zhen/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py:54: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	data
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 197, in <module>
    _main()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 262, in gen_IR
    func(current_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 515, in rename_BatchNorm
    IR_node.attr["axis"].i = MXNetParser._convert_axis(IR_node, int(source_node.get_attr("axis", "1")))
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_graph.py", line 43, in get_attr
    assert self.attr
AssertionError
`
I also tried the normal verstion of MMDNN, it also failed.

**Comment by namizzz** [comment]
Hi @xmuszq ,Thanks for your issue, we have fixed it. You can try the newest version.

**Comment by xmuszq** [comment]
@namizzz 

I checked out the newest codes and tried. In my machine there still is an error:

`transform the mxnet model to IR model using mmdnn....................
/home/zhen/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py:54: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	data
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 197, in <module>
    _main()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 262, in gen_IR
    func(current_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 565, in rename_Pooling
    kernel_shape = MXNetParser.str2intList(source_node.get_attr("kernel"))
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 55, in str2intList
    v = v.replace("(", "")
AttributeError: 'NoneType' object has no attribute 'replace'
`

Maybe something wrong in my side. The scrip I used:

`### transform the mxnet model to IR model using mmdnn
# The output file will be put in the same folder with name
#   'IR_output.pb, IR_output.json, IR_output.npy'
echo "transform the mxnet model to IR model using mmdnn...................."
path_paras=$path_folder'model-0000.params'
path_json=$path_folder'model-symbol.json'
name_IR_output='IR_output'
# cd that folder in order to save the IR files in that folder
cd $path_folder
python -m mmdnn.conversion._script.convertToIR -f mxnet -n $path_json -w $path_paras -d $name_IR_output --inputShape 3,112,112

### transfer the IR models into tf models file with name 'tf_model.py' in local folder
echo "transfer the IR models into tf models file...................."
python -m mmdnn.conversion._script.IRToCode -f tensorflow --IRModelPath IR_output.pb --IRWeightPath IR_output.npy --dstModelPath tf_model.py`


Thank you again for your great help!

**Comment by xmuszq** [comment]
@namizzz 
Can you help me take a look? I can't find where is the bug.
