### ISSUE TITLE
Darknet conversion to IR of custom model error on Win10

### ISSUE THREAD

**Issue by michhar** [Microsoft/MMdnn#326]
Platform (like ubuntu 16.04/win10):  Win10

Python version:  3.6

Source framework with version (like Tensorflow 1.4.1 with GPU):  Darknet with CUDA on Nvidia GPU

Destination framework with version (like CNTK 2.3 with GPU):  IR, but CoreML eventually

Pre-trained model path (webpath or webdisk path):  [darknet tiny YOLO v3 custom model download](https://drive.google.com/open?id=1Se7qq01P5ICbqd2Oce_yh6oqlQYFe5dg) and [yolo v3 tiny cfg file](https://drive.google.com/open?id=108o0S4ZrltIorJH3iP2jb3Z0E_uAFRZK)

Running scripts:  command is:  `mmtoir -f darknet -n experiment\yolov3-tiny.cfg -w backup\yolov3-tiny_lr0.000001_ep5000_mb16_loss2.54_.weights -o experiment\out`

Error:
```
(py36) C:\Users\michhar.REDMOND\Documents\bin\github\darknet\build\darknet\x64>mmtoir -f darknet -n experiment\yolov3-tiny.cfg -w backup\yolov3-tiny_lr0.000001_ep5000_mb16_loss2.54_.weights -o experiment\out
weights buf size: 8678554
Warning: Graph Construct a self-loop node data. Ignored.
Traceback (most recent call last):
  File "c:\anaconda3\envs\py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\py36\Scripts\mmtoir.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 184, in _main
    ret = _convert(args)
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 102, in _convert
    parser.run(args.dstPath)
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\common\DataStructure\parser.py", line 22, in run
    self.gen_IR()
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\darknet\darknet_parser.py", line 67, in gen_IR
    func(current_node)
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\darknet\darknet_parser.py", line 171, in rename_Conv
    W = np.reshape(self.buf[self.start:self.start+kernel.size], kernel.shape)
  File "c:\anaconda3\envs\py36\lib\site-packages\numpy\core\fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "c:\anaconda3\envs\py36\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 5375 into shape (21,256,1,1)
```

Seems that it's unhappy with this line:  https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/darknet/darknet_parser.py#L171

BTW, it works with the base model (`yolov3.weights`) and standard config (as in your tutorial Readme) so might be my custom YOLO v3 tiny custom model (2 classes).

Any ideas greatly appreciated!!  I really like this project and thank you in advance for your help.

**Comment by namizzz** [comment]
Hi @michhar ,thanks for your issue. We have fixed the bug. You can try the newest code!
