### ISSUE TITLE
Mxnet->Tf

### ISSUE THREAD

**Issue by xiangdeyizhang** [Microsoft/MMdnn#335]
Hi kitstar,

I have met the same question:
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator _minus_scalar with name _minusscalar0.
Warning: MXNet Parser has not supported operator _mul_scalar with name _mulscalar0.
Traceback (most recent call last):
  File "/home/bearzhang/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/bearzhang/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/bearzhang/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 159, in <module>
    _main()
  File "/home/bearzhang/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 154, in _main
    ret = _convert(args)
  File "/home/bearzhang/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 95, in _convert
    parser.gen_IR()
  File "/home/bearzhang/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 266, in gen_IR
    func(current_node)
  File "/home/bearzhang/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 487, in rename_Convolution
    in_channel = self.IR_layer_map[IR_node.input[0]].attr["_output_shapes"].list.shape[0].dim[-1].size
KeyError: u'_mulscalar0'

can you help me?

**Comment by namizzz** [comment]
Hi @xiangdeyizhang , could you provide the model files?
