### ISSUE TITLE
I follow coreml readme to convert mobilenet throw error

### ISSUE THREAD

**Issue by iChiaGuo** [Microsoft/MMdnn#336]
Platform (like ubuntu 16.04/win10):ubuntu 16.04

Python version:3.5

Source framework with version (like Tensorflow 1.4.1 with GPU):Tensorflow 1.9

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):
https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/coreml/README.md
Running scripts:
1.mmdownload -f coreml -n mobilenet
2.mmtoir -f coreml -d mobilenet -n MobileNet.mlmodel --dstNodeName MMdnn_Output
I follow [coreml readme](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/coreml/README.md) to convert mobilenet throw error:

TypeError: Expected model to be a .mlmodel file or a Model_pb2 object

mmtoir -f coreml -d mobilenet -n MobileNet.mlmodel --dstNodeName MMdnn_Output
/home/ljg/anaconda2/envs/py35/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
WARNING:root:Keras version 2.1.4 detected. Last version known to be fully compatible of Keras is 2.1.3 .
WARNING:root:TensorFlow version 1.8.0 detected. Last version known to be fully compatible is 1.5.0 .
Traceback (most recent call last):
  File "/home/ljg/anaconda2/envs/py35/bin/mmtoir", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmtoir')()
  File "/home/ljg/anaconda2/envs/py35/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/ljg/anaconda2/envs/py35/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 110, in _convert
    parser = CoremlParser(args.network)
  File "/home/ljg/anaconda2/envs/py35/lib/python3.5/site-packages/mmdnn/conversion/coreml/coreml_parser.py", line 54, in __init__
    model = _MLModel(model.encode())
  File "/home/ljg/anaconda2/envs/py35/lib/python3.5/site-packages/coremltools/models/model.py", line 155, in __init__
    raise TypeError("Expected model to be a .mlmodel file or a Model_pb2 object")
TypeError: Expected model to be a .mlmodel file or a Model_pb2 object

**Comment by iChiaGuo** [comment]
@JiahaoYao  Can you help me solve this ?
