### ISSUE TITLE
Convert Caffe model to IR error

### ISSUE THREAD

**Issue by dongxiao92** [Microsoft/MMdnn#338]
Platform (like ubuntu 16.04/win10):
ubuntu16.04
Python version:
Python 2.7.12
Source framework with version (like Tensorflow 1.4.1 with GPU):
Caffe-1.0 release
Destination framework with version (like CNTK 2.3 with GPU):
IR
Pre-trained model path (webpath or webdisk path):
no model weights
Running scripts:
python -m mmdnn.conversion._script.convertToIR -f caffe -d ./ -n ./models/caffe/ResNet-50_1.prototxt --inputShape 1 3 1400 800

I try to convert a ResNet like model with different input size to IR. But I got errors as follows:

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nvidia/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 197, in <module>
    _main()
  File "/home/nvidia/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/nvidia/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 17, in _convert
    graph = transformer.transform_graph()
  File "/home/nvidia/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/transformer.py", line 360, in transform_graph
    mapped_node = self.map_node(node)
  File "/home/nvidia/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/transformer.py", line 381, in map_node
    mapped_node = map_func(node)
  File "/home/nvidia/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/mapper.py", line 230, in map_batch_norm
    kwargs = {'scale' : len(node.data) >= 3, 'bias' : len(node.data) == 4}
TypeError: object of type 'NoneType' has no len()

I try to print the node in mapper.py and find it's the first batch norm layer. The layer definition is as follows:

layer {
        bottom: "conv1"
        top: "conv1"
        name: "bn_conv1"
        type: "BatchNorm"
        batch_norm_param {
                use_global_stats: true 
        }    
}

**Comment by namizzz** [comment]
Hi @dongxiao92 ,you don't provide the weight file, it's a must. Thanks!

**Comment by dongxiao92** [comment]
@namizzz Thanks!. But in my understanding, the IR is kind of representation of the topology of the networks, so the weight file is not necessary. I think my understanding about the role of the IR in MMDNN is wrong

**Comment by namizzz** [comment]
Hi @dongxiao92 ,your understanding is right! but now caffe parser only support to convert the archietecture and weight file at the same time. Thanks!
