### ISSUE TITLE
convert to IR report error when convert resnet50 

### ISSUE THREAD

**Issue by frank-wei** [Microsoft/MMdnn#345]
Platform (like ubuntu 16.04/win10): ubuntu 16.04

Python version: 3.5.2

Source framework with version (like Tensorflow 1.4.1 with GPU): tensorflow nightly

Destination framework with version (like CNTK 2.3 with GPU): no

Pre-trained model path (webpath or webdisk path):

Running scripts:
mmtoir -f tensorflow -iw log_resnet50/checkpoint-500 -in log_resnet50/checkpoint-500.meta  --dstNodeName "GPU_0/tower_0/fully_connected0/add" -d .

The error is below；
Parse file [/home/weiwei//log_resnet50/checkpoint-500.meta] with binary format successfully.
Tensorflow model file [/home/weiwei/log_resnet50/checkpoint-500.meta] loaded successfully.
Tensorflow checkpoint file [/home/weiwei/log_resnet50/checkpoint-500] loaded successfully. [432] variables loaded.
Traceback (most recent call last):
  File "/home/weiwei/py_night_720/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/weiwei/py_night_720/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/weiwei/py_night_720/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/home/weiwei/py_night_720/lib/python3.5/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/weiwei/py_night_720/lib/python3.5/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 309, in gen_IR
    func(current_node)
  File "/home/weiwei/py_night_720/lib/python3.5/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 661, in rename_FusedBatchNorm
    self.set_weight(source_node.name, 'mean', self.ckpt_data[mean.name])
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by namizzz** [comment]
Hi @frank-wei ,We manually save the parameters of Batch Normalization operators. But its topology varies from different version of tensorflow. So MMdnn only support the **TensorFlow1.8**. Thanks! Or you can edit the code in rename_FusedBatchNorm part to fix this problem.

**Comment by frank-wei** [comment]
@namizzz  maybe we can add more paths to support different BN version. I will try to fix it later and provide a PR later.

**Comment by namizzz** [comment]
Hi @frank-wei Thanks!
