### ISSUE TITLE
(keras2IR) TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by YusukeO** [Microsoft/MMdnn#357]
Platform : ubuntu 16.04

Python version : 3.6

Source framework with version : keras 2.20 with GPU

Destination framework with version : pytorch with GPU

Pre-trained model path (webpath or webdisk path):

Running scripts: mmtoir -f keras -d vgg16_bangs_pcb -n vgg16_3bangs.json -w vgg16_3bangs.h5
I got following error message:
Using TensorFlow backend.
.
.
.
Network file [vgg16_3bangs.json] and [vgg16_3bangs.h5] is loaded successfully.
Traceback (most recent call last):
  File "/home/suzukilab/.pyenv/versions/anaconda3-5.2.0/envs/anaconda3/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/suzukilab/.pyenv/versions/anaconda3-5.2.0/envs/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/suzukilab/.pyenv/versions/anaconda3-5.2.0/envs/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/home/suzukilab/.pyenv/versions/anaconda3-5.2.0/envs/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/suzukilab/.pyenv/versions/anaconda3-5.2.0/envs/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 142, in gen_IR
    func(current_node)
  File "/home/suzukilab/.pyenv/versions/anaconda3-5.2.0/envs/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 419, in rename_Conv2D
    self._convert_convolution(source_node, 2)
  File "/home/suzukilab/.pyenv/versions/anaconda3-5.2.0/envs/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 273, in _convert_convolution
    Keras2Parser._convert_padding(source_node, IR_node)
  File "/home/suzukilab/.pyenv/versions/anaconda3-5.2.0/envs/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 204, in _convert_padding
    list(source_node.layer.strides))
  File "/home/suzukilab/.pyenv/versions/anaconda3-5.2.0/envs/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/utils.py", line 114, in compute_tf_same_padding
    output_shape = (input_shape[idx] + strides[idx] - 1) // strides[idx]
**TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'**

I want to convert my own keras model to IR (and then IR to pytorch) with its architecture and weights.
I make my keras model based on pre-trained vgg16 and add some layers including regression layer, and then I fine-tuned it.
I save the trained model with 
model_json_str = model.to_json()
open('vgg16_3bangs.json', 'w').write(model_json_str)
model.save_weights('vgg16_3bangs.h5')

How can I solve the error message?

BTW, I cannot figure out the meaning of second argument 'vgg16_bangs_pcb'. So I arbitrary wrote it. What is the meaning of it?

**Comment by namizzz** [comment]
Hi @YusukeO , '-d' is for the IR path. Could you please provide your model file ?

**Comment by YusukeO** [comment]
Sure!
[https://drive.google.com/file/d/1eZnXeUe0haQSmxXkaIpuhZW4VjDaUt-7/view?usp=sharing
https://drive.google.com/file/d/1qHyasspL7Mtm4wjPfzM9Fjv5M2w8H2Dq/view?usp=sharing](url)

**Comment by namizzz** [comment]
Hi @YusukeO ,I find that "batch_input_shape": [null, null, null, 3] , so while computing the padding of the conv2d layer ,there is no input shape. You  can just change it to 
```code
"batch_input_shape": [null, 224, 224, 3],
```
You will get the IR files.

**Comment by YusukeO** [comment]
Thank you for checking details of my file.
I'll try it!
