### ISSUE TITLE
mxnet add_n doesn't support

### ISSUE THREAD

**Issue by lygstate** [Microsoft/MMdnn#363]
```
[10:35:27] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v0.9.5. Attempting to upgrade...
[10:35:27] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
e:\ci-cor-ready\ai\face-io\face-detection\mx2tensorflow-js\tensorflow_env\lib\site-packages\mxnet\module\base_module.py:54: UserWarning: [91mYou created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
        data[0m
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator add_n with name stage1_unit1_plus.
Traceback (most recent call last):
  File "c:\users\lygstate\appdata\local\programs\python\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lygstate\appdata\local\programs\python\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\CI-Cor-Ready\ai\face-io\face-detection\mx2tensorflow-js\tensorflow_env\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
  File "e:\ci-cor-ready\ai\face-io\face-detection\mx2tensorflow-js\tensorflow_env\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "e:\ci-cor-ready\ai\face-io\face-detection\mx2tensorflow-js\tensorflow_env\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "e:\ci-cor-ready\ai\face-io\face-detection\mx2tensorflow-js\tensorflow_env\lib\site-packages\mmdnn\conversion\common\DataStructure\parser.py", line 22, in run
    self.gen_IR()
  File "e:\ci-cor-ready\ai\face-io\face-detection\mx2tensorflow-js\tensorflow_env\lib\site-packages\mmdnn\conversion\mxnet\mxnet_parser.py", line 265, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "e:\ci-cor-ready\ai\face-io\face-detection\mx2tensorflow-js\tensorflow_env\lib\site-packages\mmdnn\conversion\mxnet\mxnet_parser.py", line 376, in rename_UNKNOWN
    raise NotImplementedError()
NotImplementedError
```

**Comment by lygstate** [comment]
The document of add_n is 
http://mxnet.apache.org/api/python/symbol/symbol.html#mxnet.symbol.add_n
