### ISSUE TITLE
[TF to Pytorch] ResNet padding seems incorrect

### ISSUE THREAD

**Issue by Eyyub** [Microsoft/MMdnn#379]
Hi,

Now that #362 seems to be fixed (at the time I write this, @namizzz PR is still pending so I pulled the newest version from his fork), I tried to load and run inference using the resulting converted model, I took inspiration from @namizzz's code in this [issue.](https://github.com/Microsoft/MMdnn/issues/378#issuecomment-416161818)
```python
import imp
import torch
import numpy as np
from torch.autograd import Variable

MainModel = imp.load_source('MainModel', 'resnet50v1.py')
model =  torch.load('resnet50v1.pth')
print model(Variable(torch.ones(1, 224, 224, 3)))
``` 
I got this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eyyub/mmdnn/venv/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "resnet50v1.py", line 190, in forward
    resnet_model_add_3 = resnet_model_batch_normalization_14_FusedBatchNorm + resnet_model_batch_normalization_11_FusedBatchNorm
RuntimeError: The size of tensor a (216) must match the size of tensor b (218) at non-singleton dimension 2

```
It's located at an addition between the output of a ResNet block and the shortcut connection. I think the issue may come from the way the inputs are padded, what do you think?

Thanks,

**Comment by namizzz** [comment]
Hi @Eyyub , I search your model ,and I find it's NCHW ,but MMdnn only support the NHWC format now (will support NHWC later). There are two ways to get the pytorch model if you want:
1. edit the pytorch_emitter to fix all the problem about pad, conv, pool ... and then dump the model.
2. convert a NHWC model

**Comment by ZiangYan** [comment]
Thanks! 
After I generate a NHWC tf model, everything works perfectly!!
