### ISSUE TITLE
Pytorch to IR Error (.pth ImportError)

### ISSUE THREAD

**Issue by wwqLearning** [Microsoft/MMdnn#383]
Platform (ubuntu 16.04):

Python version: python2.7

Source framework with version (Pytorch 0.4.0 with CPU):

Destination framework with version (caffe  with CPU):

Pre-trained model path (disk path):

Running scripts: mmtoir -f pytorch -d enet --inputShape 6,384,384 -n model_net_G.pth

Error: ImportError: No module named Mode.enet_mode

**Comment by namizzz** [comment]
Hi @wwqLearning , there is a class names Mode defined by you. Please refer to [this](https://github.com/Microsoft/MMdnn/issues/241)

**Comment by wwqLearning** [comment]
@namizzz  Thanks. I have solved the ImportError, but have another error in maxpool2d with indice.

**Comment by wwqLearning** [comment]
@namizzz  The error is "graph = torch._C._jit_pass_onnx(graph, aten)
RuntimeError: symbolic for max_pool2d returned None for the output1(indicating conversion for the particular output is not supported), but the network uses this output later. "

**Comment by namizzz** [comment]
Hi @wwqLearning , we want something like https://github.com/Microsoft/MMdnn/issues/388#issue-355401815 , and could you provide your model files?

**Comment by wwqLearning** [comment]
@namizzz  Is this the whole error stack? 
" /root/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py:1749: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/root/Map0823/Net/pytorch2caffe_converter.py", line 34, in <module>
    pytorchparser = PytorchParser(netG, shape)
  File "/root/tools/PytorchToCaffe-master/MMdnn/mmdnn/conversion/pytorch/pytorch_parser.py", line 83, in __init__
    self.pytorch_graph.build(self.input_shape)
  File "/root/tools/PytorchToCaffe-master/MMdnn/mmdnn/conversion/pytorch/pytorch_graph.py", line 124, in build
    trace.set_graph(PytorchGraph._optimize_graph(trace.graph(), False))
  File "/root/tools/PytorchToCaffe-master/MMdnn/mmdnn/conversion/pytorch/pytorch_graph.py", line 74, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, aten)
RuntimeError: symbolic for max_pool2d returned None for the output 1 (indicating conversion for that particular output is not supported), but the network uses this output later."
And I can not give the model files for some reasons.

**Comment by wwqLearning** [comment]
@namizzz  The model is something like the model in https://github.com/davidtvs/PyTorch-ENet

**Comment by namizzz** [comment]
Hi @wwqLearning ,It's a problem about onnx "MaxPool2d with index output is not supported in ONNX ".
refers to https://discuss.pytorch.org/t/problems-converting-pytorch-model-into-onnx/12192
https://github.com/onnx/onnx/blob/master/docs/Operators.md#maxpool
https://github.com/onnx/onnx/issues/417
https://github.com/onnx/onnx/issues/1217
