### ISSUE TITLE
Tensorflow inception to Caffe

### ISSUE THREAD

**Issue by juniel03** [Microsoft/MMdnn#384]
Platform (like ubuntu 16.04/win10): win 10

Python version: python 3.6.2

Source framework with version (like Tensorflow 1.4.1 with GPU): Tensorflow 1.10 with GPU

Destination framework with version (like CNTK 2.3 with GPU): Caffe

Pre-trained model path (webpath or webdisk path): 

Running scripts: mmconvert -sf tensorflow -iw tf_files/inceptionrounded_graph.pb --inNodeName input --inputShape 299,299,3 --dstNodeName final_output -df caffe -om gender

I am getting an error NameError: name 'tf' is not defined

Please Help Thank you very much

**Comment by juniel03** [comment]
Resolved the Issue by downgrading to tensorflow 1.8 but then i get this error:
    assert False
AssertionError

**Comment by juniel03** [comment]
here it is
Tensorflow has not supported operator [PlaceholderWithDefault] with name [input/BottleneckInputPlaceholder].
Traceback (most recent call last):
  File "c:\users\blue solutions\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\blue solutions\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\BLUE SOLUTIONS\AppData\Local\Programs\Python\Python36\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
  File "c:\users\blue solutions\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "c:\users\blue solutions\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "c:\users\blue solutions\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\common\DataStructure\parser.py", line 22, in run
    self.gen_IR()
  File "c:\users\blue solutions\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_frozenparser.py", line 349, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "c:\users\blue solutions\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_frozenparser.py", line 410, in rename_UNKNOWN
    assert False
AssertionError

**Comment by namizzz** [comment]
Hi @juniel03 ,as you can see from the error log, tensorflow_frozenparser has not supported operator [PlaceholderWithDefault] ,could you please send your model file for us to implement?

**Comment by om777** [comment]
The same issue is for Floor
