### ISSUE TITLE
tensorflow to caffe AssertionError

### ISSUE THREAD

**Issue by xiaoqiang233** [Microsoft/MMdnn#390]
Platform (like ubuntu 16.04/win10): ubuntu16.04

Python version: 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): 1.8

Destination framework with version (like CNTK 2.3 with GPU): caffe

Pre-trained model path (webpath or webdisk path):

Running scripts:

when I convert tensorflow to caffe use comman like this:  mmconvert -sf tensorflow -in ckpt-99500.meta -iw ckpt-99500 --dstNodeName GPU_0/Add -df caffe -om dstmodel

an AssertionError occured.  this is the log:
Parse file [ckpt-99500.meta] with binary format successfully.
Tensorflow model file [ckpt-99500.meta] loaded successfully.
Tensorflow checkpoint file [ckpt-99500] loaded successfully. [130] variables loaded.
Tensorflow has not supported operator [OneShotIterator] with name [OneShotIterator].
Tensorflow has not supported operator [IteratorGetNext] with name [IteratorGetNext].
Tensorflow has not supported operator [GreaterEqual] with name [random_crop/GreaterEqual].
Tensorflow has not supported operator [All] with name [random_crop/All].
Tensorflow has not supported operator [Assert] with name [random_crop/Assert/Assert].
Tensorflow has not supported operator [FloorMod] with name [random_crop/mod].
Tensorflow has not supported operator [Slice] with name [random_crop].
Tensorflow has not supported operator [Cast] with name [Cast].
Tensorflow has not supported operator [Fill] with name [zeros].
Tensorflow has not supported operator [Greater] with name [Greater].
Tensorflow has not supported operator [Select] with name [Select].
<mmdnn.conversion.tensorflow.tensorflow_graph.TensorflowGraphNode object at 0x7f604ee8ac18>
name: "truediv"
op: "RealDiv"
input: "Select"
input: "truediv/y"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 256
        }
        dim {
          size: 256
        }
        dim {
          size: 4
        }
      }
    }
  }
}

Traceback (most recent call last):
  File "/home/gpu/anaconda3/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 309, in gen_IR
    func(current_node)
  File "/home/gpu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 532, in rename_RealDiv
    assert False
AssertionError

Do you know the reason?  Thanks a lot!

**Comment by namizzz** [comment]
Hi @xiaoqiang233 , these are all operations about input preprocessing. MMdnn only support to convert 
 the architecture of a network. You need to skip them using `--inNodeName xxxxx`

**Comment by xiaoqiang233** [comment]
Thanks! Problem solved!

**Comment by ZhichenZhao** [comment]
hi, @xiaoqiang233 , I meet the same issue, what should be --inNodeName xxxx in your example? I tried name: "truediv" and other names but all get errors:
 
Traceback (most recent call last):
  File "/data00/home/zhaozhichen.water/apython/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/data00/home/zhaozhichen.water/apython/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/data00/home/zhaozhichen.water/apython/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 65, in _convert
    if args.inNodeName and inputshape[0]:
TypeError: 'NoneType' object is not subscriptable

Thanks for any help!

**Comment by ZhichenZhao** [comment]
@xiaoqiang233 by the way, if I add inputShape then I get the same error like you. From log file, It seems nothing is skipped.
