### ISSUE TITLE
Unable to convert resnet18 tensorflow on tiny-imagenet to MMdnn IR

### ISSUE THREAD

**Issue by ZiangYan** [Microsoft/MMdnn#398]
Platform (like ubuntu 16.04/win10): Ubuntu 16.04

Python version: 2.7.12

Source framework with version (like Tensorflow 1.4.1 with GPU): Tensorflow 1.9.0 with GPU

Destination framework with version (like CNTK 2.3 with GPU): MMdnn IR

Pre-trained model path (webpath or webdisk path): https://drive.google.com/file/d/1kQzbpEE1F8e2IU2YG-ejVpxgYtGjN2qw/view?usp=sharing

Running scripts:
```
mmtoir -f tensorflow -n resnet18_for_mmdnn.ckpt.meta -w resnet18_for_mmdnn.ckpt --dstNodeName final_dense -o converted
```

My final goal is to convert a tf model to pytorch model. Following instruction [here](https://github.com/Microsoft/MMdnn/blob/master/docs/tf2pytorch.md), I decide to convert the tf model to MMdnn IR first. 

I save my tf model in tf.train.Saver V1 data format, which is the same as imagenet resnet 152 model in the above instruction.

I'm experimenting with tiny-imagenet, thus the shape of input image is (batch_size, 64, 64, 3), and the shape of label is (batch_size, 200).

My output is 
```
Parse file [/xxx/resnet18_for_mmdnn.ckpt.meta] with binary format successfully.
Tensorflow model file [/xxx/resnet18_for_mmdnn.ckpt.meta] loaded successfully.
Tensorflow checkpoint file [/xxx/resnet18_for_mmdnn.ckpt] loaded successfully. [91] variables loaded.
Traceback (most recent call last):
  File "/usr/local/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 310, in gen_IR
    func(current_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 413, in rename_Conv2D
    self._get_bias(source_node, IR_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 352, in _get_bias
    assert variable.layer.attr['shape'].shape.dim[0].size == IR_node.attr['kernel_shape'].list.i[-1]
IndexError: list index out of range
```

**Comment by namizzz** [comment]
Hi @ZiangYan , Thanks for your issue, we have fix it! But there is a layers for pre-processing (sub in 3 axis)  we don't implement it because MMdnn focus on the network architecture part . You need to add it in the converted pytorch model code file. Thanks!

**Comment by ZiangYan** [comment]
Cool! You save my day!!

Thanks a lot.

**Comment by ZiangYan** [comment]
Cool! You save my day!!

Thanks a lot.
