### ISSUE TITLE
Pytorch to IR: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight'

### ISSUE THREAD

**Issue by cudawarped** [microsoft/MMdnn#402]
Platform (like ubuntu 16.04/win10): Win 8.1

Python version: 3.5

Source framework with version (like Tensorflow 1.4.1 with GPU): pytorch 0.4.0

Destination framework with version (like CNTK 2.3 with GPU): caffe

Pre-trained model path (webpath or webdisk path): https://mega.nz/#!yR5HGTAK!hHh3gYgShR-knRq-RYEktE5SbljFhHwLTI_U289hIpA

Running scripts: mmtoir -f pytorch -d resnet32 -n resnet32_pytorch --inputShape 3,224,224
I get the following error
Traceback (most recent call last):
  File "d:\c_progs\anaconda3\envs\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\c_progs\anaconda3\envs\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\c_progs\Anaconda3\envs\python35\Scripts\mmtoir.exe\__main__.py", line 9, in <module>
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 92, in _convert
    parser = PytorchParser(args.network, inputshape[0])
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\mmdnn\conversion\pytorch\pytorch_parser.py", line 83, in __init__
    self.pytorch_graph.build(self.input_shape)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\mmdnn\conversion\pytorch\pytorch_graph.py", line 122, in build
    trace, output = torch.jit.get_trace_graph(self.model, (dummy_input, ))
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\torch\jit\__init__.py", line 255, in get_trace_graph
    return LegacyTracedModule(f, nderivs=nderivs)(*args, **kwargs)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\torch\jit\__init__.py", line 288, in forward
    out = self.inner(*trace_inputs)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\torch\nn\modules\module.py", line 479, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\torch\nn\modules\module.py", line 479, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "d:\c_progs\anaconda3\envs\python35\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #2 'weight'

I have successfully exported the vgg19 pytorch model (from https://github.com/Microsoft/MMdnn/blob/master/mmdnn/models/README.md) to IR Structure using the below command
mmtoir -f pytorch -d vgg19 -n imagenet_vgg19.pth --inputShape 3,224,224
so the error is caused by the model I am trying to import.  Because I am not that familiar with pytorch I can't figure out how to solve this problem?

**Comment by namizzz** [comment]
Hi @cudawarped , change this [line ](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/pytorch_parser.py#L74) to `torch.load(file, map_location='cpu')` may work. I can't install fastai in my machine so I can't try to use your model to test. But it seems a problem of loading a model on CPU device trained in GPU.

**Comment by cudawarped** [comment]
Hi @namizzz  thank you for your help, that seems to have done the trick, however I am now getting the following error
KeyError: 'onnx::LogSoftmax'
because their is no conversion between onnx::LogSoftmax and the IR structure.  This seems identical to this [issue](https://github.com/Microsoft/MMdnn/issues/283).   Is there a reason why the conversion of LogSoftmax has not been implemented?

**Comment by namizzz** [comment]
Hi @cudawarped ,because we don't have a PyTorch model including softmax layer provided by users that we can use to implement and test it. We can't load your model and that issue didn't provide the model. Sorry... We will ping you if we have any further progress.

**Comment by cudawarped** [comment]
Hi @namizzz, that makes perfect sense especially as it should be easy enough to manually add that layer to the converted model for all frameworks.  With your help I have successfully converted the pytorch model to caffe, and the results for my validation set are almost identical, thanks again.
