### ISSUE TITLE
Cannot convert TF FCN to Caffe

### ISSUE THREAD

**Issue by monckxqq** [Microsoft/MMdnn#403]
Platform : Centos 7

Python version : 2.7

Source framework with version :Tensorflow 1.8.0

Destination framework with version : Caffe 1.0

I followed shekkizh/FCN.tensorflow(https://github.com/shekkizh/FCN.tensorflow) and trained a Tensorflow FCN model.

After extracted my model,  I tried to convert the model to caffe but it failed.

Running command:
mmconvert -sf tensorflow -in imagenet_fcn.ckpt.meta -iw imagenet_fcn.ckpt --dstNodeName MMdnn_Output -df caffe -om tf_fcn 

Got error:
```Warning: Graph Construct a self-loop node sub/y. Ignored
Warning: Graph Construct a self-loop node inference/dropout_1/random_uniform. Ignored
Warning: Graph Construct a self-loop node inference/BiasAdd_19. Ignored
Warning: Graph Construct a self-loop node inference/BiasAdd_20. Ignored
Warning: Graph Construct a self-loop node inference/BiasAdd_21. Ignored
Traceback (most recent call last):
    File "/home/mine/env/bin/mmconvert", line 11, in module
        sys.exit(_main())
    File "/home/mine/env/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
        ret = IRToCode._convert(code_args)
    File "/home/mine/env/lib/python2.7/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
        emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
    File "/home/mine/env/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 144, in run
        super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
    File "/home/mine/env/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
        self.save_code(dstNetworkPath, phase)
    File "/home/mine/env/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
        code = self.gen_code(phase)
    File "/home/mine/env/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 132, in gen_code
        func(current_node)
    File "/home/mine/env/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 323, in emit_DataInput
        shape = [shape[0], shape[-1] + shape[1:-1]
IndexError: list index out of range

Is TF FCN to Caffe supportted?

**Comment by namizzz** [comment]
Hi @monckxqq ,could you provide your model files for us to debug?

**Comment by wang-kangkang** [comment]
you should specify tf.placeholder()'s parameter shape, don't let it use defaule shape.
for example:
tf.placeholder(dtype=tf.float32,name='input_img'),    which is wrong
tf.placeholder(dtype=tf.float32,shape=[1,64,64,3],name='input_img'),    which is right
