### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'real_variable_name'

### ISSUE THREAD

**Issue by IvyGongoogle** [Microsoft/MMdnn#416]
hello, I get a issue. here I have PNet-30.meta, in which `conv4_1` has a output `cls_prob`, but when I run `mmconvert -sf tensorflow -in PNet-30.meta -iw PNet-30 --dstNodeName  cls_prob -df caffe -om tf_PNet`, it shows error:

```
Parse file [PNet-30.meta] with binary format successfully.
Tensorflow model file [PNet-30.meta] loaded successfully.
Tensorflow checkpoint file [PNet-30] loaded successfully. [25] variables loaded.
Tensorflow has not supported operator [Slice] with name [conv4_1/Slice].
Tensorflow has not supported operator [Softmax] with name [conv4_1/Softmax].
IR network structure is saved as [6a75099bfbbf4fd9b0209b9210bf0838.json].
IR network structure is saved as [6a75099bfbbf4fd9b0209b9210bf0838.pb].
IR weights are saved as [6a75099bfbbf4fd9b0209b9210bf0838.npy].
Parse file [6a75099bfbbf4fd9b0209b9210bf0838.pb] with binary format successfully.
Warning: Graph Construct a self-loop node conv4_1/Rank. Ignored.
Warning: Graph Construct a self-loop node conv4_1/Sub/y. Ignored.
Warning: Graph Construct a self-loop node conv4_1/concat/values_0. Ignored.
Warning: Graph Construct a self-loop node conv4_1/Slice. Ignored.
Warning: Graph Construct a self-loop node conv4_1/Softmax. Ignored.
Traceback (most recent call last):
  File "/xxx/local/anaconda2/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/xxx/local/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/xxx/local/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/xxx/local/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 144, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/xxx/local/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/xxx/local/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/xxx/local/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 132, in gen_code
    func(current_node)
  File "/xxx/local/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 558, in emit_Reshape
    self.parent_variable_name(IR_node),
  File "/xxx/local/anaconda2/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 41, in parent_variable_name
    return self.IR_graph.get_parent(IR_node.name, path).real_variable_name
AttributeError: 'NoneType' object has no attribute 'real_variable_name'
```

how to fix it?
can anyone give some advises?
thank you very much~

**Comment by namizzz** [comment]
Hi @IvyGongoogle , could you please provide your model file for us to debug?

**Comment by IvyGongoogle** [comment]
@namizzz  thanks for your reply. you can get my `PNet-30.meta` under [here](https://github.com/IvyGongoogle/mtcnn-models/tree/master/PNet). and you also can get the model parameters in it. 
looking forward your reply.

**Comment by IvyGongoogle** [comment]
need help~~

**Comment by namizzz** [comment]
Hi @IvyGongoogle , thanks for your issue, we have fixed the problems!

**Comment by Archernarkiu** [comment]
@IvyGongoogle I used your model and your command
> mmconvert -sf tensorflow -in PNet-30.meta -iw PNet-30 --dstNodeName cls_prob -df caffe -om tf_PNet
,then the same error occurred.Have you solved this problem yet?

**Comment by joaoantoniocn** [comment]
I'm getting the same error when I'm trying to convert tensorflow to pytorch. Anyone has fixed it yet?
