### ISSUE TITLE
How to add new type of layers in converting caffe model?

### ISSUE THREAD

**Issue by Alexuan** [Microsoft/MMdnn#443]
I am sorry to raise this issue because I am new to caffe and mmdnn.
 
I encountered the error below when attempted to convert caffe model to IR and my environment was the docker `mmdnn/mmdnn:cpu.small`
Here is the error info:
```
Traceback (most recent call last):
  File "/usr/local/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 184, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 9, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/caffe/transformer.py", line 311, in __init__
    text_format.Merge(f.read(), model)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 536, in Merge
    descriptor_pool=descriptor_pool)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 590, in MergeLines
    return parser.MergeLines(lines, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 623, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 638, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 763, in _MergeField
    merger(tokenizer, message, field)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 837, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py", line 730, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 883:3 : Message type "caffe.LayerParameter" has no field named "norm_param".
```
After checking my prototxt file and other files in `mmdnn/conversion/caffe/`, I suppose my error emerges because the NormalizeLayer is defined non-officially and it is not supported in the python caffe.
Here is part of the prototxt file. If it is not necessary, I can provide the full context.
```
layer {
  name: "conv4_3_norm"
  type: "Normalize"
  bottom: "conv4_3"
  top: "conv4_3_norm"
  norm_param {
    across_spatial: false
    scale_filler {
      type: "constant"
      value: 20
    }
    channel_shared: false
  }
}
```
How can I add new type of layer in converting caffe model? 
Or is there any solution to this issue?
Thank you~

**Comment by namizzz** [comment]
Hi @Alexuan , MMdnn doesn't support the third party caffe now. Please change it to the official caffe or implement it by yourself. Here is the https://github.com/Microsoft/MMdnn/wiki/Contribution-Guideline. Thanks!

**Comment by Alexuan** [comment]
Thanks for your kind reply @namizzz ~
