### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Banhalmi** [Microsoft/MMdnn#451]
Platform (like ubuntu 16.04/win10):
win 8.1
Python version:
3.6, Anaconda 3
Pre-trained model path (webpath or webdisk path):
https://api.medicalphoto.org/model_onychomycosis.php#offline
After downloading, allmodelswithexamples.zip\onychomycosis\A1 folder.
Running scripts:
mmtoir -f caffe -n resnet-deploy.prototxt -w res_nail2-naillowlr_resnet_152_iter_24907.caffemodel -o caffe_resnet_IR

The output was:

Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\runpy.py", line 193, in _run_module_as_ma
in
    "__main__", mod_spec)
  File "c:\program files\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Anaconda3\Scripts\mmtoir.exe\__main__.py", line 9, in <
module>
  File "c:\program files\anaconda3\lib\site-packages\mmdnn\conversion\_script\co
nvertToIR.py", line 192, in _main
    ret = _convert(args)
  File "c:\program files\anaconda3\lib\site-packages\mmdnn\conversion\_script\co
nvertToIR.py", line 16, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", inp
utshape[0], phase = args.caffePhase)
TypeError: 'NoneType' object is not subscriptable

**Comment by crmauceri** [comment]
I experience the same error running the example conversion for resnet152. 

I run

```
mmdownload -f caffe -n resnet152 -o ./
mmconvert -sf caffe -in resnet152-deploy.prototxt -iw resnet152.caffemodel -df cntk -om caffe_resnet152.dnn
```

And get the error 

```
Traceback (most recent call last):
  File "/Users/Mauceri/anaconda/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/Users/Mauceri/anaconda/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/Users/Mauceri/anaconda/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 16, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", inputshape[0], phase = args.caffePhase)
TypeError: 'NoneType' object is not subscriptable
```

I'm running macOS 10.13, python 3.6 (anaconda). I do not have caffe installed. Is it a dependency for converting caffe models?

**Comment by crmauceri** [comment]
Found the solution in issue #421 
- caffe is a dependancy
- need to use the -inputShape flag
