### ISSUE TITLE
Error (Caffe->IR)

### ISSUE THREAD

**Issue by aWeinzierl** [Microsoft/MMdnn#46]
When I try to get the intermediate representation of a caffemodel, I get the following error:

    class args( object ):
        srcFramework = 'caffe' 
        dstPath = destinationFilePrefix
        network = structureFile
        weights = weightFile
        inputShape = [3, 227, 227]
        caffePhase = 'TRAIN'
    convertToIR._convert( args() )

```
 ------------------------------------------------------------
    WARNING: PyCaffe not found!
    Falling back to a pure protocol buffer implementation.
    * Conversions will be drastically slower.
    * This backend is UNTESTED!
------------------------------------------------------------

Traceback (most recent call last):
File "convertToIR.py", line 9, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)

File "transformer.py", line 316, in __init__
    graph = GraphBuilder(def_path, self.input_shape, self.is_train_proto, phase).build()

File "graph.py", line 446, in build
    graph.compute_output_shapes(self.model)

File "graph.py", line 270, in compute_output_shapes
    node.output_shape = TensorShape(*NodeKind.compute_output_shape(node))

File "graph.py", line 125, in compute_output_shape
    return LAYER_DESCRIPTORS[node.kind](node)

File "shape.py", line 97, in shape_pool
    return get_strided_kernel_output_shape(node, math.ceil)

File "shape.py", line 24, in get_strided_kernel_output_shape
    dilation = 1 if len(node.parameters.dilation) == 0 else node.parameters.dilation[0]
AttributeError: 'PoolingParameter' object has no attribute 'dilation'
```

Happens with https://github.com/DeepScale/SqueezeNet/tree/master/SqueezeNet_v1.1
as well as with https://github.com/songhan/SqueezeNet-DSD-Training

**Comment by kitstar** [comment]
Should be fixed. Please try the newest code. Thanks.

**Comment by aWeinzierl** [comment]
works perfectly, thank you so much for this fast fix
