### ISSUE TITLE
Tensorflow to Mxnet:ValueError: Need to provide the output node of Tensorflow model.

### ISSUE THREAD

**Issue by wiwatarm** [Microsoft/MMdnn#462]
Platform (like ubuntu 16.04/win10): ubuntu 16.04

Python version: 3.6.6

Source framework with version (like Tensorflow 1.4.1 with GPU):Tensorflow 1.8.0 with GPU

Destination framework with version (like CNTK 2.3 with GPU): Mxnet (anyversion) with GPU

Pre-trained model path (webpath or webdisk path): https://github.com/mdietrichstein/tensorflow-open_nsfw

Running scripts: mmconvert --srcFramework tensorflow --IRModelPath open_nsfw.pb --dstModelPath ../../classify_nsfw.py -df mxnet --IRWeightPath ../../data/open_nsfw-weights.npy -om mxnet_nxfw_v3-0000.params

basically, i have save the graph from tensorflow-nsfw, there've existed these following file

checkpoint           
open_nsfw.ckpt.data-00000-of-00001  
open_nsfw.ckpt.meta  
optimized_open_nsfw.pb
frozen_open_nsfw.pb  
open_nsfw.ckpt.index                
open_nsfw.pb

error found 

Traceback (most recent call last):
  File "/home/datawow/miniconda2/envs/deep_learning3/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/datawow/miniconda2/envs/deep_learning3/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/datawow/miniconda2/envs/deep_learning3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 51, in _convert
    raise ValueError("Need to provide the output node of Tensorflow model.")
ValueError: Need to provide the output node of Tensorflow model.

**Comment by rainLiuplus** [comment]
Hi @wiwatarm , please read this https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/README.md#usage .
