### ISSUE TITLE
in emit_Concat     axis = axis_array.index(IR_node.get_attr('axis')) ValueError: tuple.index(x): x not in tuple

### ISSUE THREAD

**Issue by IvyGongoogle** [Microsoft/MMdnn#469]
hello, when I run `mmconvert -sf tensorflow -iw /xxx/my_mobilenet2.pb --inNodeName input_images --inputShape 1000,1000,3 --dstNodeName model_0/feature_fusion/scores/Sigmoid -df caffe -om tf_resnet`, I get error:
`
R network structure is saved as [57e120c6abd14cdf9a6c80d0671c8b4e.json].
IR network structure is saved as [57e120c6abd14cdf9a6c80d0671c8b4e.pb].
IR weights are saved as [57e120c6abd14cdf9a6c80d0671c8b4e.npy].
Parse file [57e120c6abd14cdf9a6c80d0671c8b4e.pb] with binary format successfully.
Warning: Graph Construct a self-loop node model_0/sub_1/y. Ignored.
Warning: Graph Construct a self-loop node model_0/sub_2/y. Ignored.
Warning: Graph Construct a self-loop node model_0/sub/y. Ignored.
CaffeEmitter has not supported operator [Split].
model_0/split
Traceback (most recent call last):
  File "/xxx/.virtualenvs/mmdnn/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/xxx/.virtualenvs/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/xxx/.virtualenvs/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/xxx/.virtualenvs/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 144, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/xxx/.virtualenvs/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/xxx/.virtualenvs/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/xxx/.virtualenvs/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 132, in gen_code
    func(current_node)
  File "/xxx/.virtualenvs/mmdnn/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 460, in emit_Concat
    axis = axis_array.index(IR_node.get_attr('axis'))
ValueError: tuple.index(x): x not in tuple
`
my tf is 1.8 and mmdnn is 0.2.3, 
so how to fix it? 
thank you very much~

my `my_mobilenet2.pb` is [here](https://github.com/IvyGongoogle/mobilenet).

**Comment by payal211** [comment]
I have the same error. Anyone can please help.

Thanks in advance.


Traceback (most recent call last):
  File "/usr/local/bin/mmtocode", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 117, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 144, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, args.phase) 
File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/usr/local/lib/mmdnn/lib/python3.5/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 55, in save_code
    code = self.gen_code(phase)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 132, in gen_code
    func(current_node)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 516, in emit_Concat
    axis = axis_array.index(IR_node.get_attr('axis'))
ValueError: tuple.index(x): x not in tuple

**Comment by payal211** [comment]
@IvyGongoogle have you solve it? 
What was the issue for this?

Thank you very much.
