### ISSUE TITLE
How to Converting pre-trained pytorch model to MXNet?

### ISSUE THREAD

**Issue by Ken1256** [Microsoft/MMdnn#479]
Platform (like ubuntu 16.04/win10):win10

Python version:3.6.6 x64

Source framework with version (like Tensorflow 1.4.1 with GPU):torch-0.4.1-cp36-cp36m-win_amd64 (CUDA 9.2)

Destination framework with version (like CNTK 2.3 with GPU):mxnet-cu92 --pre(1.3.1b20180927)

Pre-trained model path (webpath or webdisk path):
http://xinyizhang.tech/files/GFN_epoch_55.pkl.zip
https://github.com/jacquelinelala/GFN

Running scripts:
mmconvert -sf "pytorch" -in Z:\sp2\GFN\GFN-master\models\GFN_epoch_55.pkl --inputShape 3,256,256 -df "mxnet" -om "F:\test.params"

error:
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "c:\program files\python36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 92, in _convert
    parser = PytorchParser(model, inputshape[0])
  File "c:\program files\python36\lib\site-packages\mmdnn\conversion\pytorch\pytorch_parser.py", line 76, in __init__
    model = torch.load(model_file_name, map_location='cpu')
  File "c:\program files\python36\lib\site-packages\torch\serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "c:\program files\python36\lib\site-packages\torch\serialization.py", line 542, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'networks'

**Comment by Ken1256** [comment]
I don't know how to get inputShape value, just guess...

**Comment by kirkzZ** [comment]
Hi,did you solve it? xxx.pth convert xxx.params
