### ISSUE TITLE
mmconvert from TensorFlow to Cntk fails if TensorFlow version is 1.10.0 or higher 

### ISSUE THREAD

**Issue by Alfalover** [Microsoft/MMdnn#486]
Platform Windows 10, Python 3.6 mmdnn 0.2.3 tensorflow 1.10.0 

C:\Users\antjdav\Documents\Visual Studio 2017\MLExpectedPower\PythonTensorFlow>mmconvert --srcFramework tensorflow -iw plant_243_tf/saved_model.pb --inNodeName "vector_input:0" --inputShape 14 --dstNodeName "output_layer:0" -df cntk -om outTest
Traceback (most recent call last):
 File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\runpy.py", line 193, in _run_module_as_main
   "__main__", mod_spec)
 File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "C:\Users\antjdav\AppData\Roaming\Python\Python36\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
 File "C:\Users\antjdav\AppData\Roaming\Python\Python36\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
   ret = convertToIR._convert(ir_args)
 File "C:\Users\antjdav\AppData\Roaming\Python\Python36\site-packages\mmdnn\conversion\_script\convertToIR.py", line 61, in _convert
   parser = TensorflowParser2(args.weights, inputshape, args.inNodeName, args.dstNodeName)
 File "C:\Users\antjdav\AppData\Roaming\Python\Python36\site-packages\mmdnn\conversion\tensorflow\tensorflow_frozenparser.py", line 91, in __init__
   'MMdnn requires tensorflow>=1.8.0' % tf.__version__)
NameError: name 'tf' is not defined

looking at tensorflow_frozenparser.py 

Line 96 : 
if tensorflow.__version__ < '1.8.0':
           raise ImportError(
               'Your TensorFlow version %s is outdated. '
               'MMdnn requires tensorflow>=1.8.0' % tf.__version__)

Version is wrongly compared using string comparison and 1.10.0 version is lower than 1.8.0
also the message format references tf variable that do not exists.

**Comment by peteryang1** [comment]
try the latest code
