### ISSUE TITLE
Failed to convert tf1.4 model to caffe mode，TypeError

### ISSUE THREAD

**Issue by Jackiq** [Microsoft/MMdnn#491]
Platform (like ubuntu 16.04/win10):
Ubuntu14.04
Python version:
2.7
Source framework with version (like Tensorflow 1.4.1 with GPU):
TensorFlow1.4 gpu
Destination framework with version (like CNTK 2.3 with GPU):
caffe gpu
Pre-trained model path (webpath or webdisk path):
https://github.com/Jackiq/TF-1.4-MODEL
Running scripts:
$ mmconvert -sf tensorflow -in model.ckpt.meta -iw model.ckpt  -df caffe -om tf_to_caffe.proto --dump_tag SERVING

Running detail：
$ mmconvert -sf tensorflow -in model.ckpt.meta -iw model.ckpt  -df caffe -om tf_to_caffe.proto --dump_tag SERVING
Parse file [model.ckpt.meta] with binary format successfully.
Tensorflow model file [model.ckpt.meta] loaded successfully.
Tensorflow checkpoint file [model.ckpt] loaded successfully. [301] variables loaded.
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmconvert')()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 66, in _convert
    parser = TensorflowParser(args.network, args.weights, args.dstNodeName)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 248, in __init__
    dest_nodes, transforms)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/tools/graph_transforms/__init__.py", line 46, in TransformGraph
    outputs_string = compat.as_bytes(",".join(outputs))
TypeError

**Comment by Super-Tree** [comment]
I met the same error，it is strange and seems like that there are errors in tensorflow for the parser of tf graph
