### ISSUE TITLE
mxnet mobilefacenet to IR error

### ISSUE THREAD

**Issue by ronyuzhang** [Microsoft/MMdnn#493]
Platform (mac):

Python version:
    python3
Running scripts:
python -m mmdnn.conversion._script.convertToIR -f mxnet -n model-symbol.json -w model-0104.params -d anti_spoof --inputShape 3 112 112

error log：
[21:03:01] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.0. Attempting to upgrade...
[21:03:01] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator L2Normalization with name l2normalization0.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 197, in <module>
    _main()
  File "/usr/local/lib/python3.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/usr/local/lib/python3.7/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/local/lib/python3.7/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 265, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "/usr/local/lib/python3.7/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 376, in rename_UNKNOWN
    raise NotImplementedError()
NotImplementedError

**Comment by ronyuzhang** [comment]
@namizzz

**Comment by namizzz** [comment]
Hi, @ronyuzhang , MMdnn focus on the network architecture part , so it doesn't support the operators like L2Normalization. Thanks!

**Comment by namizzz** [comment]
Hi @ronyuzhang , MMdnn focus on the network architecture part, so we don't implement the L2Normalization operator. Thanks!
