### ISSUE TITLE
Errors in `Generate PyTorch model from code snippet file and weight file`

### ISSUE THREAD

**Issue by tengerye** [Microsoft/MMdnn#499]
Platform: ubuntu 16.04

Python version: 3.6.5 :: Anaconda

Source framework with version: mxnet

Destination framework with version: PyTorch-CPU 0.4.1

Pre-trained model path (webpath or webdisk path): https://pan.baidu.com/s/1mj6X7MK

Running scripts:
1. `mmtoir -f mxnet -n model-r50-am-lfw/model-sym
bol.json -w model-r50-am-lfw/model-0000.params -d faceVer --inputShape 3,112,112`;
2. `mmtomodel -f pytorch -n faceVer.py -w pytorch_faceVer.npy --dump pytorch_faceVer.pth`

------
After reading the source code, I realized that there is a bug in the tutorial of [PyTorch conversion](https://github.com/Microsoft/MMdnn/tree/master/mmdnn/conversion/pytorch#generate-pytorch-model-from-code-snippet-file-and-weight-file). Therefore, I alerted my code to:
`mmtomodel -f pytorch -in faceVer.py -iw pytor
ch_faceVer.npy -o pytorch_faceVer.pth`

The traceback of the error is:

> Traceback (most recent call last):
>   File "/home/ubuntu/anaconda3/bin/mmtomodel", line 11, in <module>
>     sys.exit(_main())
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/dump_code.py", line 79, in _main
>     ret = dump_code(args.framework, args.inputNetwork, args.inputWeight, args.outputModel, args.dump_tag)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
>     save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
>   File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/pytorch/saver.py", line 5, in save_model
>     model = MainModel.KitModel(weight_filepath)
>   File "faceVer.py", line 161, in __init__
>     self.fc1 = self.__batch_normalization(0, 'fc1', num_features=512, eps=1.9999999494757503e-05, momentum=0.8999999761581421)
>   File "faceVer.py", line 381, in __batch_normalization
>     else:           raise NotImplementedError()
> NotImplementedError

**Comment by tengerye** [comment]
Hi, may I ask if someone is seeing it?
