### ISSUE TITLE
How to get the .graph file？

### ISSUE THREAD

**Issue by ToBigboss** [Microsoft/MMdnn#501]
mmconvert -sf tensorflow -in model.ckpt-30000.meta -iw model.ckpt-30000 --dstNodeName add -df caffe -om tf_align
Parse file [model.ckpt-30000.meta] with binary format successfully.
Tensorflow model file [model.ckpt-30000.meta] loaded successfully.
Tensorflow checkpoint file [model.ckpt-30000] loaded successfully. [36] variables loaded.
Traceback (most recent call last):
  File "/home/super/.local/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/super/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/super/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 68, in _convert
    parser = TensorflowParser(args.network, args.weights, args.dstNodeName)
  File "/home/super/.local/lib/python2.7/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 221, in __init__
    model = extract_sub_graph(model, dest_nodes)
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 174, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/home/super/.local/lib/python2.7/site-packages/tensorflow/python/framework/graph_util_impl.py", line 133, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: add is not in graph

**Comment by sssimpleboy** [comment]
hello！ Could you tell me how to solve this problem ? Thx!
