### ISSUE TITLE
TF->caffe   68points facial landmarks model,  I get a lot of errors 

### ISSUE THREAD

**Issue by ToBigboss** [Microsoft/MMdnn#502]
ubuntu 16.04
python2.7

log:
mmconvert -sf tensorflow -in model.ckpt-30000.meta -iw model.ckpt-30000 --dstNodeName alignmentnet/add -df caffe -om tf_align
Parse file [model.ckpt-30000.meta] with binary format successfully.
Tensorflow model file [model.ckpt-30000.meta] loaded successfully.
Tensorflow checkpoint file [model.ckpt-30000] loaded successfully. [36] variables loaded.
2018-11-20 12:35:27.440724: I tensorflow/tools/graph_transforms/transform_graph.cc:317] Applying fold_constants
2018-11-20 12:35:27.511719: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Tensorflow has not supported operator [ResizeNearestNeighbor] with name [alignmentnet/up_3].
Tensorflow has not supported operator [ResizeNearestNeighbor] with name [alignmentnet/up_2].
IR network structure is saved as [86666f4abc7e4591a666d47896c82035.json].
IR network structure is saved as [86666f4abc7e4591a666d47896c82035.pb].
IR weights are saved as [86666f4abc7e4591a666d47896c82035.npy].
Parse file [86666f4abc7e4591a666d47896c82035.pb] with binary format successfully.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_0_0//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_0_1//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_1_0//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_1_1//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_2_0//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_2_1//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_3_0//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_3_1//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/up_3. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_3_2//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/up_2. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_2_2//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/alignmentnet/conv_1_2//alpha. Ignored.
Warning: Graph Construct a self-loop node alignmentnet/prelu/alpha. Ignored.
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmconvert')()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 144, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 132, in gen_code
    func(current_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 197, in emit_Conv
    pad_h, pad_w = self._get_symmetric_padding(IR_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 160, in _get_symmetric_padding
    if IR_parent_node.type == 'Pad':
AttributeError: 'NoneType' object has no attribute 'type'

I want to know  how fix it ?

**Comment by rainLiuplus** [comment]
It seems that the reason is that mmdnn does not support the ResizeNearestNeighbor operator. Maybe You can try adding this operator. Thanks!
