### ISSUE TITLE
mxnet->keras

### ISSUE THREAD

**Issue by liuyan20062010** [Microsoft/MMdnn#503]
Platform (like ubuntu 16.04):

Python version:

Source framework with version (like Tensorflow 1.10 with GPU):

Running scripts:
 python -m mmdnn.conversion._script.convertToIR -f mxnet -n model-symbol.json -w model-0000.params -d keras --inputShape 3,112,112

python -m mmdnn.conversion._script.IRToCode -f keras --IRModelPath keras.pb --dstModelPath keras.py -w keras.npy

errors:
Using TensorFlow backend.
Parse file [keras.pb] with binary format successfully.
KerasEmitter has not supported operator [Constant].
mulscalar0_second
KerasEmitter has not supported operator [Constant].
minusscalar0_second
KerasEmitter has not supported operator [Sub].
minusscalar0
Traceback (most recent call last):
  File "/home/liuyan/anaconda3/envs/tensorflow110/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liuyan/anaconda3/envs/tensorflow110/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liuyan/MMdnn/mmdnn/conversion/_script/IRToCode.py", line 122, in <module>
    _main()
  File "/home/liuyan/MMdnn/mmdnn/conversion/_script/IRToCode.py", line 117, in _main
    ret = _convert(args)
  File "/home/liuyan/MMdnn/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/home/liuyan/MMdnn/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/home/liuyan/MMdnn/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/home/liuyan/MMdnn/mmdnn/conversion/keras/keras2_emitter.py", line 113, in gen_code
    func(current_node)
  File "/home/liuyan/MMdnn/mmdnn/conversion/keras/keras2_emitter.py", line 262, in emit_Mul
    raise NotImplementedError()
NotImplementedError

**Comment by rainLiuplus** [comment]
Hi @liuyan20062010,  Could you please provide your model for us to debug?
