### ISSUE TITLE
mmconvert from keras to caffe fails with AssertionError

### ISSUE THREAD

**Issue by coveritytest** [Microsoft/MMdnn#524]
Platform (like ubuntu 16.04/win10):

Using the Docker image, so Debian stretch/sid

Python version:

Using the Docker image, so Python 2.7.12

Source framework with version (like Tensorflow 1.4.1 with GPU):

keras

Destination framework with version (like CNTK 2.3 with GPU):

caffe

Pre-trained model path (webpath or webdisk path):

keras_cifar10_trained_model.h5

Running scripts:

mmconvert -sf keras -im keras_cifar10_trained_model.h5 -df caffe -om myModel.prototxt

Stacktrace:

root@6412cc1e4f8c:~# mmconvert -sf keras -im keras_cifar10_trained_model.h5 -df caffe -om myModel.prototxt
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 39, in _convert
    parser = Keras2Parser(model)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/keras/keras2_parser.py", line 104, in __init__
    assert False
AssertionError

**Comment by coveritytest** [comment]
Can be solved with https://github.com/Microsoft/MMdnn/issues/222#issuecomment-393729215
