### ISSUE TITLE
ValueError: Unknown layer: UpsampleLike

### ISSUE THREAD

**Issue by coveritytest** [Microsoft/MMdnn#525]
Platform (like ubuntu 16.04/win10):

ubuntu 16.04

Python version:

2.7.12

Source framework with version (like Tensorflow 1.4.1 with GPU):

keras

Destination framework with version (like CNTK 2.3 with GPU):

caffe

Running scripts:

mmconvert -sf keras -iw net.hdf5 -df caffe -om net

Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 39, in _convert
    parser = Keras2Parser(model)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/keras/keras2_parser.py", line 95, in __init__
    'DepthwiseConv2D': _keras.applications.mobilenet.DepthwiseConv2D
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 270, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 347, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2525, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2511, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: UpsampleLike

**Comment by rainLiuplus** [comment]
Hi @coveritytest , could you provide your model for us to debug?
