### ISSUE TITLE
The size of Generated Prototxt and Caffemodel is zero

### ISSUE THREAD

**Issue by suikammd** [Microsoft/MMdnn#528]
Parse file [model_30epoch.ckpt.meta] with binary format successfully.
Tensorflow model file [model_30epoch.ckpt.meta] loaded successfully.
Tensorflow checkpoint file [model_30epoch.ckpt] loaded successfully. [220] variables loaded.
Tensorflow has not supported operator [Conv3D] with name [encoding0/Conv3D].
Tensorflow has not supported operator [BiasAdd] with name [encoding0/BiasAdd].
Tensorflow has not supported operator [Slice] with name [loss_function/Slice].
........
Tensorflow has not supported operator [ScalarSummary] with name [loss_function/loss].
IR network structure is saved as [2b98bf73e5584965930870b777ba06c6.json].
IR network structure is saved as [2b98bf73e5584965930870b777ba06c6.pb].
IR weights are saved as [2b98bf73e5584965930870b777ba06c6.npy].
Parse file [2b98bf73e5584965930870b777ba06c6.pb] with binary format successfully.
Warning: Graph Construct a self-loop node Shape_2. Ignored.
.......
Warning: Graph Construct a self-loop node logits/BiasAdd. Ignored.
Warning: Graph Construct a self-loop node loss_function/SoftmaxCrossEntropyWithLogits. Ignored.
Traceback (most recent call last):
  File "/usr/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/usr/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/usr/lib/python2.7/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/usr/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 143, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/usr/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/usr/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/usr/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 131, in gen_code
    func(current_node)
  File "/usr/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 342, in emit_BatchNorm
    self.parent_variable_name(IR_node),
  File "/usr/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 41, in parent_variable_name
    return self.IR_graph.get_parent(IR_node.name, path).real_variable_name
AttributeError: 'NoneType' object has no attribute 'real_variable_name'

**Comment by suikammd** [comment]
I found I should use python 2.7 and the corresponding 3d caffe but I get  generated prototxt and caffemodel with size 0. 
Anybody facing this problem?

**Comment by rainLiuplus** [comment]
Seems due to mmdnn does not support the operators you mentioned above.  Maybe you can add them by yourself or provide your model for us to debug?
