### ISSUE TITLE
Convert TensorFlow Squeezenet to IR

### ISSUE THREAD

**Issue by michhar** [Microsoft/MMdnn#531]
Platform (like ubuntu 16.04/win10): win10

Python version: 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): Tensorflow 1.9

Destination framework with version (like CNTK 2.3 with GPU): IR

Pre-trained model path (webpath or webdisk path):  I exported a model from Microsoft Custom Vision Service using the "TensorFlow" exporter and converted the frozen pb to checkpoint files: https://drive.google.com/open?id=1hkiS0uf2NLfRTZSZp40MOv21bCrLaDuw

Running scripts:

Command:  `mmtoir -f tensorflow -w model.ckpt -n model.ckpt.meta --inNodeName "prefix/Placeholder" --dstNodeName "prefix/model_outputs" --inputShape 227 -d model.ir`

Error:
```
(py36) C:\Users\michhar.REDMOND\Documents\bin\python\custom_vision\tf_path>mmtoir -f tensorflow -w model.ckpt -n model.ckpt.meta --inNodeName "prefix/Placeholder" --dstNodeName "prefix/model_outputs" --inputShape 227 -d model.ir
Parse file [model.ckpt.meta] with binary format successfully.
Tensorflow model file [model.ckpt.meta] loaded successfully.
Tensorflow checkpoint file [model.ckpt] loaded successfully. [1] variables loaded.
Tensorflow has not supported operator [Neg] with name [prefix/data_bn/data_bn/Neg].
Tensorflow has not supported operator [Rsqrt] with name [prefix/data_bn/data_bn/Rsqrt].
Traceback (most recent call last):
  File "c:\anaconda3\envs\py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\py36\Scripts\mmtoir.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 184, in _main
    ret = _convert(args)
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 102, in _convert
    parser.run(args.dstPath)
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\common\DataStructure\parser.py", line 22, in run
    self.gen_IR()
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_parser.py", line 311, in gen_IR
    func(current_node)
  File "c:\anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_parser.py", line 409, in rename_Conv2D
    self.set_weight(source_node.name, 'weights', self.ckpt_data[W.name])
KeyError: 'prefix/conv1/weights'
```

Additional Info:

* The architecture node names are (and you can see that that node name "'prefix/conv1/weights" does exist):
```
prefix/fc/biases
prefix/fc/biases/read
prefix/fc/weights
prefix/fc/weights/read
prefix/fc/Reshape/shape
prefix/fire9_concat/axis
prefix/fire9_expand3x3/biases
prefix/fire9_expand3x3/biases/read
prefix/fire9_expand3x3/weights
prefix/fire9_expand3x3/weights/read
prefix/fire9_expand1x1/biases
prefix/fire9_expand1x1/biases/read
prefix/fire9_expand1x1/weights
prefix/fire9_expand1x1/weights/read
prefix/fire9_squeeze1x1/biases
prefix/fire9_squeeze1x1/biases/read
prefix/fire9_squeeze1x1/weights
prefix/fire9_squeeze1x1/weights/read
prefix/fire8_concat/axis
prefix/fire8_expand3x3/biases
prefix/fire8_expand3x3/biases/read
prefix/fire8_expand3x3/weights
prefix/fire8_expand3x3/weights/read
prefix/fire8_expand1x1/biases
prefix/fire8_expand1x1/biases/read
prefix/fire8_expand1x1/weights
prefix/fire8_expand1x1/weights/read
prefix/fire8_squeeze1x1/biases
prefix/fire8_squeeze1x1/biases/read
prefix/fire8_squeeze1x1/weights
prefix/fire8_squeeze1x1/weights/read
prefix/fire7_concat/axis
prefix/fire7_expand3x3/biases
prefix/fire7_expand3x3/biases/read
prefix/fire7_expand3x3/weights
prefix/fire7_expand3x3/weights/read
prefix/fire7_expand1x1/biases
prefix/fire7_expand1x1/biases/read
prefix/fire7_expand1x1/weights
prefix/fire7_expand1x1/weights/read
prefix/fire7_squeeze1x1/biases
prefix/fire7_squeeze1x1/biases/read
prefix/fire7_squeeze1x1/weights
prefix/fire7_squeeze1x1/weights/read
prefix/fire6_concat/axis
prefix/fire6_expand3x3/biases
prefix/fire6_expand3x3/biases/read
prefix/fire6_expand3x3/weights
prefix/fire6_expand3x3/weights/read
prefix/fire6_expand1x1/biases
prefix/fire6_expand1x1/biases/read
prefix/fire6_expand1x1/weights
prefix/fire6_expand1x1/weights/read
prefix/fire6_squeeze1x1/biases
prefix/fire6_squeeze1x1/biases/read
prefix/fire6_squeeze1x1/weights
prefix/fire6_squeeze1x1/weights/read
prefix/fire5_concat/axis
prefix/fire5_expand3x3/biases
prefix/fire5_expand3x3/biases/read
prefix/fire5_expand3x3/weights
prefix/fire5_expand3x3/weights/read
prefix/fire5_expand1x1/biases
prefix/fire5_expand1x1/biases/read
prefix/fire5_expand1x1/weights
prefix/fire5_expand1x1/weights/read
prefix/fire5_squeeze1x1/biases
prefix/fire5_squeeze1x1/biases/read
prefix/fire5_squeeze1x1/weights
prefix/fire5_squeeze1x1/weights/read
prefix/fire4_concat/axis
prefix/fire4_expand3x3/biases
prefix/fire4_expand3x3/biases/read
prefix/fire4_expand3x3/weights
prefix/fire4_expand3x3/weights/read
prefix/fire4_expand1x1/biases
prefix/fire4_expand1x1/biases/read
prefix/fire4_expand1x1/weights
prefix/fire4_expand1x1/weights/read
prefix/fire4_squeeze1x1/biases
prefix/fire4_squeeze1x1/biases/read
prefix/fire4_squeeze1x1/weights
prefix/fire4_squeeze1x1/weights/read
prefix/fire3_concat/axis
prefix/fire3_expand3x3/biases
prefix/fire3_expand3x3/biases/read
prefix/fire3_expand3x3/weights
prefix/fire3_expand3x3/weights/read
prefix/fire3_expand1x1/biases
prefix/fire3_expand1x1/biases/read
prefix/fire3_expand1x1/weights
prefix/fire3_expand1x1/weights/read
prefix/fire3_squeeze1x1/biases
prefix/fire3_squeeze1x1/biases/read
prefix/fire3_squeeze1x1/weights
prefix/fire3_squeeze1x1/weights/read
prefix/fire2_concat/axis
prefix/fire2_expand3x3/biases
prefix/fire2_expand3x3/biases/read
prefix/fire2_expand3x3/weights
prefix/fire2_expand3x3/weights/read
prefix/fire2_expand1x1/biases
prefix/fire2_expand1x1/biases/read
prefix/fire2_expand1x1/weights
prefix/fire2_expand1x1/weights/read
prefix/fire2_squeeze1x1/biases
prefix/fire2_squeeze1x1/biases/read
prefix/fire2_squeeze1x1/weights
prefix/fire2_squeeze1x1/weights/read
prefix/conv1/biases
prefix/conv1/biases/read
prefix/conv1/weights
prefix/conv1/weights/read
prefix/data_bn/data_bn/add/y
prefix/data_bn/variance
prefix/data_bn/variance/read
prefix/data_bn/data_bn/add
prefix/data_bn/data_bn/Rsqrt
prefix/data_bn/mean
prefix/data_bn/mean/read
prefix/data_bn/data_bn/Neg
prefix/data_bn/data_bn/mul_1
prefix/Placeholder
prefix/data_bn/data_bn/mul
prefix/data_bn/data_bn/add_1
prefix/conv1/Conv2D
prefix/conv1/BiasAdd
prefix/conv1/conv1
prefix/pool1
prefix/fire2_squeeze1x1/Conv2D
prefix/fire2_squeeze1x1/BiasAdd
prefix/fire2_squeeze1x1/fire2_squeeze1x1
prefix/fire2_expand3x3/Conv2D
prefix/fire2_expand3x3/BiasAdd
prefix/fire2_expand3x3/fire2_expand3x3
prefix/fire2_expand1x1/Conv2D
prefix/fire2_expand1x1/BiasAdd
prefix/fire2_expand1x1/fire2_expand1x1
prefix/fire2_concat
prefix/fire3_squeeze1x1/Conv2D
prefix/fire3_squeeze1x1/BiasAdd
prefix/fire3_squeeze1x1/fire3_squeeze1x1
prefix/fire3_expand3x3/Conv2D
prefix/fire3_expand3x3/BiasAdd
prefix/fire3_expand3x3/fire3_expand3x3
prefix/fire3_expand1x1/Conv2D
prefix/fire3_expand1x1/BiasAdd
prefix/fire3_expand1x1/fire3_expand1x1
prefix/fire3_concat
prefix/pool3
prefix/fire4_squeeze1x1/Conv2D
prefix/fire4_squeeze1x1/BiasAdd
prefix/fire4_squeeze1x1/fire4_squeeze1x1
prefix/fire4_expand3x3/Conv2D
prefix/fire4_expand3x3/BiasAdd
prefix/fire4_expand3x3/fire4_expand3x3
prefix/fire4_expand1x1/Conv2D
prefix/fire4_expand1x1/BiasAdd
prefix/fire4_expand1x1/fire4_expand1x1
prefix/fire4_concat
prefix/fire5_squeeze1x1/Conv2D
prefix/fire5_squeeze1x1/BiasAdd
prefix/fire5_squeeze1x1/fire5_squeeze1x1
prefix/fire5_expand3x3/Conv2D
prefix/fire5_expand3x3/BiasAdd
prefix/fire5_expand3x3/fire5_expand3x3
prefix/fire5_expand1x1/Conv2D
prefix/fire5_expand1x1/BiasAdd
prefix/fire5_expand1x1/fire5_expand1x1
prefix/fire5_concat
prefix/pool5
prefix/fire6_squeeze1x1/Conv2D
prefix/fire6_squeeze1x1/BiasAdd
prefix/fire6_squeeze1x1/fire6_squeeze1x1
prefix/fire6_expand3x3/Conv2D
prefix/fire6_expand3x3/BiasAdd
prefix/fire6_expand3x3/fire6_expand3x3
prefix/fire6_expand1x1/Conv2D
prefix/fire6_expand1x1/BiasAdd
prefix/fire6_expand1x1/fire6_expand1x1
prefix/fire6_concat
prefix/fire7_squeeze1x1/Conv2D
prefix/fire7_squeeze1x1/BiasAdd
prefix/fire7_squeeze1x1/fire7_squeeze1x1
prefix/fire7_expand3x3/Conv2D
prefix/fire7_expand3x3/BiasAdd
prefix/fire7_expand3x3/fire7_expand3x3
prefix/fire7_expand1x1/Conv2D
prefix/fire7_expand1x1/BiasAdd
prefix/fire7_expand1x1/fire7_expand1x1
prefix/fire7_concat
prefix/fire8_squeeze1x1/Conv2D
prefix/fire8_squeeze1x1/BiasAdd
prefix/fire8_squeeze1x1/fire8_squeeze1x1
prefix/fire8_expand3x3/Conv2D
prefix/fire8_expand3x3/BiasAdd
prefix/fire8_expand3x3/fire8_expand3x3
prefix/fire8_expand1x1/Conv2D
prefix/fire8_expand1x1/BiasAdd
prefix/fire8_expand1x1/fire8_expand1x1
prefix/fire8_concat
prefix/fire9_squeeze1x1/Conv2D
prefix/fire9_squeeze1x1/BiasAdd
prefix/fire9_squeeze1x1/fire9_squeeze1x1
prefix/fire9_expand3x3/Conv2D
prefix/fire9_expand3x3/BiasAdd
prefix/fire9_expand3x3/fire9_expand3x3
prefix/fire9_expand1x1/Conv2D
prefix/fire9_expand1x1/BiasAdd
prefix/fire9_expand1x1/fire9_expand1x1
prefix/fire9_concat
prefix/pool10
prefix/fc/Reshape
prefix/fc/fc/MatMul
prefix/fc/fc
prefix/loss
prefix/model_outputs
```

Any help greatly appreciated!!

**Comment by rainLiuplus** [comment]
Hi @michhar , I tested your model and found that the weight files are quite small. Have you saved it correctly?

**Comment by michhar** [comment]
@anrothMSFT Adding you here as I'm utilizing an exported Custom Vision model (exported 12/17/2018) with MMdnn (in hopes of converting to TensorRT or PyTorch).  I'd saved the model with the `tf.train.Saver()` as a checkpoint format from the frozen model def, model.pb from the Custom Vision Service Tensorflow export (2.8MB) with the following code (also, note, I'm writing out for tensorboard files to explore graph).

```python
"""
https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc
https://blog.metaflow.fr/tensorflow-saving-restoring-and-mixing-multiple-models-c4c94d5d7125
https://stackoverflow.com/questions/33759623/tensorflow-how-to-save-restore-a-model
"""

import argparse 
import tensorflow as tf

def load_graph(frozen_graph_filename):
    # We load the protobuf file from the disk and parse it to retrieve the 
    # unserialized graph_def
    with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())

    # Then, we import the graph_def into a new Graph and returns it 
    with tf.Graph().as_default() as graph:
        # The name var will prefix every op/nodes in your graph
        # Since we load everything in a new graph, this is not needed
        tf.import_graph_def(graph_def, name="prefix")
    return graph


if __name__ == '__main__':
    # Let's allow the user to pass the filename as an argument
    parser = argparse.ArgumentParser()
    parser.add_argument("--frozen_model_filename", default="results/frozen_model.pb", type=str, help="Frozen model file to import")
    args = parser.parse_args()

    # We use our "load_graph" function
    graph = load_graph(args.frozen_model_filename)

    # We can verify that we can access the list of operations in the graph
    for op in graph.get_operations():
        print(op.name)
        # prefix/Placeholder/inputs_placeholder
        # ...
        # prefix/Accuracy/predictions
    with graph.as_default():
        batch_size_placeholder = tf.placeholder(tf.int64, name='batch_size_ph')
        features_placeholder = tf.placeholder(tf.int64, [227, 227, 3], 'prefix/Placeholder')
        labels_placeholder = tf.placeholder(tf.int32, [None, 2], 'labels_data_ph')
        prediction = graph.get_tensor_by_name('prefix/model_outputs:0')

        input_sample = tf.random_uniform([227, 227, 3], minval=0, maxval=255, \
            dtype=tf.int32, seed=None, name="prefix/model_outputs")
        output_sample = tf.Variable(0, name="outputs")
        saver = tf.train.Saver()

        with tf.Session(graph=graph) as sess:
            # For tensorboard
            writer = tf.summary.FileWriter('logs', sess.graph)

            tf.global_variables_initializer().run(session=sess)
            # Saving
            inputs = {
                "batch_size_placeholder": batch_size_placeholder,
                "features_placeholder": features_placeholder,
                "labels_placeholder": labels_placeholder,
            }
            outputs = {"prediction": prediction}

            # Save a protobuf
            tf.saved_model.simple_save(
                sess, 'model_tf', inputs, outputs
            )
            
            # Save a checkpoint file, index and meta
            save_path = saver.save(sess, "./new_checkpoints/model.ckpt")

            # For tensorboard
            writer.close()
```

The resulting sizes of the checkpoint files are as follows. (As you can see, the `.data` file is nearly empty indicating there are no weights in the protobuf file.  Is this expected @anrothMSFT?  Thanks!)

```unix
-rw-r--r-- 1 michhar 1049089   77 Feb 12 17:38 checkpoint
-rw-r--r-- 1 michhar 1049089    4 Feb 12 17:38 model.ckpt.data-00000-of-00001
-rw-r--r-- 1 michhar 1049089  123 Feb 12 17:38 model.ckpt.index
-rw-r--r-- 1 michhar 1049089 2.9M Feb 12 17:38 model.ckpt.meta
```

cc @rainLiuplus Thanks you.  (I believe this may be closed as it looks to be a Custom Vision related issue)
