### ISSUE TITLE
YOLOv3 Darknet model to IR to TensorFlow with `mmtomodel` failing

### ISSUE THREAD

**Issue by michhar** [Microsoft/MMdnn#532]
Platform (like ubuntu 16.04/win10): win10

Python version: 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): Darknet

Destination framework with version (like CNTK 2.3 with GPU): TensorFlow 1.9

Pre-trained model path (webpath or webdisk path): https://drive.google.com/open?id=11NFgoQkQNjTjdh_o7JH8BdFZ3M8HcA_1

Running scripts: 

The plan:  Darknet -> IR, create TensorFlow code for model, and save as a TF model (wishing to convert eventually to TensorRT).  This is a Tiny YOLOv3 model with 2 input classes.  All files you should need are in the zip folder above.  I have TensorFlow 1.9.0.  The following commands were used:

```
mmtoir -f darknet -n yolov3-tiny.cfg -w yolov3-tiny_lr0.000001_ep5000_mb16_loss2.54_.weights -o darknet2ir

mmtocode -f tensorflow --IRModelPath darknet2ir.pb --IRWeightPath darknet2ir.npy --dstModelPath tf_yolov3.py

mmtomodel -f tensorflow -in tf_yolov3.py -iw darknet2ir.npy -o tf_yolov3 --dump_tag SERVING

```
Error:

```
(py36) C:\Users\michhar.REDMOND\Documents\bin\python\mmdnn>mmtomodel -f tensorflow -in tf_yolov3.py -iw darknet2ir.npy -o tf_yolov3 --dump_tag SERVING
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 24 and 26. Shapes are [?,24,24] and [?,26,26]. for 'layer21-concat' (op: 'ConcatV2') with input shapes: [?,24,24,128], [?,26,26,256], [] and with computed input tensors: input[2] = <3>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\py36\Scripts\mmtomodel-script.py", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmtomodel')()
  File "C:\Anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\_script\dump_code.py", line 79, in _main
    ret = dump_code(args.framework, args.inputNetwork, args.inputWeight, args.outputModel, args.dump_tag)
  File "C:\Anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\_script\dump_code.py", line 25, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath, dump_tag)
  File "C:\Anaconda3\envs\py36\lib\site-packages\mmdnn\conversion\tensorflow\saver.py", line 9, in save_model
    input, model = MainModel.KitModel(weight_filepath)
  File "tf_yolov3.py", line 64, in KitModel
    layer21_concat  = tf.concat([layer20_upsample, layer9_act], 3, name = 'layer21-concat')
  File "C:\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1189, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "C:\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1105, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "C:\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\ops.py", line 1734, in __init__
    control_input_ops)
  File "C:\Anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 24 and 26. Shapes are [?,24,24] and [?,26,26]. for 'layer21-concat' (op: 'ConcatV2') with input shapes: [?,24,24,128], [?,26,26,256], [] and with computed input tensors: input[2] = <3>.
```

Any help greatly appreciated.  Excited about the progress on this project.

**Comment by rainLiuplus** [comment]
Hi @michhar,  Thanks for your attention, we are going to handle it. if there is any progress we will ping you.

**Comment by lp55** [comment]
Hi, any news on this? I'm also trying to convert a YOLOv3 darknet model, and I get the same error.

**Comment by nscotto** [comment]
Same kind of error for me.
Occurs on `layer21_concat`, with same kind of error in dimensions: 
for my model version: 
```[(None, 34, 34, 128), (None, 36, 36, 256)]```
