### ISSUE TITLE
Mxnet ResNet50V1d to Keras Model

### ISSUE THREAD

**Issue by chrisluu** [Microsoft/MMdnn#536]
Platform: ubuntu 16.04

Python version: Python 3.6.5

Source framework with version: mxnet-cu90 1.3.1

Destination framework with version: Keras 2.1.5

Pre-trained model path: 
[ResNet50V1d-symbol.json](https://pan.baidu.com/s/1QuoEDruVP8mNFA-clcAXGw)
[ResNet50V1d-0000.params](https://pan.baidu.com/s/1BEly9-BUKL6BX4s09iZpyA)

Running scripts: python3 -m mmdnn.conversion._script.convertToIR -f mxnet -n ResNet50V1d-symbol.json -w ResNet50V1d-0000.params -d mxnet_resnet50v1d --inputShape 3,224,224

Error: 
```
Traceback (most recent call last):
  File "/home/imsight/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/imsight/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/imsight/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 197, in <module>
    _main()
  File "/home/imsight/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/imsight/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/home/imsight/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/imsight/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 262, in gen_IR
    func(current_node)
  File "/home/imsight/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 598, in rename_Pooling
    self.set_output_shape(source_node, IR_node)
  File "/home/imsight/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 279, in set_output_shape
    for sym in sym_group:
  File "/home/imsight/anaconda3/lib/python3.6/site-packages/mxnet/symbol/symbol.py", line 93, in <genexpr>
    return (self[i] for i in self.list_outputs())
  File "/home/imsight/anaconda3/lib/python3.6/site-packages/mxnet/symbol/symbol.py", line 517, in __getitem__
    raise ValueError('There are multiple outputs with name \"%s\"' % index)
ValueError: There are multiple outputs with name "relu22_fwd_output"
```

**Any suggestion would be very appreciated!**

**Comment by linmajia** [comment]
@chrisluu , thank you very much for the feedback.

There is some problem to download your model files. Would you please place them on another public storage like GitHub?
