### ISSUE TITLE
mxnet pareser does not support upsample op

### ISSUE THREAD

**Issue by memoiry** [Microsoft/MMdnn#541]
Platform (like ubuntu 16.04/win10):
**ubuntu16.04**
Python version:
**3.7**
Source framework with version (like Tensorflow 1.4.1 with GPU):
**mxnet**
Destination framework with version (like CNTK 2.3 with GPU):
**tensorflow 1.8 with gpu**
Pre-trained model path (webpath or webdisk path):

Running scripts: 
mmtoir -f mxnet -n firenet-symbol.json -w firenet-0000.params -d resnet50 --inputShape 8,1088,800

```bash
(tensorflow) ➜  mx-lidar git:(master) ✗ mmtoir -f mxnet -n firenet-symbol.json -w firenet-0000.params -d resnet50 --inputShape 8,1088,800
/home/xuguodong/anaconda3/envs/tensorflow/lib/python3.6/site-packages/mxnet/module/base_module.py:55: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
        data
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator UpSampling with name resnetv1pyr0_upsampling0.
Traceback (most recent call last):
  File "/home/xuguodong/anaconda3/envs/tensorflow/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/xuguodong/anaconda3/envs/tensorflow/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/xuguodong/anaconda3/envs/tensorflow/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/home/xuguodong/anaconda3/envs/tensorflow/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/xuguodong/anaconda3/envs/tensorflow/lib/python3.6/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 265, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "/home/xuguodong/anaconda3/envs/tensorflow/lib/python3.6/site-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 376, in rename_UNKNOWN
    raise NotImplementedError()
NotImplementedError
```

I'm trying to convert mxnet model to tensorflow, so at first, I'm trying to convert my mxnet model to IR and it got stuck. 

It seems that the **UpSampling** op is not supported in mxnet parser, is there any plan to add it for mxnet parser? or could you please provide other suggestion to convert this mxnet model to tensorflow? Thanks!

**Comment by rainLiuplus** [comment]
Hi @memoiry, could you please provide your model so that we can check this op. Thanks!

**Comment by zlwzlwzlw** [comment]
i also have the same problem, does mxnet pareser add the upsampling op?

**Comment by irmowan** [comment]
Same problem.

**Comment by gasgallo** [comment]
@memoiry Have you solved this issue? I'm having the same problem

**Comment by Akhp888** [comment]
having same isuue
