### ISSUE TITLE
Error when converting PyTorch model to TF model

### ISSUE THREAD

**Issue by ShuaiHuang** [Microsoft/MMdnn#542]
Platform (like ubuntu 16.04/win10): Ubuntu16.04

Python version: 3.6.7

Source framework with version (like Tensorflow 1.4.1 with GPU): PyTorch 0.4.0

Destination framework with version (like CNTK 2.3 with GPU): TensorFlow 1.12

Pre-trained model path (webpath or webdisk path): Customed ResNet-50

Running scripts:

```
mmconvert -sf pytorch -in ../../model/model_full_1_8592_8663.pkl -df tensorflow --inputShape=3,320,256 -om sppe_tf
```

----

I made some modification on ResNet-50, and encounter the following error.

```
Traceback (most recent call last):
  File "/home/solomon/.conda/envs/pytorch040/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 74, in __init__
    model = torch.load(model_file_name)
  File "/home/solomon/.conda/envs/pytorch040/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/solomon/.conda/envs/pytorch040/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'FastPose_SE' on <module '__main__' from '/home/solomon/.conda/envs/pytorch040/bin/mmconvert'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/solomon/.conda/envs/pytorch040/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/solomon/.conda/envs/pytorch040/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/solomon/.conda/envs/pytorch040/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(args.network, inputshape[0])
  File "/home/solomon/.conda/envs/pytorch040/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 76, in __init__
    model = torch.load(model_file_name, map_location='cpu')
  File "/home/solomon/.conda/envs/pytorch040/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/solomon/.conda/envs/pytorch040/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'FastPose_SE' on <module '__main__' from '/home/solomon/.conda/envs/pytorch040/bin/mmconvert'>
```

**Comment by rainLiuplus** [comment]
Hi @ShuaiHuang , it seems that this is a problem with the pytorch model loading.  Please refer  https://discuss.pytorch.org/t/error-loading-saved-model/8371. Thanks!
