### ISSUE TITLE
ERROR when running demo pytorch to tensorflow

### ISSUE THREAD

**Issue by stoneyang** [Microsoft/MMdnn#543]
* Platform (like ubuntu 16.04/win10): centos

* Python version: 2.7.5

* Source framework with version (like Tensorflow 1.4.1 with GPU): pytorch 0.4.0 with GPU

* Destination framework with version (like CNTK 2.3 with GPU): Tensorflow 1.4.0 with GPU

* Pre-trained model path (webpath or webdisk path): https://download.pytorch.org/models/resnet101-5d3b4d8f.pth

* Running scripts: 

```
mmconvert -sf pytorch -in resnet101-5d3b4d8f.pth -df tensorflow --inputShape 3 224 224 -om resnet101_pytorch2tf
```

* ERROR:

```
/usr/lib64/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/bin/mmconvert", line 9, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmconvert')()
  File "/home/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 79, in _convert
    parser = PytorchParser(args.network, inputshape)
  File "/home/.local/lib/python2.7/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 76, in __init__
    self.pytorch_graph = PytorchGraph(model)
  File "/home/.local/lib/python2.7/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 61, in __init__
    self.state_dict = _unique_state_dict(self.model)
  File "/home/.local/lib/python2.7/site-packages/torch/jit/__init__.py", line 259, in _unique_state_dict
    state_dict = module.state_dict(keep_vars=keep_vars)
AttributeError: 'OrderedDict' object has no attribute 'state_dict'
```

* Related issues:
  1. #542 
  2. #419 
  3. #274 
  4. #324

**Comment by ShuaiHuang** [comment]
It seems like that the model you saved in PyTorch is not full model.

**Comment by rainLiuplus** [comment]
Yeah, the reason is that you did not save the full pytorch model. Please refer to https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md#faq. Thanks!
