### ISSUE TITLE
convert tf to caffe error

### ISSUE THREAD

**Issue by xubin19939** [Microsoft/MMdnn#548]
Platform (like ubuntu 16.04/win10):ubuntu 16.04

Python version:2.7

Source framework with version (like Tensorflow 1.4.1 with GPU):tensorflow 1.8.0 cpu

Destination framework with version (like CNTK 2.3 with GPU):caffe

Pre-trained model path (webpath or webdisk path):https://github.com/xubin19939/tftocaffe

Running scripts:
$ mmconvert -sf tensorflow -in model199000model.ckpt.meta -iw model199000model.c
kpt --dstNodeName Softmax -df caffe -om tf_resnet
Parse file [model199000model.ckpt.meta] with binary format successfully.
Tensorflow model file [model199000model.ckpt.meta] loaded successfully.
Tensorflow checkpoint file [model199000model.ckpt] loaded successfully. [19] variables loaded.
2019-01-07 15:06:55.798600: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_constants
2019-01-07 15:06:55.823933: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Tensorflow has not supported operator [NoOp] with name [Dropout/cond/dropout/Shape/Switch:1].
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmconvert')()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 359, in gen_IR
    func(current_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 436, in rename_Placeholder
    IR_node.attr['shape'].shape.dim[0].size = -1
IndexError: list index out of range

below is my definition of placeholder:
height=64;
width=64;
inputs = tf.placeholder(tf.float32, shape=[None, height, width, 3], name='inputs')
is there something wrong with placeholder?how should I fix it?
thanks o lot for help
and I have tried on gpu version tf1.8.0 ,error remains

**Comment by rainLiuplus** [comment]
Hi @xubin19939 , seems your model includes [keras.layers.Dropout](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/keras/layers/core.py#L145), which is related to condition operators ([tf.cond](https://www.tensorflow.org/api_docs/python/tf/cond)) and this placeholder is [K.learning_phrase](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/keras/layers/core.py#L139).  It is hard to convert such operators to caffe. For this reason mmdnn may not work.

**Comment by jiamian2009** [comment]
Hi@xubin19939,I am also same the issue.can you share the solution of th problem ?
