### ISSUE TITLE
KeyError when converting tf facenet to caffe 

### ISSUE THREAD

**Issue by oldzandmissmiao0312** [Microsoft/MMdnn#557]
Platform (like ubuntu 16.04/win10):ubuntu 16.04

Python version:2.7

Source framework with version (like Tensorflow 1.4.1 with GPU): 1.9.0

Destination framework with version (like CNTK 2.3 with GPU):caffe cpu

Pre-trained model path (webpath or webdisk path):https://drive.google.com/open?id=1EXPBSXwTaqrSC0OhUdXNmKSh9qJUQ55-
Running scripts:
mmconvert -sf tensorflow -iw 20180402-114759.pb --inNodeName input --inputShape 224,224,3 --dstNodeName InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool -df caffe -om tf_facenet

2019-01-09 22:58:58.048560: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
IR network structure is saved as [6b24000591d341cf9474032eef3a70a9.json].
IR network structure is saved as [6b24000591d341cf9474032eef3a70a9.pb].
IR weights are saved as [6b24000591d341cf9474032eef3a70a9.npy].
Parse file [6b24000591d341cf9474032eef3a70a9.pb] with binary format successfully.
Traceback (most recent call last):
  File "/home/z/.local/bin/mmconvert", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmconvert')()
  File "/home/z/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/home/z/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/home/z/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 144, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/home/z/.local/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/home/z/.local/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/home/z/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 132, in gen_code
    func(current_node)
  File "/home/z/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 417, in emit_Constant
    self.weights_dict[IR_node.name]['value'][0]
KeyError: u'InceptionResnetV1/Repeat_1/block17_6/mul/x'

**Comment by rainLiuplus** [comment]
Added facenet test from tf to caffe. Thanks!
