### ISSUE TITLE
error: Pytorch to IR

### ISSUE THREAD

**Issue by oyrq** [Microsoft/MMdnn#563]
run: mmtoir -f pytorch --inputShape 3,112,112 -n insightface.pth -o ./
Traceback (most recent call last):
  File "/usr/local/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(args.network, inputshape[0])
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 83, in __init__
    self.pytorch_graph.build(self.input_shape)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 122, in build
    trace, output = torch.jit.get_trace_graph(self.model, (dummy_input, ))
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 105, in set_training
    yield
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 122, in build
    trace, output = torch.jit.get_trace_graph(self.model, (dummy_input, ))
  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 196, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 251, in forward
    out = self.inner(*trace_inputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/iiai/oyrq/models/face_gender/face_gender_pytorch/net_arcface.py", line 140, in forward
    x = self.input_layer(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

Thanks!

**Comment by rainLiuplus** [comment]
Hi @oyrq , could you please provide your model for us to debug? Thanks!

**Comment by oyrq** [comment]
> Hi @oyrq , could you please provide your model for us to debug? Thanks!
Thanks! I think I have solved this problem,and I'm sorry, I have no authority to provide model for you.
but I meet a new problem when I uninstall torch-1.0.0 and install torch-0.4.0
There are error:
/usr/local/lib/python3.5/dist-packages/torch/serialization.py:367: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/usr/local/lib/python3.5/dist-packages/torch/serialization.py:367: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 74, in __init__
    model = torch.load(model_file_name)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
AttributeError: Can't get attribute '_rebuild_parameter' on <module 'torch._utils' from '/usr/local/lib/python3.5/dist-packages/torch/_utils.py'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(args.network, inputshape[0])
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 76, in __init__
    model = torch.load(model_file_name, map_location='cpu')
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
AttributeError: Can't get attribute '_rebuild_parameter' on <module 'torch._utils' from '/usr/local/lib/python3.5/dist-packages/torch/_utils.py'>

Thanks!

**Comment by Slayerxxx** [comment]
I got the similar Error:
File "f:\anacoda\anaconda3\lib\site-packages\torch\serialization.py", line 469, in _load
result = unpickler.load()
**AttributeError:** Can't get attribute 'TwoLayerFC' on <module '__main__' from 'F:\\Anacoda\\Anaconda3\\Scripts\\mmtoir.exe\\__main__.py'>

my model is defined as this:
class TwoLayerFC(torch.nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        print("initializing TLN....")
        super().__init__()
        self.linear1 = torch.nn.Linear(input_size, hidden_size)
        self.linear2 = torch.nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred
model = TwoLayerFC(D_in, H, D_out)
#after training:
torch.save(model, "FCNN.pth")
#cmd:mmtoir -f pytorch -d FCNN --inputShape 1,154 -n FCNN.pth

HELP@_@
