### ISSUE TITLE
error: Caffe to Tensorflow

### ISSUE THREAD

**Issue by SmokerX** [Microsoft/MMdnn#566]
Platform (like ubuntu 16.04/win10): win10

Python version:3.6.5

Source framework with version (like Tensorflow 1.4.1 with GPU):Caffe

Destination framework with version (like CNTK 2.3 with GPU):Tensorflow 1.11.0

Pre-trained model path (webpath or webdisk path):

Running scripts:
```
mmdownload -f caffe -n resnet152 -o ./
mmconvert -sf caffe -iw resnet152.caffemodel -in resnet152-deploy.prototxt -df tensorflow -om resnet
```
first error：
```
Traceback (most recent call last):
  File "D:\Language\Anaconda3\Scripts\mmconvert-script.py", line 11, in <module>
    load_entry_point('mmdnn', 'console_scripts', 'mmconvert')()
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\_script\convertToIR.py", line 16, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", inputshape[0], phase = args.caffePhase)
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\caffe\transformer.py", line 309, in __init__
    model = get_caffe_resolver().NetParameter()
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\caffe\resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\caffe\resolver.py", line 8, in __init__
    self.import_caffe()
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\caffe\resolver.py", line 14, in import_caffe
    import caffe
ModuleNotFoundError: No module named 'caffe'
```
second error:
```
------------------------------------------------------------
    WARNING: PyCaffe not found!
    Falling back to a pure protocol buffer implementation.
    * Conversions will be drastically slower.
    * This backend is UNTESTED!
------------------------------------------------------------

Traceback (most recent call last):
  File "D:\Language\Anaconda3\Scripts\mmconvert-script.py", line 11, in <module>
    load_entry_point('mmdnn', 'console_scripts', 'mmconvert')()
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\_script\convertToIR.py", line 16, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", inputshape[0], phase = args.caffePhase)
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\caffe\transformer.py", line 325, in __init__
    BatchNormPreprocessor() # Pre-process batch normalization data
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\caffe\graph.py", line 283, in transformed
    graph = transformer(graph)
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\caffe\transformer.py", line 82, in __call__
    node.data = self.adjust_parameters(node, data)
  File "e:\workspace\gitporject\mmdnn\mmdnn\conversion\caffe\transformer.py", line 75, in adjust_parameters
    data[idx] = np.squeeze(data[idx])
IndexError: list index out of range
```

**Comment by MinhHuuNguyen** [comment]
Same first error while convert caffe to keras

**Comment by MinhHuuNguyen** [comment]
> > Same first error while convert caffe to keras
> 
> #567

I've read but I don't understand, Please tell me what I should do

**Comment by MinhHuuNguyen** [comment]
> > Same first error while convert caffe to keras
> 
> #567

Tks, bro. I can run the code but I got another Error
Traceback (most recent call last):
  File "/home/daby/venv1/bin/mmconvert", line 10, in <module>
    sys.exit(_main())
  File "/home/daby/venv1/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "/home/daby/venv1/lib/python3.6/site-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "/home/daby/venv1/lib/python3.6/site-packages/mmdnn/conversion/keras/saver.py", line 2, in save_model
    model = MainModel.KitModel(weight_filepath)
  File "77cdab28ab934526ad05e4a7c8f2ad82.py", line 623, in KitModel
    set_layer_weights(model, weights_dict)
  File "77cdab28ab934526ad05e4a7c8f2ad82.py", line 45, in set_layer_weights
    model.get_layer(layer.name).set_weights(current_layer_parameters)
  File "/home/daby/venv1/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1057, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (64,) not compatible with provided weight shape (1, 1, 1, 64)

Please help me

**Comment by SmokerX** [comment]
if you just need caffe to tensorflow,you can use 
```
pip install -U git+https://github.com/SmokerX/MMdnn.git@skydata
```

**Comment by patrickhulce** [comment]
@SmokerX you are the best thank you! 

FYI other visitors from Google search, as of writing this still hasn't been released in a new version though the PR has been merged. I just manually applied the patch from #567 locally to get things working.
