### ISSUE TITLE
error: Inception_v3 tensorflow to pytorch

### ISSUE THREAD

**Issue by AlexDenis** [Microsoft/MMdnn#569]
Platform (like ubuntu 16.04/win10):
Ubuntu 16.04

Python version:
Python 3.6.6

Source framework with version (like Tensorflow 1.4.1 with GPU):
Tensorflow 1.10.0

Destination framework with version (like CNTK 2.3 with GPU):
PyTorch 1.0

Pre-trained model path (webpath or webdisk path):
https://drive.google.com/drive/folders/0B8N1oYmGLVGWemZQd3JMOEZvdGs

Running scripts:
`mmconvert -sf tensorflow -in checkpoint-14999.meta -iw checkpoint-14999 --dstNode InceptionV3/logits/flatten/Reshape -df pytorch -om tf_to_pytorch_inception_v3.pt`

I get the following error:

```
Tensorflow model file [checkpoint-14999.meta] loaded successfully.
Tensorflow checkpoint file [checkpoint-14999] loaded successfully. [572] variables loaded.
Tensorflow has not supported operator [Reciprocal] with name [InceptionV3/InceptionV3/Conv2d_1a_3x3/BatchNorm/moments/normalize/divisor].
Tensorflow has not supported operator [Reciprocal] with name [InceptionV3/InceptionV3/Conv2d_2a_3x3/BatchNorm/moments/normalize/divisor].
Tensorflow has not supported operator [Reciprocal] with name [InceptionV3/InceptionV3/Conv2d_2b_3x3/BatchNorm/moments/normalize/divisor].
...
Tensorflow has not supported operator [Sum] with name [InceptionV3/InceptionV3/Mixed_7c/Branch_2/Conv2d_0c_1x3/BatchNorm/moments/sufficient_statistics/mean_ss].
Tensorflow has not supported operator [Sum] with name [InceptionV3/InceptionV3/Mixed_7c/Branch_2/Conv2d_0c_1x3/BatchNorm/moments/sufficient_statistics/var_ss].
Tensorflow has not supported operator [Sum] with name [InceptionV3/InceptionV3/Mixed_7c/Branch_2/Conv2d_0d_3x1/BatchNorm/moments/sufficient_statistics/mean_ss].
Tensorflow has not supported operator [Sum] with name [InceptionV3/InceptionV3/Mixed_7c/Branch_2/Conv2d_0d_3x1/BatchNorm/moments/sufficient_statistics/var_ss].
IR network structure is saved as [b610bae15aeb483a9068438761d9f6c1.json].
IR network structure is saved as [b610bae15aeb483a9068438761d9f6c1.pb].
IR weights are saved as [b610bae15aeb483a9068438761d9f6c1.npy].
Parse file [b610bae15aeb483a9068438761d9f6c1.pb] with binary format successfully.
Warning: Graph Construct a self-loop node InceptionV3/InceptionV3/Conv2d_1a_3x3/BatchNorm/moments/StopGradient. Ignored.
Warning: Graph Construct a self-loop node InceptionV3/InceptionV3/Conv2d_1a_3x3/BatchNorm/moments/StopGradient. Ignored.
Warning: Graph Construct a self-loop node InceptionV3/InceptionV3/Conv2d_1a_3x3/BatchNorm/moments/sufficient_statistics/mean_ss. Ignored.
...
Warning: Graph Construct a self-loop node InceptionV3/InceptionV3/Mixed_7c/Branch_2/Conv2d_0d_3x1/BatchNorm/moments/normalize/divisor. Ignored.
Warning: Graph Construct a self-loop node InceptionV3/InceptionV3/Mixed_7c/Branch_2/Conv2d_0d_3x1/BatchNorm/moments/sufficient_statistics/var_ss. Ignored.
Warning: Graph Construct a self-loop node InceptionV3/InceptionV3/Mixed_7c/Branch_2/Conv2d_0d_3x1/BatchNorm/moments/normalize/divisor. Ignored.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_emitter.py", line 44, in run
    super(PytorchEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_emitter.py", line 95, in gen_code
    line = func(current_node)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_emitter.py", line 318, in emit_Reshape
    self.IR_graph.get_node(IR_node.in_edges[0]).real_variable_name,
IndexError: list index out of range
```

Can't find out the reason why this is happening, but I presume that this is because I couldn't manage to input an actual output node in `--dstNode`. I would appreciate your advice a lot and thank you for giving such an amazing opportunity!

**Comment by AlexDenis** [comment]
However, I'm not sure about the `--iw` parameter as well. In Tensorflow guide it says 

> -iw is used to specify the ".ckpt" file,
but I only had the checkpoint-14999.data-00000-of-00001 file, so I used this one instead.

**Comment by AlexDenis** [comment]
It seems that the right `--dst` in this case was `output/weights`. I'm gonna check the resulting `.pth`-file and close the issue if everything is alright.

**Comment by rainLiuplus** [comment]
Hi @AlexDenis , please refer to https://github.com/Microsoft/MMdnn/issues/492.

**Comment by AlexDenis** [comment]
@rainLiuplus Thanks for your reply, I already understood what's going on with `.ckpt` and storing tf models, but I still have an which I described in my recent message. Any idea what might be off?

**Comment by rainLiuplus** [comment]
@AlexDenis  Probably due to tensorflow parser does not support [Reciprocal] and [Sum] operator. Maybe you can help us add these two ops and then your model can be successfully converted. [This](https://github.com/Microsoft/MMdnn/wiki/Contribution-Guideline) shows how to add ops.  By the way, you can directly visualize the meta file by using `mmvismeta your_model.meta your_log_path`, which may help you find the output node. Thanks!
