### ISSUE TITLE
Pytorch to IR :Error: No module named 'networks'

### ISSUE THREAD

**Issue by luqinghit** [Microsoft/MMdnn#572]
Platform (like ubuntu 16.04/win10):
win10
Python version:
3.6
Source framework with version (like Tensorflow 1.4.1 with GPU):
gpu
Destination framework with version (like CNTK 2.3 with GPU):
cpu
Pre-trained model path (webpath or webdisk path):

Running scripts:
(base) D:\building_extract2> mmtoir -f pytorch -d DenseLinkNet --inputShape 3,640,640 -n 50.pkl
Traceback (most recent call last):
  File "e:\anaconda3\lib\site-packages\mmdnn\conversion\pytorch\pytorch_parser.py", line 76, in __init__
    model = torch.load(model_file_name)
  File "e:\anaconda3\lib\site-packages\torch\serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "e:\anaconda3\lib\site-packages\torch\serialization.py", line 469, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'networks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\Scripts\mmtoir.exe\__main__.py", line 9, in <module>
  File "e:\anaconda3\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "e:\anaconda3\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 92, in _convert
    parser = PytorchParser(model, inputshape[0])
  File "e:\anaconda3\lib\site-packages\mmdnn\conversion\pytorch\pytorch_parser.py", line 78, in __init__
    model = torch.load(model_file_name, map_location='cpu')
  File "e:\anaconda3\lib\site-packages\torch\serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "e:\anaconda3\lib\site-packages\torch\serialization.py", line 469, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'networks'

**Comment by rainLiuplus** [comment]
Hi @luqinghit , please refer to https://github.com/facebookresearch/InferSent/issues/11. Thanks!
