### ISSUE TITLE
Caffe to Keras: Layer weight shape (64,) not compatible with provided weight shape (1, 1, 1, 64)

### ISSUE THREAD

**Issue by MinhHuuNguyen** [Microsoft/MMdnn#574]
Platform (like ubuntu 16.04/win10): ubuntu 16.04

Python version: Python 3.6.8

Source framework with version (like Tensorflow 1.4.1 with GPU): Caffe

Destination framework with version (like CNTK 2.3 with GPU): Keras

Pre-trained model path (webpath or webdisk path): ResNet-152 downloaded from mmdownload -f caffe -n resnet152 -o ./

Running scripts:
mmconvert -sf caffe -in resnet152-deploy.prototxt -iw resnet152.caffemodel -df keras -om caffe_resnet152.h5

Error:
Traceback (most recent call last):
  File "/home/daby/venv1/bin/mmconvert", line 10, in <module>
    sys.exit(_main())
  File "/home/daby/venv1/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "/home/daby/venv1/lib/python3.6/site-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "/home/daby/venv1/lib/python3.6/site-packages/mmdnn/conversion/keras/saver.py", line 2, in save_model
    model = MainModel.KitModel(weight_filepath)
  File "77cdab28ab934526ad05e4a7c8f2ad82.py", line 623, in KitModel
    set_layer_weights(model, weights_dict)
  File "77cdab28ab934526ad05e4a7c8f2ad82.py", line 45, in set_layer_weights
    model.get_layer(layer.name).set_weights(current_layer_parameters)
  File "/home/daby/venv1/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1057, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (64,) not compatible with provided weight shape (1, 1, 1, 64)

**Comment by rainLiuplus** [comment]
Hi @MinhHuuNguyen , have you use the lasted released mmdnn?  I tried and it worked. Thanks!
`mmconvert -sf caffe -in resnet152-deploy.prototxt -iw resnet152.caffemodel --inputShape 3,224,224 -df keras -om caffe_resnet152.h5`

**Comment by MinhHuuNguyen** [comment]
> Hi @MinhHuuNguyen , have you use the lasted released mmdnn? I tried and it worked. Thanks!
> `mmconvert -sf caffe -in resnet152-deploy.prototxt -iw resnet152.caffemodel --inputShape 3,224,224 -df keras -om caffe_resnet152.h5`

still error! Please help me

**Comment by rainLiuplus** [comment]
@MinhHuuNguyen , I use the latest mmdnn-0.2.4 and the model can be successfully converted. Maybe you can use it to have a try, thanks!
