### ISSUE TITLE
[Help] Errors occur when I convert my tensorflow model to pytorch one   

### ISSUE THREAD

**Issue by Raise-me-up** [Microsoft/MMdnn#605]
Platform (like ubuntu 16.04/win10):
win10

Python version:
Python 3.6.1

Source framework with version (like Tensorflow 1.4.1 with GPU):
Tensorflow 1.12.0 with CPU

Destination framework with version (like CNTK 2.3 with GPU):
torch 0.4.1 

Pre-trained model path (webpath or webdisk path):
链接: https://pan.baidu.com/s/1dR_RgP8ICxhR-1jWZcbacg      提取码: 6s5j 

Running scripts:
mmconvert -sf tensorflow -in N4-SNR15-model-78000.meta -iw N4-SNR15-model-78000 --dstNodeName loss/cost -df pytorch -om N4-SNR15-model-78000.pkl

**Comment by Raise-me-up** [comment]
Error messages:
Traceback (most recent call last):
  File "e:\anaconda\installation\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda\installation\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\installation\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
  File "e:\anaconda\installation\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "e:\anaconda\installation\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "e:\anaconda\installation\lib\site-packages\mmdnn\conversion\common\DataStructure\parser.py", line 22, in run
    self.gen_IR()
  File "e:\anaconda\installation\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_parser.py", line 420, in gen_IR
    func(current_node)
  File "e:\anaconda\installation\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_parser.py", line 515, in rename_Placeholder
    IR_node.attr['shape'].shape.dim[0].size = -1
IndexError: list index out of range
