### ISSUE TITLE
pytorch to IR error??

### ISSUE THREAD

**Issue by lunalulu** [Microsoft/MMdnn#608]
Platform (like ubuntu 16.04/win10):
Ubuntu 16.04.6 LTS
Python version:
2.7
Source framework with version (like Tensorflow 1.4.1 with GPU):
1.13.1with GPU
Destination framework with version (like CNTK 2.3 with GPU):

pytorch verson: 1.0.1.post2

Pre-trained model path (webpath or webdisk path):
mmdownload -f pytorch -n resnet101 -o ./
Running scripts:
mmtoir -f pytorch -d resnet101 --inputShape 3,224,224 -n imagenet_resnet101.pth

mmdnn setup: pip install -U git+https://github.com/Microsoft/MMdnn.git@master

 mmtoir -f pytorch -d resnet101 --inputShape 3,224,224 -n imagenet_resnet101.pth
Traceback (most recent call last):
  File "/home/luna/.local/bin/mmtoir", line 10, in <module>
    sys.exit(_main())
  File "/home/luna/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/luna/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(model, inputshape[0])
  File "/home/luna/.local/lib/python2.7/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 85, in __init__
    self.pytorch_graph.build(self.input_shape)
  File "/home/luna/.local/lib/python2.7/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 124, in build
    trace.set_graph(PytorchGraph._optimize_graph(trace.graph(), False))
  File "/home/luna/.local/lib/python2.7/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 74, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, aten)
TypeError: _jit_pass_onnx(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: torch._C._onnx.OperatorExportTypes) -> torch::jit::Graph

**Comment by lunalulu** [comment]
iI lowered the pytorch version to 0.4.0,so when i try convert pytorch to IR, error report below
`luna@007:~/mmdnn$ mmdownload -f pytorch -n resnet18 -o ./
PyTorch pretrained model is saved as [./imagenet_resnet18.pth].
luna@007:~/mmdnn$ mmtoir -f pytorch -d resnet18 --inputShape 3,224,224 -n imagenet_resnet18.pth
/usr/local/lib/python2.7/dist-packages/torch/onnx/utils.py:365: UserWarning: ONNX export failed on ATen operator adaptive_avg_pool2d because torch.onnx.symbolic.adaptive_avg_pool2d does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "/home/luna/.local/bin/mmtoir", line 10, in <module>
    sys.exit(_main())
  File "/home/luna/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/luna/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/home/luna/.local/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/luna/.local/lib/python2.7/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 95, in gen_IR
    node_type = PytorchParser.layer_map[onnx_node_type]
KeyError: u'aten::adaptive_avg_pool2d'
`
thanks

**Comment by HongChow** [comment]
@rainLiuplus  could mmdnn support dynamic nodes now?

**Comment by rainLiuplus** [comment]
@HongChow , does not support.

**Comment by lunalulu** [comment]
@rainLiuplus Is there any progress？

**Comment by rainLiuplus** [comment]
Actually I can not reproduce this bug in local. But maybe you can change the versions of your packages to [this](https://github.com/Microsoft/MMdnn/blob/master/requirements/linux-py2.txt) to have a try. Thanks!

**Comment by lunalulu** [comment]
@rainLiuplus OK， thanks！

**Comment by rainLiuplus** [comment]
@lunalulu, please use torchvision 0.2.1, then it will work. Thanks!

**Comment by lunalulu** [comment]
@rainLiuplus I follow this file “ MMdnn/requirements/linux-py3.txt ” to install
`six==1.10.0
numpy==1.14.5
protobuf==3.6.1
pillow == 5.2.0
setuptools==39.1.0
http://download.pytorch.org/whl/cpu/torch-0.4.0-cp35-cp35m-linux_x86_64.whl
torchvision==0.2.1
onnx==1.2.1
onnx-tf==1.1.2`

but i get the error:
pkg_resources.DistributionNotFound: The 'numpy>=1.15.0' distribution was not found and is required by mmdnn

There seems to be something wrong with this file "MMdnn/requirements/linux-py3.txt"

**Comment by linmajia** [comment]
@lunalulu , linux-py3.txt is for our testing purpose and the specified numpy version is inconsistent with the requirement of MMdnn setup.py. We will fix it soon. Please use the following command to update numpy:
```bash
python3 -m pip install numpy==1.15.0
```

**Comment by lunalulu** [comment]
@linmajia i install the right version numpy and torchvision 0.2.1，but the error still here

> virtualEnv) luna@007:~/virtualEnv/mmdnn$ mmtoir -f pytorch -d resnet101 --inputShape 3,224,224 -n imagenet_resnet101.pth
/home/luna/virtualEnv/lib/python3.5/site-packages/torch/serialization.py:367: SourceChangeWarning: source code of class 'torchvision.models.resnet.ResNet' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/luna/virtualEnv/lib/python3.5/site-packages/torch/serialization.py:367: SourceChangeWarning: source code of class 'torchvision.models.resnet.Bottleneck' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/luna/virtualEnv/lib/python3.5/site-packages/torch/onnx/utils.py:365: UserWarning: ONNX export failed on ATen operator adaptive_avg_pool2d because torch.onnx.symbolic.adaptive_avg_pool2d does not exist
  .format(op_name, op_name))
Traceback (most recent call last):
  File "/home/luna/virtualEnv/bin/mmtoir", line 9, in <module>
    load_entry_point('mmdnn==0.2.4', 'console_scripts', 'mmtoir')()
  File "/home/luna/virtualEnv/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/luna/virtualEnv/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/home/luna/virtualEnv/lib/python3.5/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/luna/virtualEnv/lib/python3.5/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 95, in gen_IR
    node_type = PytorchParser.layer_map[onnx_node_type]
KeyError: 'aten::adaptive_avg_pool2d'

It should be noted that I did not install caffe in this environment

**Comment by linmajia** [comment]
@lunalulu , I think you are using newer version of resnet101 model. Please use mmdownload to re-download it after torchvision 0.2.1 is installed.

**Comment by lunalulu** [comment]
@linmajia it works now!
I would like to know whether I can successfully convert the resnet18 modified by using the 0.4.1 version of pytorch?

**Comment by linmajia** [comment]
@lunalulu , we only support PyTorch 0.4.0 right now and I'm afraid that using 0.4.1 will fail to convert.

**Comment by lunalulu** [comment]
@linmajia ok, thanks very much!
Looking forward to the new version!

**Comment by huanyuan54** [comment]
I have encountered the same problem. Have you solved it？

**Comment by SnowRipple** [comment]
The same here:

 File "/home/snow_ripple/workspace/012_mmdnn/mmdnn/conversion/pytorch/pytorch_graph.py", line 74, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, aten)
TypeError: _jit_pass_onnx(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: torch._C._onnx.OperatorExportTypes) -> torch::jit::Graph
