### ISSUE TITLE
Problem in converting ssd inception model from mxnet to IR.

### ISSUE THREAD

**Issue by pokerface1o1** [Microsoft/MMdnn#62]
Platform (like ubuntu 16.04):

Python version: 2.7.12

Source framework with version: MXNET 1.0.0 with GPU

Destination framework with version: Tensorflow 1.4.1 with GPU 

I was able to convert InceptionV3 (mxnet) to IR but I encounter a problem when I try to convert ssd InceptionV3  model(mxnet).

Running scripts: 
`root@2f2520263ec5:/home/bomo/Desktop# python -m mmdnn.conversion._script.convertToIR -f mxnet -n ssd_inceptionv3_512-symbol.json -d ssd_inceptionv3_512 --inputShape 3 512 512`

error:
`[14:37:20] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.12.0. Attempting to upgrade...
[14:37:20] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
/mxnet/python/mxnet/module/base_module.py:53: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	data
	label
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator null with name label.
Warning: convert the null operator with name [label] into input layer.
[14:37:20] /mxnet/dmlc-core/include/dmlc/./logging.h:308: **[14:37:20] src/c_api/c_api_symbolic.cc:417: InferShapeKeyword argument name data not found.
Candidate arguments:
	[0]label**`
`infer_shape error. Arguments:
  data: (1, 3, 512, 512)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 159, in <module>
    _main()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 154, in _main
    ret = _convert(args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 95, in _convert
    parser.gen_IR()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 269, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 388, in rename_UNKNOWN
    self.set_output_shape(source_node, IR_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 285, in set_output_shape
    arg_shape, output_shape, aux_shape = sym.infer_shape(data = self.data_shape)
  File "/mxnet/python/mxnet/symbol/symbol.py", line 965, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/mxnet/python/mxnet/symbol/symbol.py", line 1095, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/mxnet/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
**mxnet.base.MXNetError: [14:37:20] src/c_api/c_api_symbolic.cc:417: InferShapeKeyword argument name data not found.
Candidate arguments:
	[0]label**`

**Comment by kitstar** [comment]
Hi @pokerface1o1 , could you provide the model path?

**Comment by pokerface1o1** [comment]
I get the same error when I try with both network and weights. Both the file are in the same directory from which I run the code.

**Comment by kitstar** [comment]
er... I mean, could you share your model for us to testing?

**Comment by pokerface1o1** [comment]
It contains both the symbol and weights file: [ssd_inception_512](https://drive.google.com/file/d/1HdUt5v-WrPYHqbvt1-vqAQWCAH_i2fWZ/view?usp=sharing)

**Comment by kitstar** [comment]
I will try it and ping you if there is any progress. Thanks.

**Comment by SBZed** [comment]
@pokerface1o1 Were you able to resolve your issue? I am facing same problem.
@kitstar Is there any modifications related to object detection model support?

Thanks in advance.

**Comment by rohit167** [comment]
@pokerface1o1 @SBZed @kitstar 
Hello, were you able to solve this issue?

I have trained a custom yolo3 darknet-53 (using gluon-cv mxnet)
I need to convert the model to tensorflow for final inference.

I am facing the same issue while converting yolo3_darknet-53 mxnet model to IR.

`
ai-mxnet/lib/python3.6/site-packages/mxnet/module/base_module.py:55: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
        data
        _defaultpreprocess0_init_mean
        _defaultpreprocess0_init_scale
        yolov30_yolooutputv30_offset_0
        yolov30_yolooutputv30_anchor_0
        yolov30_yolooutputv31_offset_1
        yolov30_yolooutputv31_anchor_1
        yolov30_yolooutputv32_offset_2
        yolov30_yolooutputv32_anchor_2
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator null with name _defaultpreprocess0_init_scale.
Warning: convert the null operator with name [_defaultpreprocess0_init_scale] into input layer.
infer_shape error. Arguments:
  data: (1, 3, 608, 608)
...
call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:49:07] src/c_api/c_api_symbolic.cc:540: InferShapeKeyword argument name data not found.
Candidate arguments:
        [0]_defaultpreprocess0_init_scale
`

Thanks!
