### ISSUE TITLE
mxnet to tensroflow

### ISSUE THREAD

**Issue by WSCZou** [Microsoft/MMdnn#624]
mmdownload -f mxnet
mmdownload -f mxnet -n squeezenet_v1.0 -o ./
mmconvert -sf mxnet -in squeezenet_v1.0-symbol.json -iw squeezenet_v1.0-0000.params -df tensorflow -om resnet

output:
d:\anaconda3\lib\site-packages\mxnet\module\base_module.py:54: UserWarning: [91mYou created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
        data
        prob_label[0m
  warnings.warn(msg)
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
  File "d:\anaconda3\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "d:\anaconda3\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 80, in _convert
    parser = MXNetParser(model)
  File "d:\anaconda3\lib\site-packages\mmdnn\conversion\mxnet\mxnet_parser.py", line 242, in __init__
    assert isinstance(input_arg[3], list)
AssertionError

**Comment by SBZed** [comment]
@WSCZou Why did you close this issue? Did you find the solution? I'm having the same problem, can you tell me what you did?

Thanks in advance.

**Comment by WSCZou** [comment]
@SBZed  I give up using this to convert.I have found the model version I want to use. sorry can't help you.
