### ISSUE TITLE
Can't predict with converted model (Tensorflow -> MxNet)

### ISSUE THREAD

**Issue by tung1404** [Microsoft/MMdnn#63]
I was install MMdnn by
pip install -U git+https://github.com/Microsoft/MMdnn.git@master

pip list:
mxnet (0.11.0)
tensorflow (1.4.0)

I have model is trained by Tensorflow, based on Inception V3.
After convert Tensorflow to IR and convert IR to MXNET, But I can't predict image with converted model.

``
def predict(model, filename):
    print filename
    array = loadImage(filename)
    Batch = namedtuple('Batch', ['data'])
    mod.forward(Batch([array]), is_train=True)
    pred = mod.get_outputs()[0].asnumpy()
    return pred

def loadModel():
    inception_v3, arg_params, aux_params = mx.model.load_checkpoint("inception_v3", 0)
    mod = mx.mod.Module(symbol=inception_v3, data_names=('input',))
    mod.bind(for_training=False, data_shapes=[('input', (1,3,299,299))])
    mod.set_params(arg_params, aux_params)
    return mod
``

The below is error log
_Traceback (most recent call last):
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/workspace/01_acr/test_converted_model.py", line 42, in <module>
    print predict(mod, file)
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/workspace/01_acr/test_converted_model.py", line 20, in predict
    mod.forward(Batch([array]), is_train=True)
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/lib/python2.7/site-packages/mxnet/module/module.py", line 594, in forward
    self.reshape(new_dshape, new_lshape)
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/lib/python2.7/site-packages/mxnet/module/module.py", line 459, in reshape
    self._exec_group.reshape(self._data_shapes, self._label_shapes)
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 348, in reshape
    self.bind_exec(data_shapes, label_shapes, reshape=True)
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 324, in bind_exec
    allow_up_sizing=True, **dict(data_shapes_i + label_shapes_i))
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/lib/python2.7/site-packages/mxnet/executor.py", line 399, in reshape
    arg_shapes, _, aux_shapes = self._symbol.infer_shape(**kwargs)
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/lib/python2.7/site-packages/mxnet/symbol.py", line 978, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/lib/python2.7/site-packages/mxnet/symbol.py", line 1107, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/Users/tung1404/Downloads/_pc_vision/sample_mxnet/lib/python2.7/site-packages/mxnet/base.py", line 129, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator InceptionV3/InceptionV3/Conv2d_2a_3x3/Conv2D: [17:49:38] src/operator/./convolution-inl.h:463: Check failed: dilated_ksize_x <= AddPad(dshape[3], param_.pad[1]) (3 vs. 1) kernel size exceed input_

**Comment by kitstar** [comment]
Hi @tung1404 , could you share the model files for testing? Thanks.

**Comment by tung1404** [comment]
After converted, I have 3 files:
- inception_v3-0000.params
- inception_v3-symbol.json
- mxnet_inception_v3.py

In previous post, I'm used `mx.model.load_checkpoint("inception_v3", 0)` for load model.
Are you mention `mxnet_inception_v3.py`?

**Comment by kitstar** [comment]
Could you provide the files for us to reproduce your job with google drive or onedrive?
