### ISSUE TITLE
LSTM support for MXNet Emitter

### ISSUE THREAD

**Issue by sharmalakshay93** [Microsoft/MMdnn#634]
I'm trying to convert a Keras model with some LSTM layers to an MXNet equivalent by running the command `mmconvert -sf keras -iw audio_model.h5 -df mxnet -om keras_to_mxnet_mmdnn.dnn
`; the python script containing `RefactorModel` (and some other files) appear to be created fine, but the following exception is being thrown (contains a few extra lines that I logged out):

```
MXNet Emitter has not supported operator [LSTM].
lstm_22
type(IR_node): <class 'mmdnn.conversion.common.IR.IR_graph.IRGraphNode'>
IR_node.variable_name:  lstm_22_activation
Target network code snippet is saved as [db1ec0b5e7ac46e2815e951b4076dff9.py].
Traceback (most recent call last):
  File "/Users/slakshay/anaconda3/bin/mmconvert", line 10, in <module>
    sys.exit(_main())
  File "/Users/slakshay/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "/Users/slakshay/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "/Users/slakshay/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/mxnet/saver.py", line 2, in save_model
    model = MainModel.RefactorModel()
  File "db1ec0b5e7ac46e2815e951b4076dff9.py", line 10, in RefactorModel
    lstm_21_activation = mx.sym.Activation(data = lstm_21, act_type = 'tanh', name = 'lstm_21_activation')
NameError: name 'lstm_21' is not defined
8c859043214c:SpeechOrNot slakshay$ which python
/usr/bin/python
8c859043214c:SpeechOrNot slakshay$ mmconvert -sf keras -iw audio_model.h5 -df mxnet -om keras_to_mxnet_mmdnn.dnnls
8c859043214c:SpeechOrNot slakshay$ ls
234f0295af0c4417bd253bcf8c127c72.json	db1ec0b5e7ac46e2815e951b4076dff9.json
234f0295af0c4417bd253bcf8c127c72.npy	db1ec0b5e7ac46e2815e951b4076dff9.npy
234f0295af0c4417bd253bcf8c127c72.pb	db1ec0b5e7ac46e2815e951b4076dff9.pb
234f0295af0c4417bd253bcf8c127c72.py	db1ec0b5e7ac46e2815e951b4076dff9.py
__pycache__				initial_model_exploration.ipynb
audio_model.h5				main[2].py
c586d950544e4cc4ad1486e58d8181d0.json	model_plot.png
c586d950544e4cc4ad1486e58d8181d0.npy	python_module.cpp
c586d950544e4cc4ad1486e58d8181d0.pb
```

Is this because LSTM is simply not supported for MXNet conversions? Or is there something that I might be doing incorrectly? Thanks!

Platform (like ubuntu 16.04/win10):
Mac OS Sierra 10.12.6

Python version: 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): Keras  

Destination framework with version (like CNTK 2.3 with GPU): MXNet

Pre-trained model path (webpath or webdisk path): locally stored and self-created

Running scripts:

**Comment by JiahaoYao** [comment]
Hi @sharmalakshay93, I think it is just because the LSTM is not supported currently for `MMdnn`.

**Comment by eloi-loomai** [comment]
When will the mmdnn team will work on that? I have a problem on my end too on that.

**Comment by rainLiuplus** [comment]
Hi @eloi-loomai, if your source is TensorFlow,  mmdnn supports it.

**Comment by eloi-loomai** [comment]
Ok, unfortunately my source is pytorch
