### ISSUE TITLE
Exception thrown: the train_val.prototxt should be provided with the input shape

### ISSUE THREAD

**Issue by chenshousehold** [Microsoft/MMdnn#640]
Hi,

I am running the docker container to do Caffe model conversion to CoreML and I received the following assert message in the terminal:

Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 9, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/caffe/transformer.py", line 315, in __init__
    raise ConversionError('the train_val.prototxt should be provided with the input shape')
mmdnn.conversion.caffe.errors.ConversionError: the train_val.prototxt should be provided with the input shape

In my network deploy.prototxt definition, instead of using the "input_shape" to define the input, it actually defines a input layer like the following

name: "GoogleNet"
layer {
  name: "data"
  type: "MemoryData"
  top: "data"
  top: "label"
  memory_data_param {
    batch_size: 1
    channels: 3
    height: 224
    width: 224
  }
  transform_param {
    crop_size: 224
    mirror: false
    mean_value: 104
    mean_value: 117
    mean_value: 123
  }
}

Is this a known issue, how can I workaround the issue? Thanks for your support.

**Comment by chenshousehold** [comment]
Found I could add --inputShape 3,224,224 to the command line to fix the issue,
