### ISSUE TITLE
Can't convert model with elu/selu activation (Tensorflow to Caffe)

### ISSUE THREAD

**Issue by 2h4dl** [Microsoft/MMdnn#644]
Platform (like ubuntu 16.04/win10): 
`
ubuntu 16.04
`
Python version:
`
 python 2.7
`
Source framework with version (like Tensorflow 1.4.1 with GPU): 
`
Tensorflow 1.12 with GPU
`
Destination framework with version (like CNTK 2.3 with GPU):
`
caffe
`
Pre-trained model path (webpath or webdisk path):

Running scripts:
```
mmconvert -sf tensorflow -in model-lenet-10000.meta -iw model-lenet-10000 --dstNodeName dense2/outputs -df caffe -om caffe-lenet
```

Error Info:
```
TensorflowEmitter has not supported operator [Selu] with name [conv1/Selu].
TensorflowEmitter has not supported operator [Selu] with name [conv2/Selu].
TensorflowEmitter has not supported operator [Selu] with name [dense1/Selu].
IR network structure is saved as [d8ec3ee1a9104b2c89bc937f38c88911.json].
IR network structure is saved as [d8ec3ee1a9104b2c89bc937f38c88911.pb].
IR weights are saved as [d8ec3ee1a9104b2c89bc937f38c88911.npy].
/usr/local/lib/python2.7/dist-packages/scipy/signal/_max_len_seq.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._max_len_seq_inner import _max_len_seq_inner
/usr/local/lib/python2.7/dist-packages/scipy/signal/_upfirdn.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._upfirdn_apply import _output_len, _apply
/usr/local/lib/python2.7/dist-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._trlib import TRLIBQuadraticSubproblem
/usr/local/lib/python2.7/dist-packages/scipy/optimize/_numdiff.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
/usr/local/lib/python2.7/dist-packages/scipy/signal/spectral.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._spectral import _lombscargle
/usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _stats
/usr/local/lib/python2.7/dist-packages/scipy/signal/_peak_finding.py:13: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._peak_finding_utils import (_argmaxima1d, _select_by_peak_distance,
Parse file [d8ec3ee1a9104b2c89bc937f38c88911.pb] with binary format successfully.
Warning: Graph Construct a self-loop node conv1/Selu. Ignored.
Warning: Graph Construct a self-loop node conv2/Selu. Ignored.
Warning: Graph Construct a self-loop node dense1/Selu. Ignored.
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 144, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 22, in run
    self.save_code(dstNetworkPath, phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 59, in save_code
    code = self.gen_code(phase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 132, in gen_code
    func(current_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 308, in emit_Pool
    pad_h, pad_w = self._get_symmetric_padding(IR_node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 160, in _get_symmetric_padding
    if IR_parent_node.type == 'Pad':
AttributeError: 'NoneType' object has no attribute 'type'
```

**Comment by JiahaoYao** [comment]
Hi @2h4dl, It seems the `TensorflowEmit` has not implemented the `selu` yet.

**Comment by 2h4dl** [comment]
> Hi @2h4dl, It seems the `TensorflowEmit` has not implemented the `selu` yet.
So will you guys support these two activation functions in next version?

**Comment by JiahaoYao** [comment]
Hi @2h4dl, Could you upload your model so that I can find how to fix it?

**Comment by 2h4dl** [comment]
@JiahaoYao https://drive.google.com/file/d/1WhVog1OhD07g3xMT9uXz3Y77v1N_WqmZ/view?usp=sharing, this is a simple model.

**Comment by JiahaoYao** [comment]
Hi @2h4dl, I look into the caffe api. I do not think they have the official `selu`. What I can only is others' implement: [https://github.com/HolmesShuan/SNNs-Self-Normalizing-Neural-Networks-Caffe-Reimplementation](https://github.com/HolmesShuan/SNNs-Self-Normalizing-Neural-Networks-Caffe-Reimplementation).  

Another approach is to use [combine elu and scale to get selu](https://github.com/HolmesShuan/SNNs-Self-Normalizing-Neural-Networks-Caffe-Reimplementation/issues/3). I can set the alpha to elu. 
```
n.elu = L.ELU(n.fc, in_place=True)
n.scale = L.Scale(n.elu, bias_term=False, in_place=True)
```

Then, the question reduced to how to set ` ELU (with alpha=1.6732) + Scale (freezed, with param=1.0507)`?
like here: https://github.com/bioinf-jku/SNNs/blob/master/selu.py#L24-L25

**Comment by 2h4dl** [comment]
Hi @JiahaoYao. May be it's a good way to implement selu. Thx your kindness.
