### ISSUE TITLE
MXnet to IR NotImplementedError 

### ISSUE THREAD

**Issue by CarlosE97** [microsoft/MMdnn#659]
Hello @namizzz, as I've searched for this error in this repo, the issue #388 seems the closest.

This is the script I'm launching:

`mmtoir -f mxnet -n mxnet_resnet_50-symbol.json -w mxnet_resnet_50-0000.params -d resnet50 --inputShape 3 224 224`

And this is the output error I get:

> Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator Pad with name conv1_pad.
Traceback (most recent call last):
  File "/usr/local/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 184, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 102, in _convert
    parser.run(args.dstPath)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 265, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 376, in rename_UNKNOWN
    raise NotImplementedError()
NotImplementedError

Thank you

**Comment by rainLiuplus** [comment]
Hi @CarlosE97, is your model the [official model](http://data.mxnet.io.s3-website-us-west-1.amazonaws.com/models/imagenet/resnet/50-layers/resnet-50-symbol.json) of mxnet?  If so, no problems in my local testing. Maybe you can upload your model for us to debug. BTW, the correct format of inputShape is 3,224,224. Thanks!

**Comment by CarlosE97** [comment]
Hello @rainLiuplus, thank you for your reply.

I am performing a round conversion Keras -> MXnet -> Keras to check if anything will change. I used the official Keras model and the conversion to MXnet was successful, now converting MXnet to IR is not working out with this "NotImplementedError()"

I've uploaded the model architecture and the weights on WeTransfer.
Please find attached in the .zip file both the .json and the .params in the link:
https://we.tl/t-jaGbw9JAdS 


> BTW, the correct format of inputShape is 3,224,224.


I don't know why using a comma doesn't work, I guess it's about the MMdnn version, but I'm not sure, using a space never gave me an error though so this is not the problem.

Thank you

**Comment by rainLiuplus** [comment]
Hi @CarlosE97, I tested it locally using the lasted mmdnn and there is no `NotImplementedError`. Maybe you can upgrade the mmdnn and have a try. Thanks!

**Comment by CarlosE97** [comment]
Hello @rainLiuplus, thanks for the reply.

I updated the mmdnn and retried the whole process, but now it's a new error. Converting from Keras to MXnet is successful. Once I try MXnet to IR:

`mmtoir -f mxnet -n mxnet_resnet50-symbol.json -w mxnet_resnet50-0000.params -d resnet50 --inputShape 3 224 224`

 I get the following error:

> Traceback (most recent call last):
  File "/usr/local/bin/mmtoir", line 10, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 80, in _convert
    parser = MXNetParser(model)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 239, in __init__
    self.model, self.weight_data = MXNetParser._load_model(input_arg[1], input_arg[2])
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 177, in _load_model
    model = mx.mod.Module(symbol = sym)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/module.py", line 95, in __init__
    _check_input_names(symbol, data_names, "data", True)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/base_module.py", line 54, in _check_input_names
    raise ValueError(msg)
ValueError: You created Module with Module(..., data_names=['data']) but input with name 'data' is not found in symbol.list_arguments(). Did you mean one of:
        input_1
        softmax_label

Please find attached the new model and architecture in the WeTransfer link:
https://we.tl/t-lXPN5ISxjL

Thank you

**Comment by rainLiuplus** [comment]
Hi @CarlosE97, 
The new model's input data variable name is no longer the default 'data', which brings about this error.  
Thus you can change [this line](https://github.com/microsoft/MMdnn/blob/master/mmdnn/conversion/mxnet/mxnet_parser.py#L177) into 
`model = mx.mod.Module(symbol = sym, data_names=('input_1',))` 
and replace 'data' in [this line](https://github.com/microsoft/MMdnn/blob/master/mmdnn/conversion/mxnet/mxnet_parser.py#L281) with 'input_1' like 
`arg_shape, output_shape, aux_shape = sym.infer_shape(input_1 = self.data_shape)`

**Comment by CarlosE97** [comment]
Hello @rainLiuplus, Thank you for your reply. This worked out. Thanks again!
