### ISSUE TITLE
GluonCV VGG16 MXNet -> IR -> Keras 

### ISSUE THREAD

**Issue by CarlosE97** [microsoft/MMdnn#662]
Hello @namizzz @rainLiuplus, 

Going from MXnet to IR was successful. but when going from IR to Keras code snippet:
Running scripts:

`mmtocode -f keras --IRModelPath vgg16.pb --dstModelPath to_keras_vgg16.py`

was not successful:

> Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 36, in _load_weights
    self.weights_dict = np.load(file_name).item()
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 404, in load
    magic = fid.read(N)
AttributeError: 'NoneType' object has no attribute 'read'

> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
  File "/usr/local/bin/mmtocode", line 10, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 117, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/IRToCode.py", line 18, in _convert
    emitter = Keras2Emitter((args.IRModelPath, args.IRWeightPath))
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/keras/keras2_emitter.py", line 40, in __init__
    self._load_weights(weight_path)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 38, in _load_weights
    self.weights_dict = np.load(file_name, encoding='bytes').item()
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 404, in load
    magic = fid.read(N)
AttributeError: 'NoneType' object has no attribute 'read'

Is there any way to fix this? Thank you

**Comment by rainLiuplus** [comment]
Hi @CarlosE97, please add the argument '--IRWeightPath' to specify the weights file path. Thanks!

**Comment by CarlosE97** [comment]
Hello @rainLiuplus, indeed that worked out as intended. Going to the next step: 
Keras code snippet + weights -> to get the keras weights file:

`python3.5 -m mmdnn.conversion.examples.keras.imagenet_test -n mxnet_to_keras_vgg16.py -w vgg16.npy --dump to_keras_resnet50.h5`

But I get this error concerning the layers' weight shape and the weights' shape:

> Using TensorFlow backend.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-05-29 08:33:23.647692: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-05-29 08:33:23.671684: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3300000000 Hz
2019-05-29 08:33:23.673036: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x60581e0 executing computations on platform Host. Devices:
2019-05-29 08:33:23.673081: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>

> Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/examples/keras/imagenet_test.py", line 157, in <module>
    tester = TestKeras()
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/examples/keras/imagenet_test.py", line 31, in __init__
    self.model = self.MainModel.KitModel(self.args.w)
  File "mxnet_to_keras_vgg16.py", line 109, in KitModel
    set_layer_weights(model, weights_dict)
  File "mxnet_to_keras_vgg16.py", line 47, in set_layer_weights
    model.get_layer(layer.name).set_weights(current_layer_parameters)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/base_layer.py", line 1057, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (512, 4096) not compatible with provided weight shape (25088, 4096)

Thanks

**Comment by rainLiuplus** [comment]
Hi @CarlosE97, 
I have no problem testing locally, and maybe your input file does not match? I notice that the argument of -n is `mxnet_to_keras_vgg16`

**Comment by CarlosE97** [comment]
Hello @rainLiuplus, I've tried the steps again, and I'm still getting the same error about the weight shape. I'll send you my model's weights and architecture via WeTransfer:

https://we.tl/t-gJtMnf2IJu

Thank you

**Comment by JiahaoYao** [comment]
Hi @CarlosE97, 
After you got the python code snippets `mxnet_to_keras_vgg16.py`, one way is to manually add `layers.Flatten()` between the last convolution layer and first fully connected layers. 

![image](https://user-images.githubusercontent.com/20907377/59164715-cfbd7080-8ac5-11e9-8d89-b9b7d15a5bac.png)

This solves your problem because, in the mxnet graph, there is no `flatten` layer in between.
![image](https://user-images.githubusercontent.com/20907377/59164722-01363c00-8ac6-11e9-9d1c-71dc82a743b1.png)

Then, you add `flatten` layer in keras, you should have a graph like this. 
![image](https://user-images.githubusercontent.com/20907377/59164773-42c6e700-8ac6-11e9-929a-093226e7bfd3.png)

**Comment by CarlosE97** [comment]
Thank you @JiahaoYao for the explanation and for the solution. I now understand what was the matter at hand. Farewell!

**Comment by CarlosE97** [comment]
I should mention my mistake with the naming of the files, as I am working with both vgg16 and resnet50 I've mixed the names up as you can see in this script:

`python3.5 -m mmdnn.conversion.examples.keras.imagenet_test -n mxnet_to_keras_vgg16.py -w vgg16.npy --dump to_keras_resnet50.h5`

For anyone checking this issue, sorry for this inconvenience :)
