### ISSUE TITLE
UnboundLocalError: local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by moonjiaoer** [microsoft/MMdnn#671]
Platform (like ubuntu 16.04/win10):ubuntu 18.04

Python version:3.6.7

Source framework with version (like Tensorflow 1.4.1 with GPU):Tensorflow 1.13.1

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:
WARNING:tensorflow:From /home/wangyuejiao/.local/lib/python3.6/site-packages/tensorflow/python/tools/strip_unused_lib.py:86: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
Traceback (most recent call last):
  File "/media/wangyuejiao/DATA/MMdnn-master/mmdnn/conversion/_script/convert.py", line 123, in <module>
    _main()
  File "/media/wangyuejiao/DATA/MMdnn-master/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/media/wangyuejiao/DATA/MMdnn-master/mmdnn/conversion/_script/convertToIR.py", line 59, in _convert
    parser = TensorflowParser2(args.weights, inputshape, args.inNodeName, args.dstNodeName)
  File "/media/wangyuejiao/DATA/MMdnn-master/mmdnn/conversion/tensorflow/tensorflow_frozenparser.py", line 157, in __init__
    input_map[in_nodes[i] + ':0'] = x
UnboundLocalError: local variable 'x' referenced before assignment

**Comment by moonjiaoer** [comment]
@rainLiuplus 
Thx for your help,It works!
but I got new issue here:

"Tensorflow has not supported operator [IteratorFromStringHandleV2] with name [superpoint/IteratorFromStringHandleV2]. "

I thought it means the MMdnn can not support this op when convert the pb file to the caffe model.
Do you have any suggestion for this issue?
Thanks!

**Comment by rainLiuplus** [comment]
Hi @moonjiaoer 
Seems it is an operator related to data processing. But MMdnn does not support such ops for that they vary from framework to framework.  Thus just converting the network architecture may skip this issue. Thanks!

**Comment by moonjiaoer** [comment]
Hi @rainLiuplus 
Thx for your reply.
but I don't know how to skip this op?
Do you mean I can modify the MMdnn code?
Or I need to generate a new pb without this op?

**Comment by rainLiuplus** [comment]
@moonjiaoer,
just skip them via specifying input and output names like ` --inNodeName your_input  --dstNodeName your_dst`

**Comment by moonjiaoer** [comment]
/home/wangyuejiao/图片/2019-06-04 19-16-55 的屏幕截图.png
Hi I tried your method it's good but still can't solve my issue.
the figure I uploaded is part of my network.
The new issue is quantification.
You can see the node which named "FakeQuantWithMinMaxVars" that's the new problem.
This node will set in the whole network for much times I think it's hard to skip.
Could I modified the code to skip this node?

**Comment by rainLiuplus** [comment]
Hi @moonjiaoer,
could you upload this model then I can help you add this op? Thanks

**Comment by moonjiaoer** [comment]
Hi @rainLiuplus 
Thanks for your help.
could you send me your email address?
the model is nearly 78mb.

**Comment by rainLiuplus** [comment]
@moonjiaoer,
v-yucli@microsoft.com

**Comment by zxp771** [comment]
Hi @rainLiuplus 
Sorry for the late reply.
Here is the link :链接: https://pan.baidu.com/s/1B5ZOghcilm3ZywqLMcIXqg 
password(some Chinese characters like"提取码”): 84iw
BTW this is my colleague‘s account.

**Comment by rainLiuplus** [comment]
Hi @zxp771, may I ask the target framework? Thanks

**Comment by zxp771** [comment]
Hi @rainLiuplus 
This network is SuperPoint which based on tensorflow, We want to convert the tensorflow's pb file to the caffe model.

Thx for your help and patience.

**Comment by moonjiaoer** [comment]
Hi @rainLiuplus 

Sorry to disturb.
Have you tried to convert the model we sent to you?

Thx

**Comment by moonjiaoer** [comment]
Hi @rainLiuplus 

Do you have any update for this issue?

**Comment by rainLiuplus** [comment]
Hi @moonjiaoer, sorry, I am busy recently. For this issue, the key problem is that the quant op has no counterpart in Caffe. Thus to solve this issue need to register a new quant op in Caffe.   
I will add the support of this op into the work plan. Or maybe you could try to add it first? For guidance on how to add operators, please refer to [this](https://github.com/microsoft/MMdnn/wiki/Contribution-Guideline). Thanks!

**Comment by zxp771** [comment]
Hi @rainLiuplus 

Thx for your reply.
We'll try it first and hope you can bring some good news soon

Thx
