### ISSUE TITLE
Transfer from keras to caffe 【error forSeparableConv 】

### ISSUE THREAD

**Issue by zys1994** [microsoft/MMdnn#694]
Platform (like ubuntu 16.04/win10):ubuntu 16.04

Python version:python2.7.12

Source framework with version (like Tensorflow 1.4.1 with GPU):keras 2.2.4

Destination framework with version (like CNTK 2.3 with GPU):caffe

Pre-trained model path (webpath or webdisk path):

Running scripts:
mmconvert -sf keras -iw age.h5 --dstNodeName age -df caffe  -om mycaffemodel

```
Using TensorFlow backend.
2019-07-12 17:28:20.255156: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-07-12 17:28:20.361369: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: Quadro P2000 major: 6 minor: 1 memoryClockRate(GHz): 1.4805
pciBusID: 0000:65:00.0
totalMemory: 4.94GiB freeMemory: 4.28GiB
2019-07-12 17:28:20.361401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2019-07-12 17:28:20.573748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4032 MB memory) -> physical GPU (device: 0, name: Quadro P2000, pci bus id: 0000:65:00.0, compute capability: 6.1)
IR network structure is saved as [cf3c22ff6bc040c4b67fefb242b96e02.json].
IR network structure is saved as [cf3c22ff6bc040c4b67fefb242b96e02.pb].
IR weights are saved as [cf3c22ff6bc040c4b67fefb242b96e02.npy].
Parse file [cf3c22ff6bc040c4b67fefb242b96e02.pb] with binary format successfully.
CaffeEmitter has not supported operator [SeparableConv].
separable_conv2d_1
CaffeEmitter has not supported operator [SeparableConv].
separable_conv2d_2
CaffeEmitter has not supported operator [SeparableConv].
separable_conv2d_3
CaffeEmitter has not supported operator [SeparableConv].
separable_conv2d_4
CaffeEmitter has not supported operator [SeparableConv].
separable_conv2d_5
CaffeEmitter has not supported operator [SeparableConv].
separable_conv2d_6
CaffeEmitter has not supported operator [SeparableConv].
separable_conv2d_7
CaffeEmitter has not supported operator [SeparableConv].
separable_conv2d_8
Target network code snippet is saved as [cf3c22ff6bc040c4b67fefb242b96e02.py].
Target weights are saved as [cf3c22ff6bc040c4b67fefb242b96e02.npy].
Traceback (most recent call last):
  File "/home/bill/.local/bin/mmconvert", line 10, in <module>
    sys.exit(_main())
  File "/home/bill/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "/home/bill/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "/home/bill/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/saver.py", line 9, in save_model
    MainModel.make_net(dump_net)
  File "cf3c22ff6bc040c4b67fefb242b96e02.py", line 100, in make_net
    n = KitModel()
  File "cf3c22ff6bc040c4b67fefb242b96e02.py", line 38, in KitModel
    n.batch_normalization_4 = L.BatchNorm(n.separable_conv2d_1, eps=0.0010000000475, use_global_stats=True, ntop=1)
  File "/home/bill/E/dl_base/caffe_program/caffe_mobilenet/python/caffe/net_spec.py", line 180, in __getattr__
    return self.tops[name]
KeyError: 'separable_conv2d_1'
```

Before I can successfully convert mxnet's depthwise conv to caffe's groupconv, how to deal with the keras's SeparableConv and transfer to caffe's groupconv. Thanks!

**Comment by AdrianEddy** [comment]
I'm facing the same issue but with PyTorch Emitter
Model I'm trying to convert is NudeNet from here: https://github.com/notAI-tech/NudeNet/
Model downloaded from: https://github.com/bedapudi6788/NudeNet/releases/download/v0/classifier_model and converted to IR using `mmtoir -f keras -w classifier_model -o nudenet-IR`
Then `mmtocode -f pytorch -n nudenet-IR.pb --IRWeightPath nudenet-IR.npy --dstModelPath nudenet-pytorch.py -dw nudenet-pytorch.npy`

Output:
```Parse file [nudenet-IR.pb] with binary format successfully.
Pytorch Emitter has not supported operator [SeparableConv].
block2_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block2_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block3_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block3_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block4_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block4_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block5_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block5_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block5_sepconv3
Pytorch Emitter has not supported operator [SeparableConv].
block6_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block6_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block6_sepconv3
Pytorch Emitter has not supported operator [SeparableConv].
block7_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block7_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block7_sepconv3
Pytorch Emitter has not supported operator [SeparableConv].
block8_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block8_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block8_sepconv3
Pytorch Emitter has not supported operator [SeparableConv].
block9_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block9_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block9_sepconv3
Pytorch Emitter has not supported operator [SeparableConv].
block10_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block10_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block10_sepconv3
Pytorch Emitter has not supported operator [SeparableConv].
block11_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block11_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block11_sepconv3
Pytorch Emitter has not supported operator [SeparableConv].
block12_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block12_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block12_sepconv3
Pytorch Emitter has not supported operator [SeparableConv].
block13_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block13_sepconv2
Pytorch Emitter has not supported operator [SeparableConv].
block14_sepconv1
Pytorch Emitter has not supported operator [SeparableConv].
block14_sepconv2
```
