### ISSUE TITLE
Dimension error: Inception V4, TensorFlow to Pytorch

### ISSUE THREAD

**Issue by Porky623** [microsoft/MMdnn#708]
Platform (like ubuntu 16.04/win10):
SMP Debian 4.9.110-1
Python version:
2.7
Source framework with version (like Tensorflow 1.4.1 with GPU):
Tensorflow 1.14.0 with GPU
Destination framework with version (like CNTK 2.3 with GPU):
PyTorch 0.3.1 with GPU
Pre-trained model path (webpath or webdisk path):
~/visualize/checkpoints/model.pb

Running scripts:
`mmconvert -sf tensorflow -in model.pb --dstNodeName InceptionV4/Logits/Predictions -df pytorch -om tf_sku_to_pth.pth`

Good output:
```
IR network structure is saved as [2201d744de3444ce989e67f5751bdd86.json].
IR network structure is saved as [2201d744de3444ce989e67f5751bdd86.pb].
IR weights are saved as [2201d744de3444ce989e67f5751bdd86.npy].
Parse file [2201d744de3444ce989e67f5751bdd86.pb] with binary format successfully.
Target network code snippet is saved as [tf_sku_to_pth.py].
Target weights are saved as [2201d744de3444ce989e67f5751bdd86.npy].
```

Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    load_entry_point('mmdnn==0.2.4', 'console_scripts', 'mmconvert')()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/pytorch/saver.py", line 5, in save_model
    model = MainModel.KitModel(weight_filepath)
  File "tf_sku_to_pth.py", line 326, in __init__
    self.InceptionV4_Logits_Logits_MatMul = self.__dense(name = 'InceptionV4/Logits/Logits/MatMul', in_features = -1, out_features = 1221, bias = True)
  File "tf_sku_to_pth.py", line 941, in __dense
    layer = nn.Linear(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/linear.py", line 46, in __init__
    self.reset_parameters()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/linear.py", line 49, in reset_parameters
    stdv = 1. / math.sqrt(self.weight.size(1))
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by rainLiuplus** [comment]
Hi @Porky623, thanks for your report. Is there a link to this pre-trained model?

**Comment by Porky623** [comment]
http://download.tensorflow.org/models/inception_v4_2016_09_09.tar.gz

**Comment by rainLiuplus** [comment]
@Porky623, I tested the model but no errors occurred.  Maybe you could upgrade pytorch version to 0.4.0 and try again. Thanks!

The script:
`mmconvert -sf tensorflow -iw model.pb --inNodeName Placeholder --dstNodeName InceptionV4/Logits/Predictions -df pytorch -om tf_sku_to_pth.pth --inputShape 299,299,3`
