### ISSUE TITLE
Misshaped biases and softmax when converting from Caffe

### ISSUE THREAD

**Issue by petko10** [microsoft/MMdnn#711]
Platform (like ubuntu 16.04/win10): Ubuntu 18.04
Python version: 3.6.8
Source framework: BVLC Caffe
Destination framework: any (IR), pytorch and onnx on caffe2 tested
[Pre-trained model path](https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet)

When converting the Caffe model to onnx and doing inference I get two errors. The first is in connection to the fact that the converted bias data has shapes like (1,1,1,64), instead of (64,1,1,1) (an omitted transposition?). The second points to the Softmax being defined as (1,1, 1000,) instead of (1, 1000) .
Here is the first error:
```
Original python traceback for operator `1` in network `mmdnn_predict` in exception above (most recent call last):
Traceback (most recent call last):
  File "./test_onnx_via_caffe2.py", line 76, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./test_onnx_via_caffe2.py", line 62, in main
    outputs = rep.run(np.array([np_img.astype(np.float32)]))
  File "/home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/onnx/backend_rep.py", line 57, in run
    self.workspace.RunNet(self.predict_net.name)
  File "/home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/onnx/workspace.py", line 63, in f
    return getattr(workspace, attr)(*args, **kwargs)
  File "/home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/workspace.py", line 250, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/workspace.py", line 211, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at conv_op_impl.h:78] bias.dim() == 1. 4 vs 1
Error from operator: 
input: "data" input: "conv1_7x7_s2_weight" input: "conv1_7x7_s2_bias" output: "conv1_7x7_s2" name: "" type: "Conv" arg { name: "strides" ints: 2 ints: 2 } arg { name: "pads" ints: 3 ints: 3 ints: 3 ints: 3 } arg { name: "kernels" ints: 7 ints: 7 } arg { name: "group" i: 1 } arg { name: "dilations" ints: 1 ints: 1 } device_option { device_type: 0 device_id: 0 }frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f7b9e0b5441 in /home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x49 (0x7f7b9e0b5259 in /home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #2: <unknown function> + 0x1bd0846 (0x7f7b36228846 in /home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #3: <unknown function> + 0x1a42bed (0x7f7b3609abed in /home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #4: <unknown function> + 0x1829345 (0x7f7b35e81345 in /home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #5: caffe2::SimpleNet::Run() + 0x161 (0x7f7b35f55101 in /home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #6: caffe2::Workspace::RunNet(std::string const&) + 0x3a (0x7f7b35f8c5aa in /home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #7: <unknown function> + 0x4e38a (0x7f7ba262d38a in /home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x9368e (0x7f7ba267268e in /home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: python() [0x4f6128]
frame #12: python() [0x4f7d60]
frame #13: python() [0x4f876d]
frame #15: python() [0x4f6128]
frame #16: python() [0x56fe24]
frame #19: python() [0x4f6128]
frame #20: python() [0x4f7d60]
frame #21: python() [0x4f876d]
frame #23: python() [0x4f6128]
frame #24: python() [0x4f7d60]
frame #25: python() [0x4f876d]
frame #27: python() [0x4f7a28]
frame #28: python() [0x4f876d]
frame #30: python() [0x4f6128]
frame #32: python() [0x6415b2]
frame #37: __libc_start_main + 0xe7 (0x7f7ba8e93b97 in /lib/x86_64-linux-gnu/libc.so.6)
```
Then if I apply the bias reshape fix (posted below), I get this error:
```
(op_type:Softmax, name:): Inferred shape and existing shape differ in rank: (2) vs (3)
Loading model. Traceback (most recent call last):
  File "./test_onnx_via_caffe2.py", line 76, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./test_onnx_via_caffe2.py", line 48, in main
    rep = backend.prepare(model, device='CPU') # or 'CPU'
  File "/home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/caffe2/python/onnx/backend.py", line 704, in prepare
    model = onnx.shape_inference.infer_shapes(model)
  File "/home/user/projects/ml-frameworks-inference-comparison/venv/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str)
RuntimeError: Inferred shape and existing shape differ in rank: (2) vs (3)
```
Here's the forked mmconvert that I use to apply the fixes/workarounds:
```
#!/usr/bin/env python
import sys as _sys
import argparse
import mmdnn.conversion._script.convertToIR as convertToIR
import mmdnn.conversion._script.IRToCode as IRToCode
import mmdnn.conversion._script.IRToModel as IRToModel
from six import text_type as _text_type
import uuid
import os
import numpy as np

def _get_parser():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        '--srcFramework', '-sf',
        type=_text_type,
        choices=["caffe", "caffe2", "cntk", "mxnet", "keras", "tensorflow", 'tf', 'pytorch'],
        help="Source toolkit name of the model to be converted.")
    parser.add_argument(
        '--inputWeight', '-iw',
        type=_text_type,
        default=None,
        help='Path to the model weights file of the external tool (e.g caffe weights proto binary, keras h5 binary')
    parser.add_argument(
        '--inputNetwork', '-in',
        type=_text_type,
        default=None,
        help='Path to the model network file of the external tool (e.g caffe prototxt, keras json')
    parser.add_argument(
        '--dstFramework', '-df',
        type=_text_type,
        choices=['caffe', 'caffe2', 'cntk', 'mxnet', 'keras', 'tensorflow', 'coreml', 'pytorch', 'onnx'],
        required=True,
        help='Format of model at srcModelPath (default is to auto-detect).')
    parser.add_argument(
        '--outputModel', '-om',
        type=_text_type,
        required=True,
        help='Path to save the destination model')
    parser.add_argument(
        '--dump_tag',
        type=_text_type,
        default=None,
        help='Tensorflow model dump type',
        choices=['SERVING', 'TRAINING'])

    return parser


def _extract_ir_args(args, unknown_args, temp_filename):
    unknown_args.extend(['--srcFramework', args.srcFramework])
    if args.inputWeight is not None:
        unknown_args.extend(['--weights', args.inputWeight])
    if args.inputNetwork is not None:
        unknown_args.extend(['--network', args.inputNetwork])
    unknown_args.extend(['--dstPath', temp_filename])

    ir_parser = convertToIR._get_parser()
    return ir_parser.parse_known_args(unknown_args)


def _extract_code_args(args, unknown_args, temp_filename,network_filename):
    unknown_args.extend(['--dstFramework', args.dstFramework])
    unknown_args.extend(['--IRModelPath', temp_filename + '.pb'])
    unknown_args.extend(['--IRWeightPath', temp_filename + '.npy'])
    unknown_args.extend(['--dstModelPath', network_filename + '.py'])
    unknown_args.extend(['--dstWeightPath', temp_filename + '.npy'])
    code_parser = IRToCode._get_parser()
    return code_parser.parse_known_args(unknown_args)


def _extract_model_args(args, unknown_args, temp_filename):
    unknown_args.extend(['--framework', args.dstFramework])
    unknown_args.extend(['--inputNetwork', temp_filename + '.pb'])
    unknown_args.extend(['--inputWeight', temp_filename + '.npy'])
    unknown_args.extend(['--output', args.outputModel])
    model_parser = IRToModel._get_parser()
    return model_parser.parse_known_args(unknown_args)


def remove_temp_files(temp_filename, verbose=False):
    exts = ['.json', '.pb', '.npy', '.py']
    # exts = ['.pb', '.npy', '.py']
    for ext in exts:
        temp_file = temp_filename + ext
        if os.path.isfile(temp_file):
            os.remove(temp_file)
            if verbose:
                print('temporary file [{}] has been removed.'.format(temp_file))

def get_network_filename(framework, temp_filename, output_model_filename):
    if framework in ['pytorch']:
        return os.path.join(os.path.dirname(output_model_filename), os.path.basename(output_model_filename).split('.')[0])
    return temp_filename


def _main():
    parser = _get_parser()
    args, unknown_args = parser.parse_known_args()
    temp_filename = "generated_via_convert_fixed"
    ir_args, unknown_args = _extract_ir_args(args, unknown_args, temp_filename)
    
    # Convert to IR
    print("Converting to IR with args", ir_args)
    ret = convertToIR._convert(ir_args)
    if int(ret) != 0:
        _sys.exit(int(ret))

    # Convert to code
    network_filename = get_network_filename(args.dstFramework, temp_filename, args.outputModel)
    code_args, unknown_args = _extract_code_args(args, unknown_args, temp_filename, network_filename)
    print("IR to code with arguments: ", code_args)
    ret = IRToCode._convert(code_args)
    if int(ret) != 0:
        _sys.exit(int(ret))

    # Apply bias shape fix on the weights file
    print("Fixing bias shapes.")
    weights = np.load(temp_filename + '.npy', allow_pickle=True)
    for key in weights.item().keys():
        if 'bias' not in weights.item()[key]:
            continue
        if len(weights.item()[key]['weights'].shape) != 4:
            print("<2 layer:")      
            print(weights.item()[key]['weights'].shape)
            print(weights.item()[key]['bias'].shape)
            continue
        else:
            print(weights.item()[key]['weights'].shape)
            print(weights.item()[key]['bias'].shape)
            dims0 = weights.item()[key]['weights'].shape[3]
            weights.item()[key]['bias'] = weights.item()[key]['bias'].reshape((dims0,))
    np.save(open(temp_filename + '.npy', 'wb'), weights, allow_pickle=True)

    # Fix the Softmax shape
    print("Fixing the Softmax shape in the script (should report the line change)")
    script = ''
    with open(network_filename + '.py') as f:
        for line in f.readlines():
            output_size = 1000
            line_to_find = "(1, 1, {},)".format(output_size)
            replacement_line = "(1, {})".format(output_size)
            if line_to_find in line:
                print("Fixing line: " + line)
                line = line.replace(line_to_find, replacement_line)
                print("To: " + line)
            script += line

    with open(network_filename + '.py', 'w') as f:
        f.write(script)

    from mmdnn.conversion._script.dump_code import dump_code
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
    #remove_temp_files(temp_filename)


if __name__ == '__main__':
    _main()
```

**Comment by rainLiuplus** [comment]
Hi @petko10,

For the first error, the reason is that in caffe the convolutional bias is stored with the shape  info (num, channel, height, width) (actually all weights are stored in a flat shape but in [caffe_parser.py](https://github.com/microsoft/MMdnn/blob/master/mmdnn/conversion/caffe/transformer.py#L58) the weights are reshaped to be saved in the IR weights file) but the shape of [onnx bias](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv) should be one dimension. This has been fixed.

For the second error, it is caused by [Softmax]'s previous op [[Gemm](https://github.com/onnx/onnx/blob/master/docs/Operators.md#gemm)], which is corresponding to caffe's InnerProduct. Gemm's input shape is only allowed to be 2D, while the FullyConnected of other frameworks supports more than 2D input. Therefore, one workaround is to replace the [Gemm] with [MatMul] and [Add] but it doesn't seem to be a particularly good solution, maybe onnx modifying gemm to support higher dimensions is a better approach.

**Comment by petko10** [comment]
@rainLiuplus  Thanks for the response! Since the second error, as you said, is subject to either a custom or an upstream solution, I'll close this issue for the moment.
