### ISSUE TITLE
KeyError: 'block2_sepconv1' when converting keras 2.2.5 (tf backend) to caffe

### ISSUE THREAD

**Issue by tigerthu** [microsoft/MMdnn#724]
Platform (ubuntu 16.04):
Python version:2.7.12
Source framework with version (like keras 2.2.5 using TensorFlow backend 1.14.0):
Destination framework with version (like caffe1.0.0):
Pre-trained model path (webpath or webdisk path): xception

Running scripts:
IR network structure is saved as [4e0a5f0aab0e4e6f966de4bf4beeb00a.json].
IR network structure is saved as [4e0a5f0aab0e4e6f966de4bf4beeb00a.pb].
IR weights are saved as [4e0a5f0aab0e4e6f966de4bf4beeb00a.npy].
Parse file [4e0a5f0aab0e4e6f966de4bf4beeb00a.pb] with binary format successfully.
CaffeEmitter has not supported operator [SeparableConv].
block2_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block2_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block3_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block3_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block4_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block4_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block5_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block5_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block5_sepconv3
CaffeEmitter has not supported operator [SeparableConv].
block6_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block6_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block6_sepconv3
CaffeEmitter has not supported operator [SeparableConv].
block7_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block7_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block7_sepconv3
CaffeEmitter has not supported operator [SeparableConv].
block8_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block8_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block8_sepconv3
CaffeEmitter has not supported operator [SeparableConv].
block9_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block9_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block9_sepconv3
CaffeEmitter has not supported operator [SeparableConv].
block10_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block10_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block10_sepconv3
CaffeEmitter has not supported operator [SeparableConv].
block11_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block11_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block11_sepconv3
CaffeEmitter has not supported operator [SeparableConv].
block12_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block12_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block12_sepconv3
CaffeEmitter has not supported operator [SeparableConv].
block13_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block13_sepconv2
CaffeEmitter has not supported operator [SeparableConv].
block14_sepconv1
CaffeEmitter has not supported operator [SeparableConv].
block14_sepconv2
Target network code snippet is saved as [4e0a5f0aab0e4e6f966de4bf4beeb00a.py].
Target weights are saved as [4e0a5f0aab0e4e6f966de4bf4beeb00a.npy].
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 10, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/saver.py", line 9, in save_model
    MainModel.make_net(dump_net)
  File "4e0a5f0aab0e4e6f966de4bf4beeb00a.py", line 176, in make_net
    n = KitModel()
  File "4e0a5f0aab0e4e6f966de4bf4beeb00a.py", line 38, in KitModel
    n.block2_sepconv1_bn = L.BatchNorm(n.block2_sepconv1, eps=0.0010000000475, use_global_stats=True, ntop=1)
  File "/usr/caffe/python/caffe/net_spec.py", line 180, in __getattr__
    return self.tops[name]
KeyError: 'block2_sepconv1'

**Comment by rainLiuplus** [comment]
Hi @tigerthu, could you upload your model for us to debug? Thanks!
