### ISSUE TITLE
error converting from keras to caffe

### ISSUE THREAD

**Issue by TaeheeJeong** [microsoft/MMdnn#730]
Platform (like ubuntu 16.04/win10):ubuntu 16.04

Python version:Python 2.7.16

Source framework with version (like Tensorflow 1.4.1 with GPU):tensorflow 1.9.0

Destination framework with version (like CNTK 2.3 with GPU):caffe 1.0.0

Pre-trained model path (webpath or webdisk path):custom file

Running scripts: mmconvert -sf keras -iw model_076720.h5 -df caffe -om mycaffemodel

Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/taeheej/work/nobkup/anaconda2/envs/deephipy2f/bin/mmconvert", line 10, in <module>
    sys.exit(_main())
  File "/home/taeheej/work/nobkup/anaconda2/envs/deephipy2f/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/taeheej/work/nobkup/anaconda2/envs/deephipy2f/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "/home/taeheej/work/nobkup/anaconda2/envs/deephipy2f/lib/python2.7/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 120, in __init__
    'DepthwiseConv2D': layers.DepthwiseConv2D
  File "/home/taeheej/work/nobkup/anaconda2/envs/deephipy2f/lib/python2.7/site-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/home/taeheej/work/nobkup/anaconda2/envs/deephipy2f/lib/python2.7/site-packages/keras/utils/io_utils.py", line 197, in __init__
    'Received: {}.'.format(type(path)))
TypeError: Required Group, str or dict. Received: <type 'unicode'>.

**Comment by rainLiuplus** [comment]
Hi @TaeheeJeong, maybe [this workaround](https://github.com/keras-team/keras/issues/11269#issuecomment-431485085) could solve your issue.

Thanks!
