### ISSUE TITLE
tensorflow Frozen Graph to mxnet Error

### ISSUE THREAD

**Issue by jayle19930918** [microsoft/MMdnn#746]
Platform: win10

Python version: 3.6.9

Source framework with version: like Tensorflow 1.14.0 with CPU

Destination framework with version: mxnet 1.5.0 with GPU

Pre-trained model path (webpath or webdisk path): https://pan.baidu.com/s/1QFnJjenEunjqIKz1Om9Vtg
Extraction code:   ghvw

Running scripts: mmconvert -sf tensorflow -iw inceptionv1onfire.pb --inNodeName InputData/X --inputShape 224,224,3 --dstNodeName FullyConnected/Softmax -df mxnet -om inceptionv1onfire -dw mxnet_inceptionv1onfire-0000.params

Hi, I want to convert the pb file to mxnet model. I have converted TensorFlow mobilenet slim model with frozen_pb to mxnet successfully.  However, I failed to convert the above tensorflow pb model. Error occurs: 
  raise IOError("Graph doesn't have node [%s]." % name.split(':')[0])
  OSError: Graph doesn't have node [data].

The log is as follows: 
(gluon) E:\python\model_convert\mxnet>mmconvert -sf tensorflow -iw inceptionv1onfire.pb --inNodeName InputData/X --inputShape 224,224,3 --dstNodeName FullyConnected/Softmax -df mxnet -om inceptionv1onfire -dw mxnet_inceptionv1onfire-0000.params
WARNING:tensorflow:From d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_frozenparser.py:107: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

WARNING:tensorflow:From d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_frozenparser.py:108: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From d:\app\anaconda\install\envs\gluon\lib\site-packages\tensorflow\python\tools\strip_unused_lib.py:86: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
WARNING:tensorflow:From d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_frozenparser.py:147: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_frozenparser.py:161: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-10-11 11:06:46.512410: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_frozenparser.py:164: The name tf.train.export_meta_graph is deprecated. Please use tf.compat.v1.train.export_meta_graph instead.

IR network structure is saved as [76ddc54d558d495a8105afc36d9375c3.json].
IR network structure is saved as [76ddc54d558d495a8105afc36d9375c3.pb].
IR weights are saved as [76ddc54d558d495a8105afc36d9375c3.npy].
Parse file [76ddc54d558d495a8105afc36d9375c3.pb] with binary format successfully.
Warning: Graph Construct a self-loop node Dropout/cond/dropout/sub/x. Ignored.
Warning: Graph Construct a self-loop node Dropout/cond/dropout/rate. Ignored.
Warning: Graph Construct a self-loop node Dropout/cond/dropout/truediv/x. Ignored.
Warning: Graph Construct a self-loop node Dropout/cond/dropout/random_uniform. Ignored.
Detect input layer [Placeholder] using infer batch size, set it as default value [1]
Traceback (most recent call last):
  File "d:\app\anaconda\install\envs\gluon\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\app\anaconda\install\envs\gluon\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\app\anaconda\install\envs\gluon\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
  File "d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\_script\convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\_script\IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\common\DataStructure\emitter.py", line 22, in run
    self.save_code(dstNetworkPath, phase)
  File "d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\common\DataStructure\emitter.py", line 59, in save_code
    code = self.gen_code(phase)
  File "d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\mxnet\mxnet_emitter.py", line 102, in gen_code
    line = func(current_node)
  File "d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\mxnet\mxnet_emitter.py", line 997, in emit_Sub
    self.parent_variable_name(IR_node),
  File "d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\common\DataStructure\emitter.py", line 48, in parent_variable_name
    return self.IR_graph.get_parent_variable_name(IR_node.name, path)
  File "d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\common\DataStructure\graph.py", line 124, in get_parent_variable_name
    current_node = self.get_node(parent_name)
  File "d:\app\anaconda\install\envs\gluon\lib\site-packages\mmdnn\conversion\common\DataStructure\graph.py", line 72, in get_node
    raise IOError("Graph doesn't have node [%s]." % name.split(':')[0])
OSError: Graph doesn't have node [data].

I don't know how to solve this problem.

**Comment by ccl-private** [comment]
why did this close without solve?
