### ISSUE TITLE
Pytorch to IR: KeyError: 'sharedNet.0.weight'

### ISSUE THREAD

**Issue by ChenYizhao77** [microsoft/MMdnn#760]
Platform (like ubuntu 16.04/win10):ubuntu 16.04

Python version:3.6

Source framework with version (like Tensorflow 1.4.1 with GPU):Pytorch0.4.0 with GPU

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:
Traceback (most recent call last):
  File "tocaffe.py", line 103, in <module>
    pytorchparser.run(IR_file)
  File "/home/yckj2442/MMdnn-master/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/yckj2442/MMdnn-master/mmdnn/conversion/pytorch/pytorch_parser.py", line 101, in gen_IR
    func(current_node)
  File "/home/yckj2442/MMdnn-master/mmdnn/conversion/pytorch/pytorch_parser.py", line 237, in rename_Conv
    weight = self.state_dict[weights_name]
KeyError: 'sharedNet.0.weight'

**sharedNet.0.weight**
OrderedDict([('**sharedNet.function_modulelist.0.0.weight**', tensor([[[[ 0.0361, -0.0410, -0.0623],

Hi, as shown above, can you help me check why the weight name in 'current_node' cannot match the name in 'self.state_dict'. (In Conv layer). Thanks a lot!

**Comment by rainLiuplus** [comment]
Hi @ChenYizhao77, probably the naming rule of your PyTorch model weights has been changed. You can change this [line ](https://github.com/microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/pytorch_graph.py#L29)to adapt your model. Thanks!
