### ISSUE TITLE
Mxnet to IR error

### ISSUE THREAD

**Issue by LjwPanda** [microsoft/MMdnn#765]
Platform (like ubuntu 16.04/win10):
win10
Python version:
3.5
Source framework with version (like Tensorflow 1.4.1 with GPU):
mxnet1.5.0 without GPU
Destination framework with version (like CNTK 2.3 with GPU):
Tensorflow 1.4.1 without GPU
Pre-trained model path (webpath or webdisk path):
json:https://github.com/deepinsight/insightface/blob/master/deploy/mtcnn-model/det4-symbol.json
param:https://github.com/deepinsight/insightface/blob/master/deploy/mtcnn-model/det4-0001.params
Running scripts:
python -m mmdnn.conversion._script.convertToIR -f mxnet -n det4-symbol.json -w det4-0001.params -d Lnet --inputShape 15,24,24

I got error:
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator SliceChannel with name slice.
Traceback (most recent call last):
  File "E:\Anaconda3\envs\python3.5\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\Anaconda3\envs\python3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\envs\python3.5\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 197, in <module>
    _main()
  File "E:\Anaconda3\envs\python3.5\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "E:\Anaconda3\envs\python3.5\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "E:\Anaconda3\envs\python3.5\lib\site-packages\mmdnn\conversion\common\DataStructure\parser.py", line 22, in run
    self.gen_IR()
  File "E:\Anaconda3\envs\python3.5\lib\site-packages\mmdnn\conversion\mxnet\mxnet_parser.py", line 265, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "E:\Anaconda3\envs\python3.5\lib\site-packages\mmdnn\conversion\mxnet\mxnet_parser.py", line 376, in rename_UNKNOWN
    raise NotImplementedError()
NotImplementedError

my mmdnn version is 0.2.5.
thank you for help

**Comment by rainLiuplus** [comment]
Hi @LjwPanda, this op [SliceChannel] currently is not supported by MMdnn. You can refer [this](https://github.com/microsoft/MMdnn/wiki/Contribution-Guideline) to manually add it. Thanks!

**Comment by LjwPanda** [comment]
I see. Thank you for your answer
