### ISSUE TITLE
No module named 'caffe'

### ISSUE THREAD

**Issue by suakim** [microsoft/MMdnn#767]
Platform (like ubuntu 16.04/win10): Win10

Python version: 3.6.9

Source framework with version (like Tensorflow 1.4.1 with GPU): tensorflow-gpu 1.13.1

Destination framework with version (like CNTK 2.3 with GPU): caffe

Pre-trained model path (webpath or webdisk path): I trained the model myself. C:\Users\skim\MMdnn\tensorflow

Running scripts:

C:\Users\skim\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\skim\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\skim\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\skim\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\skim\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\skim\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From C:\Users\skim\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\tools\strip_unused_lib.py:86: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
2019-11-13 14:02:58.694385: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-11-13 14:02:58.833894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.759
pciBusID: 0000:01:00.0
totalMemory: 3.00GiB freeMemory: 2.43GiB
2019-11-13 14:02:58.843739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-11-13 14:02:59.306002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-13 14:02:59.311229: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-11-13 14:02:59.314479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-11-13 14:02:59.318534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2116 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
IR network structure is saved as [1d3677fe8fd54f5cb60d659481cf9ede.json].
IR network structure is saved as [1d3677fe8fd54f5cb60d659481cf9ede.pb].
IR weights are saved as [1d3677fe8fd54f5cb60d659481cf9ede.npy].
Traceback (most recent call last):
  File "c:\users\skim\appdata\local\continuum\anaconda3\envs\deeprestof\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\skim\appdata\local\continuum\anaconda3\envs\deeprestof\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\skim\AppData\Local\Continuum\anaconda3\envs\DeepResToF\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
  File "c:\users\skim\appdata\local\continuum\anaconda3\envs\deeprestof\lib\site-packages\mmdnn\conversion\_script\convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "c:\users\skim\appdata\local\continuum\anaconda3\envs\deeprestof\lib\site-packages\mmdnn\conversion\_script\IRToCode.py", line 9, in _convert
    from mmdnn.conversion.caffe.caffe_emitter import CaffeEmitter
  **File "c:\users\skim\appdata\local\continuum\anaconda3\envs\deeprestof\lib\site-packages\mmdnn\conversion\caffe\caffe_emitter.py", line 13, in <module>
    import caffe
ModuleNotFoundError: No module named 'caffe'**

**Comment by anathema43** [comment]
@rainLiuplus  I just came across this library, if i am conerting from caffe to tensorflow do i need both caffe and tensorflow installed ?

**Comment by JiahaoYao** [comment]
@anathema43 I think so. You should install both. If you have trouble installing the caffe, you might want to try docker: https://github.com/microsoft/MMdnn#install-with-docker-image.

**Comment by linmajia** [comment]
@anathema43 , you should install both. If you are using Ubuntu >= 17.10, you could install Caffe by executing the following command:
```bash
sudo apt install caffe-cpu
```
For TensorFlow, you need to install the version 1.13.1 now. New version support is in progress.

@JiahaoYao , thank you very much for the reply.
