### ISSUE TITLE
Keras layer of type `tensorflow.python.keras.engine.training.Model` is not supported

### ISSUE THREAD

**Issue by rsomani95** [microsoft/MMdnn#789]
Platform: macOS

**Python version:** 3.7.3
**Source framework with version:** Tensorflow 1.14, Keras 2.2.4
**Destination framework with version:** pytorch
**Pre-trained model path:** 'mobnetv2.h5' (irrelevant -- explained below)

I've tweaked the `keras2_parser.py` script to load my model directly (I'm certain this part doesn't cause the issue; in fact, it was done to avoid a bunch of other issues.

Here's how I'm loading my model inside keras2_parser.py`:
```python
import tensorflow as tf

def _load_model(...):
    base_model = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3),
                                                   include_top=False,
                                                   weights='imagenet')
    base_model.trainable = False
    return base_model

def __init__(...):
    model = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3),
                                              include_top=False,
                                              weights='imagenet')
    model.trainable = False
```

**script:** `mmconvert -sf keras -iw mobnetv2.h5 -df pytorch -om mobnetv2-keras.pth` (the `-iw mobnetv2.h5` is irrelevant I believe)
**Error message:**
```python
Traceback (most recent call last):
  File "/Users/rahulsomani/anaconda3/bin/mmconvert", line 8, in <module>
    sys.exit(_main())
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 146, in __init__
    self.keras_graph = Keras2Graph(model)
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/keras/keras2_graph.py", line 37, in __init__
    raise TypeError("Keras layer of type %s is not supported." % type(model))
TypeError: Keras layer of type <class 'tensorflow.python.keras.engine.training.Model'> is not supported.
```

My understanding is that the `Keras` version (2.2.4) shouldn't matter since I'm using `tf.keras`. I tried downgrading to 2.2.2 but then ran into dependency issues, and I can't seem to find the right tensorflow version supported with 2.2.2 (due to `keras-preprocessing` and `keras-applications` version conflicts. I tried tensorflow==1.14, 1.15, 2.0, 2.1).

Would really appreciate any help, thanks!

**Comment by XiaoXYe** [comment]
Hi @rsomani95 , actually we only support tensorflow version <=1.13.1 now. There maybe some unexpectable error if the version do not match with those we listed in requirements\linux-py3.txt
