### ISSUE TITLE
Unable to Replicate Usage Script Examples (Keras --> PyTorch) [ValueError: Object arrays cannot be loaded when allow_pickle=False]

### ISSUE THREAD

**Issue by rsomani95** [microsoft/MMdnn#790]
**Platform:** Ubuntu 18.04
**Python version:** 3.7.4
**Source framework with version:** Tensorflow-GPU 1.14, Keras 2.1.3
**Destination framework with version:** PyTorch 1.3
**Pre-trained model path:** imagenet_mobilenet.h5

Running scripts: 
`mmdownload -f keras -n mobilenet -o ./`
`mmconvert -sf keras -iw imagenet_mobilenet.h5 -df pytorch -om mobnet.pth`

Output:
```python
Using TensorFlow backend.
WARNING:tensorflow:From /home/rahul/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:504: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /home/rahul/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3828: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /home/rahul/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:235: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /home/rahul/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:166: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /home/rahul/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:171: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2020-02-05 10:52:08.801837: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-05 10:52:08.826450: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3492870000 Hz
2020-02-05 10:52:08.827682: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5607b0c79fb0 executing computations on platform Host. Devices:
2020-02-05 10:52:08.827708: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-02-05 10:52:08.828753: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2020-02-05 10:52:08.833957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:42:00.0
2020-02-05 10:52:08.834078: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64::/usr/local/cuda-10.1/lib64
2020-02-05 10:52:08.834183: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64::/usr/local/cuda-10.1/lib64
2020-02-05 10:52:08.834254: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64::/usr/local/cuda-10.1/lib64
2020-02-05 10:52:08.834323: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64::/usr/local/cuda-10.1/lib64
2020-02-05 10:52:08.834390: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64::/usr/local/cuda-10.1/lib64
2020-02-05 10:52:08.834479: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64::/usr/local/cuda-10.1/lib64
2020-02-05 10:52:08.838791: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-02-05 10:52:08.838822: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2020-02-05 10:52:08.925706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-05 10:52:08.925739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2020-02-05 10:52:08.925746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2020-02-05 10:52:08.927656: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5607b48c7190 executing computations on platform CUDA. Devices:
2020-02-05 10:52:08.927671: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-02-05 10:52:08.953885: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
WARNING:tensorflow:From /home/rahul/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1794: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

WARNING:tensorflow:From /home/rahul/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3135: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
/home/rahul/anaconda3/lib/python3.7/site-packages/keras/models.py:255: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
IR network structure is saved as [0f20379a159249fea25a4a595c2fcb1f.json].
IR network structure is saved as [0f20379a159249fea25a4a595c2fcb1f.pb].
IR weights are saved as [0f20379a159249fea25a4a595c2fcb1f.npy].
Parse file [0f20379a159249fea25a4a595c2fcb1f.pb] with binary format successfully.
Traceback (most recent call last):
  File "/home/rahul/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 36, in _load_weights
    self.weights_dict = np.load(file_name).item()
  File "/home/rahul/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/rahul/anaconda3/lib/python3.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rahul/anaconda3/bin/mmconvert", line 10, in <module>
    sys.exit(_main())
  File "/home/rahul/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/home/rahul/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/IRToCode.py", line 42, in _convert
    emitter = PytorchEmitter((args.IRModelPath, args.IRWeightPath))
  File "/home/rahul/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/pytorch/pytorch_emitter.py", line 41, in __init__
    self._load_weights(weight_path)
  File "/home/rahul/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 38, in _load_weights
    self.weights_dict = np.load(file_name, encoding='bytes').item()
  File "/home/rahul/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/rahul/anaconda3/lib/python3.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

The script does output the following files though:
```bash
0f20379a159249fea25a4a595c2fcb1f.json
0f20379a159249fea25a4a595c2fcb1f.npy
0f20379a159249fea25a4a595c2fcb1f.pb
```

Thank you for your time, I'd appreciate any help!

**Comment by poliveirap** [comment]
Hi, did you figure out this issue?

**Comment by murthy95** [comment]
@poliveirap I changed line 36 in mmdnn/conversion/common/DataStructure/emitter.py to 
`self.weights_dict = np.load(file_name, allow_pickle=True).item()`

**Comment by linmajia** [comment]
@rsomani95 , @poliveirap and @murthy95 , thank you for the feedback. Please refer to https://github.com/microsoft/MMdnn/issues/681 . The latest Master branch has already beed updated to explicitly use "allow_pickle=True".

**Comment by linmajia** [comment]
Duplicate of https://github.com/microsoft/MMdnn/issues/681
