### ISSUE TITLE
Tensorflow has not supported operator [Neg] with name [p_re_lu_37_1/Neg].

### ISSUE THREAD

**Issue by trippycode** [microsoft/MMdnn#806]
Platform (like ubuntu 16.04/win10): ubuntu 18.04

Python version: 3.6.10

Source framework with version (like Tensorflow 1.4.1 with GPU): 1.9.0

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts: mmconvert -sf tensorflow -iw ./model/tf_pnet_360_640model.pb --inNodeName input_12_1 --inputShape 360,640,3 --dstNodeName softmax_12_1/truediv -df caffe -om caffe_pnet_360
/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2020-03-18 16:03:48.054347: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Tensorflow has not supported operator [Neg] with name [p_re_lu_37_1/Neg].
Traceback (most recent call last):
  File "/home/amit/anaconda3/envs/tf-gpu/bin/mmconvert", line 8, in <module>
    sys.exit(_main())
  File "/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/mmdnn/conversion/tensorflow/tensorflow_frozenparser.py", line 379, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "/home/amit/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/mmdnn/conversion/tensorflow/tensorflow_frozenparser.py", line 441, in rename_UNKNOWN
    assert False
AssertionError

**Comment by XiaoXYe** [comment]
Hi @trippycode , “Neg” was unsupported in tensorflow parser yet, we will add it in future version.

**Comment by trippycode** [comment]
Sure thanks for the update
