### ISSUE TITLE
Mxnet to tensorflow

### ISSUE THREAD

**Issue by Manideep08** [microsoft/MMdnn#833]
Platform (like ubuntu 16.04/win10): Google Colab

Python version: 3.6.9

Source framework with version : MXNET with GPU

Destination framework with version : Tensorflow 1.14 GPU

Pre-trained model path (webpath or webdisk path): https://github.com/YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices/blob/master/head_detection/saved_model/configuration_10_160_17L_4scales_v1_2019-09-20-13-08-26/train_10_160_17L_4scales_v1_iter_800000.params

Running scripts:

I am trying to convert [this](https://github.com/YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices/blob/master/head_detection/symbol_farm/symbol_10_160_17L_4scales_v1_deploy.json) to IR form and then to tensorflow. But I am facing issues as below

**Code :** 
!mmtoir -f mxnet -n symbol_10_160_17L_4scales_v1_deploy.json -d rand_scl --inputShape 3,256,256 

**Error messages**

/usr/local/lib/python3.6/dist-packages/mxnet/module/base_module.py:55: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
	data
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator slice_axis with name slice_axis16.
Traceback (most recent call last):
  File "/usr/local/bin/mmtoir", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 263, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 374, in rename_UNKNOWN
    raise NotImplementedError()
NotImplementedError

Could you please assist me overthis?

**Comment by XiaoXYe** [comment]
Hi @Manideep08 , slice_axis op is not supported by MXNET parser currently. We will add it in future release.
