### ISSUE TITLE
No module named 'sync_batchnorm'

### ISSUE THREAD

**Issue by MarlNox** [microsoft/MMdnn#843]
Hi there I'm trying to convert a Pytorch model into Tensorflow, but im running into an issue. 
Currently I'm working on Colab as an FYI. 
The model I'm working on can be found [here ](https://github.com/AliaksandrSiarohin/first-order-model)

When I try to convert the model,  I Get the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 76, in __init__
    model = torch.load(model_file_name)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'sync_batchnorm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(model, inputshape[0])
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 78, in __init__
    model = torch.load(model_file_name, map_location='cpu')
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'sync_batchnorm'

Any ideas on how to fix it?

**Comment by XiaoXYe** [comment]
Hi @MarlNox ,it seems that your model cannot be load correctly by `torch.load`, what about check your pytorch version and your model requirements?
Anc MMdnn requirements we recommand are placed in `MMdnn\requirements\linux-py3.txt`

**Comment by linmajia** [comment]
@MarlNox , thank you very much for the feedback. It seems that you are using the [Synchronized-BatchNorm-PyTorch](https://github.com/vacancy/Synchronized-BatchNorm-PyTorch) module (in the "sync_batchnorm" folder of your repos). I think you may try adding the path of "sync_batchnorm" to the PYTHONPATH environment variable.
