### ISSUE TITLE
Cannot convert TF InceptionResNet to IR

### ISSUE THREAD

**Issue by KyriaAnnwyn** [Microsoft/MMdnn#86]
Platform (like ubuntu 16.04/win10):ubuntu16.04

Python version:3.5

Source framework with version (like Tensorflow 1.4.1 with GPU):TF 1.5 with GPU

Destination framework with version (like CNTK 2.3 with GPU):Caffe

Pre-trained model path (webpath or webdisk path): https://yadi.sk/d/OnH0586P3SqoV3 

Running scripts:

**Comment by KyriaAnnwyn** [comment]
Cannot convert the provided net to IR.
I tried to create new graph using freeze_graph.py and after that to use optimize_for_inference_lib.py.
I got a new graph, but when I try to convert the net to IR using python -m mmdnn.conversion._script.convertToIR I get the following error:

Info: Trying to parse file [optimizedScript2.pb] with binary format but failed with error [Error parsing message].
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 140, in <module>
    _main()
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 135, in _main
    ret = _convert(args)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 48, in _convert
    parser = TensorflowParser(args.network, args.weights, args.frozen_pb, args.dstNodeName)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 185, in __init__
    model = TensorflowParser._load_meta(meta_file)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 83, in _load_meta
    load_protobuf_from_file(meta_graph, model_network_path)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/common/IR/IR_graph.py", line 28, in load_protobuf_from_file
    text_format.Parse(file_content.decode('UTF-8'), container, allow_unknown_extension=True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 92: invalid continuation byte

though the input file is binary.

what should I do to avoid this error&

**Comment by kitstar** [comment]
Hi @KyriaAnnwyn , frozen graph is not supported now. Welcome to contribute to it (not much different from tf checkpoint format). Thanks.

**Comment by KyriaAnnwyn** [comment]
Hi @kitstar! Thank you for your answer. I also tried other graphs (optimized without freezing and just meta file).
If I take optimized *.pb I get this error message:
Info: Trying to parse file [optimizedScript2.pb] with binary format but failed with error [Error parsing message].
And after that the file is parsed as text file and it leads to an error as it is binary.

If I try to convert *.meta file saved in the checkpoint I also get error:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 140, in <module>
    _main()
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 135, in _main
    ret = _convert(args)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 72, in _convert
    parser.run(args.dstPath)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 280, in gen_IR
    func(current_node)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 350, in rename_Placeholder
    IR_node = self._convert_identity_operation(source_node, new_op='DataInput')
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 387, in _convert_identity_operation
    TensorflowParser._copy_and_reop(source_node, IR_node, new_op)
  File "/home/ml/.virtualenvs/tensorflow3/lib/python3.5/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 297, in _copy_and_reop
    assert source_node.layer.attr['dtype'].type in TensorflowParser.dtype_map, 'type [{}] is unknown.'.format(source_node.layer.attr['dtype'].type)
AssertionError: type [10] is unknown.

This refers to Switch operators and also produces error messages:
Tensorflow has not supported operator [NoOp] with name [InceptionResnetV1/Conv2d_1a_3x3/BatchNorm/cond/AssignMovingAvg/sub/Switch:1]

Maybe you could help me with dealing this error.

**Comment by KyriaAnnwyn** [comment]
I tried inception_resnet_v2 from slim library and its conversion works ok. The code for model creation is quite similar:
https://yadi.sk/d/_nhw2ze33SsJ38 - contains 2 py model files

**Comment by kitstar** [comment]
Hi @KyriaAnnwyn,

1. "type[10] is unknown" fixed.

1. Could you provide your convertToIR command? Seems you didn't set a proper dstNodeName. You can also provide the meta file for me to reproduce.

Thanks.

**Comment by KyriaAnnwyn** [comment]
Hi, @kitstar 

This is my convert cmd line: python -m mmdnn.conversion._script.convertToIR -f tensorflow -d IRV1 -n model-20180113-230848.meta --dstNodeName embeddings

and meta file for it https://yadi.sk/d/euys0ILO3StePQ

I've checked the net has node embeddings. 

Maybe I have some old version old mmdnn: I installed this one
pip install https://github.com/Microsoft/MMdnn/releases/download/0.1.3/mmdnn-0.1.3-py2.py3-none-any.whl

Your help is really valuable for me!
