### ISSUE TITLE
pytorch2keras: ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by zhang-f** [microsoft/MMdnn#879]
Platform (like ubuntu 16.04/win10): ubuntu 18.04

Python version: 3.6.8

Source framework with version (like Tensorflow 1.4.1 with GPU):  pytorch 1.15.1

Destination framework with version (like CNTK 2.3 with GPU): keras 2.2.4

Pre-trained model path (webpath or webdisk path): 

Running scripts: mmconvert -sf pytorch -in pcifar.pth -df keras -om cifar.h5

~~~
Traceback (most recent call last):
  File "/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 81, in __init__
    model = torch.load(model_file_name)
  File "/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fanzh/.conda/envs/dba/bin/mmtoir", line 8, in <module>
    sys.exit(_main())
  File "/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 197, in _main
    ret = _convert(args)
  File "/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 97, in _convert
    parser = PytorchParser151(model, inputshape[0])
  File "/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 521, in __init__
    super(PytorchParser151, self).__init__(model_file_name, input_shape)
  File "/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 83, in __init__
    model = torch.load(model_file_name, map_location='cpu')
  File "/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models'

**Comment by linmajia** [comment]
@zhang-f , thank you very much for the feedback. You need to keep the model module in the same folder when loading the serialized model. Please refer to https://github.com/pytorch/pytorch/issues/18325 and https://github.com/pytorch/pytorch/issues/18325 for solution.

**Comment by zhang-f** [comment]
@linmajia , thanks so much!!!

**Comment by XinyingZheng** [comment]
> @linmajia , thanks so much!!!

放在一个目录下，对应你的是放在/home/fanzh/.conda/envs/dba/lib/python3.6/site-packages/mmdnn/conversion/pytorch下面么
