### ISSUE TITLE
ResNet v1_101 Tensorflow -> Pytorch ERROR: Input 0 of node map/Shape was passed float from Placeholder:0 incompatible with expected string

### ISSUE THREAD

**Issue by nile649** [microsoft/MMdnn#886]
The title says it all.

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node map/Shape was passed float from Placeholder:0 incompatible with expected string.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/mmconvert", line 8, in <module>
    sys.exit(_main())
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 66, in _convert
    parser = TensorflowParser(args.network, args.weights, args.dstNodeName)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 308, in __init__
    tensorflow.import_graph_def(transformed_graph_def, name='', input_map=input_map)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node map/Shape was passed float from Placeholder:0 incompatible with expected string.

```

**Comment by nile649** [comment]
Tensorflow version ==1.15
Downgrade -> Tensorflow version ==1.4.0
ERROR : TypeError: Cannot convert a tensor of type float32 to an input of type string
