### ISSUE TITLE
PReLU is not support yet?

### ISSUE THREAD

**Issue by Pinnh** [Microsoft/MMdnn#89]
Platform (ubuntu 16.04):

Python version: 2.7

Follow issue happens when use PReLU layer, can you support it?
thanks.

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 140, in <module>
    _main()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 135, in _main
    ret = _convert(args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 9, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/transformer.py", line 316, in __init__
    graph = GraphBuilder(def_path, self.input_shape, self.is_train_proto, phase).build()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/graph.py", line 447, in build
    graph.compute_output_shapes(self.model)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/graph.py", line 266, in compute_output_shapes
    node.output_shape = TensorShape(*NodeKind.compute_output_shape(node))
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/graph.py", line 126, in compute_output_shape
    return LAYER_DESCRIPTORS[node.kind](node)
KeyError: None

**Comment by kitstar** [comment]
Hi @Pinnh . Sure. What is your dest framework? I can also add it.

**Comment by Pinnh** [comment]
OK, I just extract caffe params to the intermediate representation, Pytorch may better or other framework. thanks a lot ~

**Comment by galli-leo** [comment]
Could you also add Prelu to the CoreML emitter? (Not sure if this is the right place to post)

**Comment by kitstar** [comment]
@galli-leo Thanks for your code commit!
