### ISSUE TITLE
error:caffe-tensorflow

### ISSUE THREAD

**Issue by huafeihuayu** [microsoft/MMdnn#892]
Traceback (most recent call last):
  File "e:\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\envs\tensorflow\Scripts\mmconvert.exe\__main__.py", line 7, in <module>
  File "e:\anaconda3\envs\tensorflow\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "e:\anaconda3\envs\tensorflow\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 16, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", inputshape[0], phase = args.caffePhase)
  File "e:\anaconda3\envs\tensorflow\lib\site-packages\mmdnn\conversion\caffe\transformer.py", line 345, in __init__
    print (self.graph)
  File "e:\anaconda3\envs\tensorflow\lib\site-packages\mmdnn\conversion\caffe\graph.py", line 314, in __str__
    s.append('{:<20} {:<30} {!s:>20} {!s:>20}'.format(node.kind, node.name, data_shape, tuple(out_shape)))
TypeError: unsupported format string passed to NoneType.__format__

**Comment by huafeihuayu** [comment]
Please help me
