### ISSUE TITLE
Convert Models from Caffe to Tensorflow

### ISSUE THREAD

**Issue by seanchung2** [Microsoft/MMdnn#9]
I got some pre-trained model on Caffe and wanna convert them to tensorflow (`.ckpt`). Some of `.caffemodel` files have been converted into numpy (`.npy`). Is there any way to convert them into the checkpoint (`.ckpt`)?
Thank you.

**Comment by kitstar** [comment]
Hi, Please refer the last step of [Tensorflow ReadME](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/README.md) and see if it works. Thanks.

**Comment by seanchung2** [comment]
Hi,

My numpy files were converted by [ethereon](https://github.com/ethereon/caffe-tensorflow)'s converter. Since the output by his converter will include `from kaffe.tensorflow import Network`, they can't be fit into your converter.

So I tried to use your caffe to IR converter. The error happened as following:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 156, in <module>
    _main()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 151, in _main
    ret = _convert(args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 10, in _convert
    graph = transformer.transform_graph()
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/transformer.py", line 348, in transform_graph
    mapped_node = self.map_node(node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/transformer.py", line 368, in map_node
    mapped_node = map_func(node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/mapper.py", line 117, in map_pooling
    kwargs, padding = cls.get_kernel_params(node)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/mapper.py", line 38, in get_kernel_params
    if node.kernel_parameters.p_h > 0 or node.kernel_parameters.p_w > 0:
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/graph.py", line 187, in kernel_parameters
    k_h = self.get_kernel_value(params.kernel_h, params.kernel_size, 0)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/caffe/graph.py", line 180, in get_kernel_value
    raise ValueError('Unable to determine kernel parameter!')
ValueError: Unable to determine kernel parameter!
```

Can you please check it out?
If you wanna reproduce the error, here is my caffe model: [Xception](https://drive.google.com/drive/folders/0B7ENM-r6t_TzMlVVeW9uM1p3YXM?usp=sharing)

Thank you.

**Comment by kitstar** [comment]
I will follow up. Thanks.

**Comment by kitstar** [comment]
Hi @seanchung2 ,
The problem is lacking support of Global Pooling in old version MMdnn. Newest master implement it and tested in my env. Please have a try.
Thanks.
